### PR TITLE
ConsoleInteraction.py: Typo Fix

### PR DESCRIPTION
**Pull request by mansenfranzen**

### CODE REVIEW

**Comment by Asnelchristian** [comment]
please can you add more info to you commit message ( like what you changed ) :)

**Comment by sils1297** [comment]
Hi,

it seems that your commit message doesn't contain enough information. Don't worry, most people don't know about good commit messages when they join us, including very experienced developers :)

The most important part is the first line of your commit message - maintainers will use it to read through a large number of commits and thus it's important that it's short but most importantly concise. I'd heartily recommend reading http://coala.readthedocs.io/en/latest/Getting_Involved/Writing_Good_Commits.html !

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

Cheers!

**Comment by mansenfranzen** [comment]
Right, thanks for the advice and the corresponding git commands. Changed the description accordingly.

**Comment by tushar-rishav** [comment]
ack https://github.com/coala-analyzer/coala/pull/2514/commits/c8a6cf9d8f8d3c3a811086852f7c02c907e9bffa

**Comment by sils1297** [comment]
hi, the test fail is nondeterministically, don't worry.

But:
it looks like your PR is out of date and needs a rebase. [This page](http://coala.readthedocs.org/en/latest/Users/Tutorials/Git_Help.html) may help you to get started on this. (*Do not press the update branch button. It's evil.*)

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

Ping us on [our gitter channel](https://gitter.im/coala-analyzer/coala) if you need help!

**Comment by mansenfranzen** [comment]
Okay, fetched from upstream, rebased my branched, and forced push. Hope it works out.

**Comment by sils1297** [comment]
looks good :)

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2514/commits/aa7a0833efa335714e2b7b56476572b5b07821f1 , as an optional improvement suggestion for future reference: `Fix typo` isn't particularly precise and rather describes the issue (typo) than the actual change you did. Thus commit messages with a `Fix` in it are usually bad ;)

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
