### PR TITLE
Rename Compatability.py to Compatibility.py

### PR DESCRIPTION
**Pull request by underyx**

### CODE REVIEW

**Comment by sils1297** [comment]
:D it could have been my typo

**Comment by sils1297** [comment]
ack which might also

**Comment by sils1297** [comment]
ack

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2762/commits/39cd5f6c12bb8b3be7a0e0ae7c2290305fd0206d

**Comment by sils1297** [comment]
@underyx command timeout - getting this on otherPRs as well, might that be related to caching?

**Comment by sils1297** [comment]
rebuilding

**Comment by chauffer** [comment]
@rultor merge

**Pull request merged**
