### PR TITLE
travis.yml : Fixes #1755

### LINKED ISSUE #1755: Small typo in the travis.yml file.
The travis.yml file has a small typo error, on the commented second line of the file, in the language block.
```
language:
  # The `objective-c` language by default uses a OSX build container. This
  # is the currently supported method of using a OSX xontainer.    <------ Here. (This should be "container")
  - objective-c

env:
  global:
    - PYENV_ROOT=~/.pyenv
    - PATH=$PYENV_ROOT/shims:$PATH
  matrix:
    - PYTHON_VERSION=3.4.2

install:
  - bash .misc/deps.osx.sh

script:
  - bash .misc/tests.sh

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b9493488a4edb005c5c6
```

### PR DESCRIPTION
**Pull request by sudoankit**
Fixes a small typo in travis.yml
Addresses #1755

### CODE REVIEW

**Comment by AbdealiJK** [comment]
@sudoankit The commit message needs to be fixed

And also, we do not allow the "Merge branch ..." commit - you need to rebase correctly.

Take a look at http://coala.readthedocs.org/en/latest/Getting_Involved/Newcomers.html

**Comment by sudoankit** [comment]
Sorry, for that. I'm rebasing. 
Or should I give a fresh PR?

**Comment by AbdealiJK** [comment]
DO not create a new PR.
amend and rebase on this.

The newcomer guide should have all the info you need :)
You can always talk to us on gitter if you need more help

**Comment by sudoankit** [comment]
Thank you. Working on it.

**Comment by AbdealiJK** [comment]
Closing this as the fork is deleted

**Pull request closed without merging**
