### PR TITLE
Close File Descriptors

### PR DESCRIPTION
**Pull request by sils1297**

### CODE REVIEW

**Comment by Makman2** [comment]
We need to use `os.linesep` , see http://stackoverflow.com/questions/454725/python-get-proper-line-ending .

**Comment by sils1297** [comment]
Would you mind correcting this one?

**Comment by Makman2** [comment]
Or even better : use the `text` param of `mkstemp`  to open the file in text mode

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
