### PR TITLE
Fixed issue 2491 typo

### PR DESCRIPTION
**Pull request by IgnatiousFlo**

### CODE REVIEW

**Comment by sils1297** [comment]
Hi,

it seems that your commit message doesn't contain enough information. Don't worry, most people don't know about good commit messages when they join us, including very experienced developers :)

The most important part is the first line of your commit message - maintainers will use it to read through a large number of commits and thus it's important that it's short but most importantly concise. I'd heartily recommend reading http://coala.readthedocs.io/en/latest/Getting_Involved/Writing_Good_Commits.html !

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

Cheers!

**Comment by Adrianzatreanu** [comment]
Hey. Seems your commit message and change are good this time. All you need to do is rebase.
Depending on how you have setup your remotes, something like
``git pull upstream master --rebase`` , where upstream is the name of the official coala remote you have added (if you havent, do a git remote add upstream coala_repo_link)

**Comment by sils1297** [comment]
Hi,

it looks like your PR is out of date and needs a rebase. [This page](http://coala.readthedocs.org/en/latest/Users/Tutorials/Git_Help.html) may help you to get started on this. (*Do not press the update branch button. It's evil.*)

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

Ping us on [our gitter channel](https://gitter.im/coala-analyzer/coala) if you need help!

**Comment by sils1297** [comment]
Hey, this worked and is great. But I did something wrong, I forgot about this and now something else was merged :/ so you need to do a rebase again... I'm sorry. It's a bit annoying.

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2552/commits/750b4d0f9476051d247f77d9175fc3163497bfff

**Comment by mr-karan** [comment]
@IgnatiousFlo You there? I think it again needs a rebase. It isn't merged, yet :)

**Comment by IgnatiousFlo** [comment]
Hi,

Sorry. I'm at work now and can't do the rebase but will as soon as I get
home.

Cheers.

**Comment by Asnelchristian** [comment]
reack https://github.com/coala-analyzer/coala/pull/2552/commits/7c19031235e830d0eecdadc076a506722e90ca9e

**Comment by sils1297** [comment]
@rultor merge

**Comment by IgnatiousFlo** [comment]
Cool. Thanks. That was my first ever contribution to a project. I will definitely be back to help again soon. :)

**Comment by Asnelchristian** [comment]
Great you are welcome here :) 
Good job :) :+1:

**Pull request merged**
