### PR TITLE
Misc message fixes

### PR DESCRIPTION
**Pull request by shivanipoddariiith**
Executing "run_tests.py" without installing gettext, prompts the user with the following message:
screen shot 2015-03-07 at 1 34 05 pm
The message is not clear enough to state that, msgfmt requires "gettext" to be installed in the correct path so as to recover from the error.
The error message needs to be fixed for the same.

### CODE REVIEW

**Comment by sils1297** [comment]
Can you retry on current master? Got a fix pushed yesterday as I promised
you.
Am 07.03.2015 09:27 schrieb "Shivani Poddar" <notifications@github.com>:

**Comment by shivanipoddariiith** [comment]
I did update my repo before I tried again today. Wonder why it showed me the same error.

**Comment by sils1297** [comment]
I had an unstable internet connection while pushing. Seems commits didn't
get up. (These trains are too fast these days...) Could you try on
wip/sils/newlines branch?
Am 07.03.2015 19:44 schrieb "Shivani Poddar" <notifications@github.com>:

**Comment by sils1297** [comment]
Sorry this something slightly related. Message could be better indeed. I'll
take a look at this. Thanks.
Am 07.03.2015 21:00 schrieb "Lasse Schuirmann" <lasse.schuirmann@gmail.com>:

**Comment by shivanipoddariiith** [comment]
Ah, hard luck, I fixed another issue around, so could you check if those 2 are in sync now. I could move on to other things then :)

**Comment by sils1297** [comment]
Go, move on. I'll try to tidy up as much as possible on Monday.
Am 07.03.2015 21:06 schrieb "Shivani Poddar" <notifications@github.com>:

**Comment by sils1297** [comment]
See also https://github.com/coala-analyzer/coala/commit/d3f890938225636b87c03794851d1bc787f619b1 by the way. Is already acknowledged so it will probably be pushed this evening or so.

**Comment by sils1297** [comment]
Please rephrase your commit messages. We're using the same rules as GNOME, written down somewhere in docs/getting_involved.

Second commit: this message would only be applicable if the save setting is set to non-false.

**Comment by sils1297** [comment]
Art didn't see Mischa already reviewed. If my comment says something else he's right because he probably took more time than I could now.

**Comment by shivanipoddariiith** [comment]
@Makman2 You are right about this confusing the user, I'd just remove it for what I feel. Should we go ahead with that then ?

**Comment by Makman2** [comment]
ah yes sorry. A new pull request for my issue #367 is really better^^
Okay so just rebase and delete the last commit^^

**Comment by shivanipoddariiith** [comment]
So, I have rough commits for the 3 odd issues we had. Removed the one about .coafile.
I still have the one about coverage bug and the gettext error message fix. Also added some Mac hints.
If these look okay, I can clean this up. :)

**Comment by sils1297** [comment]
@shivanipoddariiith we usually make our commits perfect, so each commit is one change and we don't push a row of commits like

 * Add something
 * Ooops that was wrong, correction
 * Again
 * ...

but we squash all the "oops" commits so we have very few perfect commits.

**Comment by sils1297** [comment]
and we rebase, so you shouldn't have a commit like "resolving merge commits"

**Comment by sils1297** [comment]
just as GNOME does (due to bugzilla patch submittance)

**Comment by sils1297** [comment]
As for the commit messages, our specification is a bit imprecise, I filed https://github.com/coala-analyzer/coala/issues/371 for this. Please use imperative language for the shortlog, thats common and also in the GNOME Commit message guidelines.

**Comment by Makman2** [comment]
So far what I know for the commit messages:
- Every shortlog starts with a tag:
  `tag: ...`
- After the tag a short description follows:
  `tag: Add something`
- The shortlog has 50 chars maximum!
- If you want to be more detailed since the shortlog doesn't suffice, wrap two lines and write the detailed one:
  ```
  tag: Add something

  Add the new super-duper component that does whatever it should do.
  I write even more in more than one line since I want it...
  ```
- The detailed log has 72 chars per line maximum! (I hope it's 72.. It confuses me everytime^^)
- GitHub supports automatic linking for issues and references them online. Just type the issue into the commit message :)
  i.e. `Fixes #0815` (That would even close the issue when this commit gets merged, but that's described more detailed on github's website^^)

**Comment by sils1297** [comment]
@Makman2 about commit messages: The tag is not mandantory but it's great to get some context. And please don't rely on github and provide a full link to the issue, not only the number. (Especially since we're thinking about switching to phabricator at some point)

**Comment by sils1297** [comment]
looks good besides indentation

**Comment by sils1297** [comment]
pushed with modified commit message

**Pull request closed without merging**
