### PR TITLE
CI: Use golang dependency manager

### PR DESCRIPTION
**Pull request by sudheesh001**
Uses goop the simple golang dependency manager
for installing and managing dependencies needed for
golang in the coala project.

Fixes https://github.com/coala-analyzer/coala/issues/1501

### CODE REVIEW

**Comment by sudheesh001** [comment]
Yup it does work, here's the part of the circle CI log
```log
+ go get -u github.com/karmakaze/goop
+ goop install
=> Fetching github.com/golang/lint/golint...
Cloning into '/home/ubuntu/coala/.vendor/tmp/src/github.com/golang/lint'...
remote: Counting objects: 531, done.
remote: Total 531 (delta 0), reused 0 (delta 0), pack-reused 531
Receiving objects: 100% (531/531), 220.70 KiB | 254.00 KiB/s, done.
Resolving deltas: 100% (314/314), done.
Checking connectivity... done.
Checking out "32a87160691b3c96046c0c678fe57c5bef761456"
=> Fetching golang.org/x/tools/cmd/goimports...
2016/02/16 06:18:03 get "golang.org/x/tools/cmd/goimports": found meta tag vcs.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/cmd/goimports?go-get=1
2016/02/16 06:18:03 get "golang.org/x/tools/cmd/goimports": verifying non-authoritative meta tag
Cloning into '/home/ubuntu/coala/.vendor/tmp/src/golang.org/x/tools'...
remote: Sending approximately 12.83 MiB ...
remote: Counting objects: 1114, done
remote: Finding sources: 100% (201/201)
remote: Total 15353 (delta 10291), reused 15334 (delta 10291)
Receiving objects: 100% (15353/15353), 10.12 MiB | 17.47 MiB/s, done.
Resolving deltas: 100% (10291/10291), done.
Checking connectivity... done.
Checking out "cd3cb7be66fa0563f7ae86a1b3072603a54cd9bf"
=> Fetching sourcegraph.com/sqs/goreturns...
2016/02/16 06:18:06 get "sourcegraph.com/sqs/goreturns": found meta tag vcs.metaImport{Prefix:"sourcegraph.com/sqs/goreturns", VCS:"git", RepoRoot:"https://github.com/sqs/goreturns"} at https://sourcegraph.com/sqs/goreturns?go-get=1
Cloning into '/home/ubuntu/coala/.vendor/tmp/src/sourcegraph.com/sqs/goreturns'...
remote: Counting objects: 89, done.
remote: Total 89 (delta 0), reused 0 (delta 0), pack-reused 89
Receiving objects: 100% (89/89), 1.05 MiB | 548.00 KiB/s, done.
Resolving deltas: 100% (46/46), done.
Checking connectivity... done.
Checking out "b368f1f77f2950c753e05a6a29acfc487fa7a959"
=> Fetching dependencies for github.com/golang/lint/golint...
=> Fetching dependencies for golang.org/x/tools/cmd/goimports...
Fetching https://golang.org/x/net/html?go-get=1
Parsing meta tags from https://golang.org/x/net/html?go-get=1 (status code 200)
get "golang.org/x/net/html": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/html?go-get=1
get "golang.org/x/net/html": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
golang.org/x/net (download)
Fetching https://golang.org/x/net/html/atom?go-get=1
Parsing meta tags from https://golang.org/x/net/html/atom?go-get=1 (status code 200)
get "golang.org/x/net/html/atom": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/html/atom?go-get=1
get "golang.org/x/net/html/atom": verifying non-authoritative meta tag
2016/02/16 06:18:13 get "golang.org/x/net": found meta tag vcs.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net?go-get=1
Checking out "cbbbe2bc0f2efdd2afb318d93f1eadb19350e4a3"
=> Fetching dependencies for sourcegraph.com/sqs/goreturns...
=> Installing github.com/golang/lint/golint...
=> Installing golang.org/x/tools/cmd/goimports...
=> Installing sourcegraph.com/sqs/goreturns...
=> Installing golang.org/x/net...
WORK=/tmp/go-build492286567
mkdir -p $WORK/golang.org/x/tools/go/exact/_obj/
mkdir -p $WORK/golang.org/x/tools/go/
cd /home/ubuntu/coala/.vendor/src/golang.org/x/tools/go/exact
/usr/local/go/pkg/tool/linux_amd64/compile -o $WORK/golang.org/x/tools/go/exact.a -trimpath $WORK -p golang.org/x/tools/go/exact -complete -buildid adb5b5ded18126c04ca0af8a59a0ef9921bb0ea4 -D _/home/ubuntu/coala/.vendor/src/golang.org/x/tools/go/exact -I $WORK -pack ./exact.go ./go14.go
mkdir -p /home/ubuntu/coala/.vendor/pkg/linux_amd64/golang.org/x/tools/go/
mv $WORK/golang.org/x/tools/go/exact.a /home/ubuntu/coala/.vendor/pkg/linux_amd64/golang.org/x/tools/go/exact.a
mkdir -p $WORK/golang.org/x/tools/go/types/_obj/
cd /home/ubuntu/coala/.vendor/src/golang.org/x/tools/go/types
/usr/local/go/pkg/tool/linux_amd64/compile -o $WORK/golang.org/x/tools/go/types.a -trimpath $WORK -p golang.org/x/tools/go/types -complete -buildid 490264033702534d074efa9867121f6581bed9a3 -D _/home/ubuntu/coala/.vendor/src/golang.org/x/tools/go/types -I $WORK -I /home/ubuntu/coala/.vendor/pkg/linux_amd64 -pack ./api.go ./assignments.go ./builtins.go ./call.go ./check.go ./conversions.go ./decl.go ./errors.go ./eval.go ./expr.go ./exprstring.go ./initorder.go ./labels.go ./lookup.go ./methodset.go ./object.go ./objset.go ./operand.go ./ordering.go ./package.go ./predicates.go ./resolver.go ./return.go ./scope.go ./selection.go ./sizes.go ./stmt.go ./type.go ./typestring.go ./typexpr.go ./universe.go
mv $WORK/golang.org/x/tools/go/types.a /home/ubuntu/coala/.vendor/pkg/linux_amd64/golang.org/x/tools/go/types.a
mkdir -p $WORK/golang.org/x/tools/go/gcimporter/_obj/
cd /home/ubuntu/coala/.vendor/src/golang.org/x/tools/go/gcimporter
/usr/local/go/pkg/tool/linux_amd64/compile -o $WORK/golang.org/x/tools/go/gcimporter.a -trimpath $WORK -p golang.org/x/tools/go/gcimporter -complete -buildid 419c993cf7af19fd9b9c9b0e72f20e20f3b722a1 -D _/home/ubuntu/coala/.vendor/src/golang.org/x/tools/go/gcimporter -I $WORK -I /home/ubuntu/coala/.vendor/pkg/linux_amd64 -pack ./exportdata.go ./gcimporter.go
mv $WORK/golang.org/x/tools/go/gcimporter.a /home/ubuntu/coala/.vendor/pkg/linux_amd64/golang.org/x/tools/go/gcimporter.a
mkdir -p $WORK/github.com/golang/lint/_obj/
mkdir -p $WORK/github.com/golang/
cd /home/ubuntu/coala/.vendor/src/github.com/golang/lint
/usr/local/go/pkg/tool/linux_amd64/compile -o $WORK/github.com/golang/lint.a -trimpath $WORK -p github.com/golang/lint -complete -buildid 49aa8071a916fe8c7110983a397c1d09a88b16ce -D _/home/ubuntu/coala/.vendor/src/github.com/golang/lint -I $WORK -I /home/ubuntu/coala/.vendor/pkg/linux_amd64 -pack ./lint.go
mkdir -p /home/ubuntu/coala/.vendor/pkg/linux_amd64/github.com/golang/
mv $WORK/github.com/golang/lint.a /home/ubuntu/coala/.vendor/pkg/linux_amd64/github.com/golang/lint.a
mkdir -p $WORK/github.com/golang/lint/golint/_obj/
mkdir -p $WORK/github.com/golang/lint/golint/_obj/exe/
cd /home/ubuntu/coala/.vendor/src/github.com/golang/lint/golint
/usr/local/go/pkg/tool/linux_amd64/compile -o $WORK/github.com/golang/lint/golint.a -trimpath $WORK -p main -complete -buildid cd3ba076090244dfa4a2defd2b03f7f9a2d31aa7 -D _/home/ubuntu/coala/.vendor/src/github.com/golang/lint/golint -I $WORK -I /home/ubuntu/coala/.vendor/pkg/linux_amd64 -pack ./golint.go ./import.go
cd .
/usr/local/go/pkg/tool/linux_amd64/link -o $WORK/github.com/golang/lint/golint/_obj/exe/a.out -L $WORK -L /home/ubuntu/coala/.vendor/pkg/linux_amd64 -extld=gcc -buildmode=exe -buildid=cd3ba076090244dfa4a2defd2b03f7f9a2d31aa7 $WORK/github.com/golang/lint/golint.a
mkdir -p /home/ubuntu/coala/.vendor/bin/
mv $WORK/github.com/golang/lint/golint/_obj/exe/a.out /home/ubuntu/coala/.vendor/bin/golint
WORK=/tmp/go-build853179844
mkdir -p $WORK/golang.org/x/tools/go/ast/astutil/_obj/
mkdir -p $WORK/golang.org/x/tools/go/ast/
cd /home/ubuntu/coala/.vendor/src/golang.org/x/tools/go/ast/astutil
/usr/local/go/pkg/tool/linux_amd64/compile -o $WORK/golang.org/x/tools/go/ast/astutil.a -trimpath $WORK -p golang.org/x/tools/go/ast/astutil -complete -buildid 7d47cb8f169d22c09f2ce82fb9e3ba505ff3243a -D _/home/ubuntu/coala/.vendor/src/golang.org/x/tools/go/ast/astutil -I $WORK -pack ./enclosing.go ./imports.go ./util.go
mkdir -p /home/ubuntu/coala/.vendor/pkg/linux_amd64/golang.org/x/tools/go/ast/
mv $WORK/golang.org/x/tools/go/ast/astutil.a /home/ubuntu/coala/.vendor/pkg/linux_amd64/golang.org/x/tools/go/ast/astutil.a
mkdir -p $WORK/golang.org/x/tools/imports/_obj/
mkdir -p $WORK/golang.org/x/tools/
cd /home/ubuntu/coala/.vendor/src/golang.org/x/tools/imports
/usr/local/go/pkg/tool/linux_amd64/compile -o $WORK/golang.org/x/tools/imports.a -trimpath $WORK -p golang.org/x/tools/imports -complete -buildid 50fe4cbbd9dd25aab922ff5336aecd00c2202e00 -D _/home/ubuntu/coala/.vendor/src/golang.org/x/tools/imports -I $WORK -I /home/ubuntu/coala/.vendor/pkg/linux_amd64 -pack ./fix.go ./imports.go ./sortimports.go ./zstdlib.go
mkdir -p /home/ubuntu/coala/.vendor/pkg/linux_amd64/golang.org/x/tools/
mv $WORK/golang.org/x/tools/imports.a /home/ubuntu/coala/.vendor/pkg/linux_amd64/golang.org/x/tools/imports.a
mkdir -p $WORK/golang.org/x/tools/cmd/goimports/_obj/
mkdir -p $WORK/golang.org/x/tools/cmd/goimports/_obj/exe/
cd /home/ubuntu/coala/.vendor/src/golang.org/x/tools/cmd/goimports
/usr/local/go/pkg/tool/linux_amd64/compile -o $WORK/golang.org/x/tools/cmd/goimports.a -trimpath $WORK -p main -complete -buildid fbff4bbc917eac7e76b060a86b3ba9d34aa58882 -D _/home/ubuntu/coala/.vendor/src/golang.org/x/tools/cmd/goimports -I $WORK -I /home/ubuntu/coala/.vendor/pkg/linux_amd64 -pack ./doc.go ./goimports.go
cd .
/usr/local/go/pkg/tool/linux_amd64/link -o $WORK/golang.org/x/tools/cmd/goimports/_obj/exe/a.out -L $WORK -L /home/ubuntu/coala/.vendor/pkg/linux_amd64 -extld=gcc -buildmode=exe -buildid=fbff4bbc917eac7e76b060a86b3ba9d34aa58882 $WORK/golang.org/x/tools/cmd/goimports.a
mkdir -p /home/ubuntu/coala/.vendor/bin/
mv $WORK/golang.org/x/tools/cmd/goimports/_obj/exe/a.out /home/ubuntu/coala/.vendor/bin/goimports
WORK=/tmp/go-build288896366
mkdir -p $WORK/sourcegraph.com/sqs/goreturns/returns/_obj/
mkdir -p $WORK/sourcegraph.com/sqs/goreturns/
cd /home/ubuntu/coala/.vendor/src/sourcegraph.com/sqs/goreturns/returns
/usr/local/go/pkg/tool/linux_amd64/compile -o $WORK/sourcegraph.com/sqs/goreturns/returns.a -trimpath $WORK -p sourcegraph.com/sqs/goreturns/returns -complete -buildid 807bf5cdff2a33f141ea487b739dcfffca13c856 -D _/home/ubuntu/coala/.vendor/src/sourcegraph.com/sqs/goreturns/returns -I $WORK -I /home/ubuntu/coala/.vendor/pkg/linux_amd64 -pack ./fix.go ./index.go ./returns.go
mkdir -p /home/ubuntu/coala/.vendor/pkg/linux_amd64/sourcegraph.com/sqs/goreturns/
mv $WORK/sourcegraph.com/sqs/goreturns/returns.a /home/ubuntu/coala/.vendor/pkg/linux_amd64/sourcegraph.com/sqs/goreturns/returns.a
mkdir -p $WORK/sourcegraph.com/sqs/goreturns/_obj/
mkdir -p $WORK/sourcegraph.com/sqs/goreturns/_obj/exe/
cd /home/ubuntu/coala/.vendor/src/sourcegraph.com/sqs/goreturns
/usr/local/go/pkg/tool/linux_amd64/compile -o $WORK/sourcegraph.com/sqs/goreturns.a -trimpath $WORK -p main -complete -buildid dac559b89024f6905b5ca45f0b76b114da4a5c5e -D _/home/ubuntu/coala/.vendor/src/sourcegraph.com/sqs/goreturns -I $WORK -I /home/ubuntu/coala/.vendor/pkg/linux_amd64 -pack ./goreturns.go
cd .
/usr/local/go/pkg/tool/linux_amd64/link -o $WORK/sourcegraph.com/sqs/goreturns/_obj/exe/a.out -L $WORK -L /home/ubuntu/coala/.vendor/pkg/linux_amd64 -extld=gcc -buildmode=exe -buildid=dac559b89024f6905b5ca45f0b76b114da4a5c5e $WORK/sourcegraph.com/sqs/goreturns.a
mkdir -p /home/ubuntu/coala/.vendor/bin/
mv $WORK/sourcegraph.com/sqs/goreturns/_obj/exe/a.out /home/ubuntu/coala/.vendor/bin/goreturns
can't load package: package golang.org/x/net: no buildable Go source files in /home/ubuntu/coala/.vendor/src/golang.org/x/net
=> Done!
```

**Comment by sils1297** [comment]
this commit needs to be repushed to trigger CI, github seems to have issues related to that cyurrently. Either do a rebase if needed or just an amend without changing anything

**Comment by AbdealiJK** [comment]
ack 3b67f1c

**Comment by AbdealiJK** [comment]
Moved to https://github.com/coala-analyzer/coala/pull/1530

**Pull request closed without merging**
