### PR TITLE
Issues in Collectors and Lint

### PR DESCRIPTION
**Pull request by AbdealiJK**

### CODE REVIEW

**Comment by AbdealiJK** [comment]
reack
6222241 ClangAstPrintBear: Convert to GlobalBear
d0d09d9 CheckstyleBear: Find jar in check_prerequisites
d5d29a3 OpenEditorActionTest: Clean up after test
664ab1b coafile: Add LineLengthBear for docs
3912960 CONTRIBUTING.md: Fix minor issues
5ce6c39 coafile: Analyze .rst files instead of .md in docs
bea2be0 docs: Add docs on git pre-commit hook for coala
b53b3f8 *.py: Reorder imports to be alphabetically sorted
082c86f LineDiff: Accept any iterable in add_after()
512326b Lint: Convert all files to tuples
4ca99b2 LocalBearTestHelper: Allow tuple of lines
e641479 Lint: Use run_shell_command() instead of Popen
57de9a6 Lint: Add helper to auto generate configs
38906fb *LintBear.py: Move arguments into list()
bbf117f Lint: Use .format() to insert variables in command
cee0002 Collectors: Move out unused glob warnings
6c8ca9e Collectors: Raise warning when file glob is empty
9c33434 Collectors: Use fnmatch with a list of patterns
e89fc3b Globbing: Allow list of patterns in fnmatch()

**Comment by AbdealiJK** [comment]
reack 6222241 ClangAstPrintBear: Convert to GlobalBear
d0d09d9 CheckstyleBear: Find jar in check_prerequisites
d5d29a3 OpenEditorActionTest: Clean up after test
664ab1b coafile: Add LineLengthBear for docs
3912960 CONTRIBUTING.md: Fix minor issues
5ce6c39 coafile: Analyze .rst files instead of .md in docs
bea2be0 docs: Add docs on git pre-commit hook for coala
b53b3f8 *.py: Reorder imports to be alphabetically sorted
082c86f LineDiff: Accept any iterable in add_after()
512326b Lint: Convert all files to tuples
4ca99b2 LocalBearTestHelper: Allow tuple of lines
e641479 Lint: Use run_shell_command() instead of Popen
57de9a6 Lint: Add helper to auto generate configs
38906fb *LintBear.py: Move arguments into list()
bbf117f Lint: Use .format() to insert variables in command
cee0002 Collectors: Move out unused glob warnings
6c8ca9e Collectors: Raise warning when file glob is empty
9c33434 Collectors: Use fnmatch with a list of patterns
e89fc3b Globbing: Allow list of patterns in fnmatch()

**Comment by sils1297** [comment]
reack 6222241 ClangAstPrintBear: Convert to GlobalBear d0d09d9 CheckstyleBear: Find jar in check_prerequisites d5d29a3 OpenEditorActionTest: Clean up after test 664ab1b coafile: Add LineLengthBear for docs 3912960 CONTRIBUTING.md: Fix minor issues 5ce6c39 coafile: Analyze .rst files instead of .md in docs bea2be0 docs: Add docs on git pre-commit hook for coala b53b3f8 *.py: Reorder imports to be alphabetically sorted 082c86f LineDiff: Accept any iterable in add_after() 512326b Lint: Convert all files to tuples 4ca99b2 LocalBearTestHelper: Allow tuple of lines e641479 Lint: Use run_shell_command() instead of Popen 57de9a6 Lint: Add helper to auto generate configs 38906fb *LintBear.py: Move arguments into list() bbf117f Lint: Use .format() to insert variables in command cee0002 Collectors: Move out unused glob warnings 6c8ca9e Collectors: Raise warning when file glob is empty 9c33434 Collectors: Use fnmatch with a list of patterns e89fc3b Globbing: Allow list of patterns in fnmatch()

**Comment by AbdealiJK** [comment]
@rultor merge

**Pull request merged**
