### PR TITLE
Result: Change seperators -> separators

### PR DESCRIPTION
**Pull request by yash-nisar**
Fixes https://github.com/coala-analyzer/coala/issues/2485

### CODE REVIEW

**Comment by sils1297** [comment]
Fixes -> Closes otherwise you confuse our bug prediction algorithm :)

**Comment by yash-nisar** [comment]
Thanks @sils1297 , I shall make a note of it.

**Comment by sils1297** [comment]
That's the `review carefully` label, we're doing some research with that so we need to know which commits are actually fixing bugs and which are closing issues :)

**Comment by sils1297** [comment]
https://github.com/coala-analyzer/coala/pull/2570/commits/f6abe65eab7bc43150c5f11d4ea3b7bb59e81a92 is ready

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@yash-nisar you have done two newcomer issues and it seems you're well acquainted with the workflow! That's awesome :) We recommend to not do newcomer issues anymore because they take us more time to file than to fix them so other newcomers can have a few as well. Next level is http://tinyurl.com/coala-low - you can now dive into whatever you want. Let us know if you need help or have any special interests - there's a lot of stuff going on and usually interests can be met :)

**Pull request merged**
