### PR TITLE
Git_help.rst: Add a git tutorial page

### PR DESCRIPTION
**Pull request by Adrianzatreanu**
This page should help newcomers to understand git
a little better, and make it easier for them to
get started on their first contribution.

Fixes https://github.com/coala-analyzer/coala/issues/1741

I will edit the newcomers page and guide it to this link once this gets merged :)

### CODE REVIEW

**Comment by tushar-rishav** [comment]
@Adrianzatreanu Awesome! If possible, please add these commands too. :)

- `git rebase master # from <new_branch> . Why use rebase and not merge? `

- ` git  reset HEAD~N ` where N is some number

-  `git reset --hard HEAD@(N) `

-  `git push --force and git pull --ff-only <origin> <master> `

We often encounter people asking for these commands. Adding these would help newcomers. :)

**Comment by AbdealiJK** [comment]
@tushar-rishav Please change the label to "process/wip" after reviewing (if its not acked)

**Comment by Adrianzatreanu** [comment]
hm, writing a git tutorial and having git struggles feels a little embarassing i guess

**Comment by AbdealiJK** [comment]
ack 62523d1

**Comment by Adrianzatreanu** [comment]
reack 62523d1

**Comment by Adrianzatreanu** [comment]
reack aa47ac1

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Pull request merged**
