### PR TITLE
complete glob rework including fnmatch

### PR DESCRIPTION
**Pull request by fneu**
This PR adresses:
 * #396 escaping for globs
 * #460 document what our glob supports
 * #596 need a function similar to fnmatch in glob

### CODE REVIEW

**Comment by Makman2** [comment]
@sils1297 Could you rebuild on appveyor? Again it's too dumb and needs more than 40 minutes for a build...

**Comment by sils1297** [comment]
@Makman2 let's ignore AppVeyor for now.

**Comment by Makman2** [comment]
No we can't ignore appveyor, the tests fail on my local machine:
```
  1/75 | ApplyPatchActionTest
  2/75 | BearRunnerTest
  3/75 | BearTest
  4/75 | ClangASTPrintBearTest, Skipping: [WinError 126] Das angegebene Modul wurde nicht gefunden. To provide a path to libclang use Config
.set_library_path() or Config.set_library_file().
  5/75 | ClangCloneDetectionBearTest, Skipping: No module named 'munkres'
  6/75 | ClangCountingConditionsTest, Skipping: [WinError 126] Das angegebene Modul wurde nicht gefunden. To provide a path to libclang use
Config.set_library_path() or Config.set_library_file().
  7/75 | ClangCountVectorCreatorTest, Skipping: [WinError 126] Das angegebene Modul wurde nicht gefunden. To provide a path to libclang use
Config.set_library_path() or Config.set_library_file().
  8/75 | CliParsingTest
  9/75 | ClosableObjectTest
 10/75 | CollectorsTest
test_bear_empty (__main__.CollectBearsTest) ... ok
test_bear_invalid (__main__.CollectBearsTest) ... ok
test_expression_invalid (__main__.CollectBearsTest) ... ok
test_no_duplications (__main__.CollectBearsTest) ... ok
test_reference_single (__main__.CollectBearsTest) ... ok
test_simple_single (__main__.CollectBearsTest) ... ok
test_wrong_kind (__main__.CollectBearsTest) ... ok
test_dir_collection (__main__.CollectDirsTest) ... FAIL
test_dir_empty (__main__.CollectDirsTest) ... ok
test_dir_invalid (__main__.CollectDirsTest) ... ok
test_expression_invalid (__main__.CollectDirsTest) ... ok
test_expression_invalid (__main__.CollectFilesTest) ... ok
test_file_collection (__main__.CollectFilesTest) ... FAIL
test_file_empty (__main__.CollectFilesTest) ... ok
test_file_invalid (__main__.CollectFilesTest) ... ok

======================================================================
FAIL: test_dir_collection (__main__.CollectDirsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Users\MAK\Eigene Dokumente\GitHub\coala\coalib\tests\collecting\CollectorsTest.py", line 75, in test_dir_collection
    self.collectors_test_dir+os.sep]))
AssertionError: Lists differ: ['d:\\users\\mak\\eigene dokumente\\github\[618 chars]les'] != ['D:\\Users\\MAK\\Eigene Dokumente\\GitHub\[618
 chars]les']

First differing element 0:
d:\users\mak\eigene dokumente\github\coala\coalib\tests\collecting\collectors_test_dir\
D:\Users\MAK\Eigene Dokumente\GitHub\coala\coalib\tests\collecting\collectors_test_dir\

Diff is 1968 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_file_collection (__main__.CollectFilesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Users\MAK\Eigene Dokumente\GitHub\coala\coalib\tests\collecting\CollectorsTest.py", line 41, in test_file_collection
    "file2.py")])
AssertionError: Lists differ: ['d:\\users\\mak\\eigene dokumente\\github\[79 chars].py'] != ['D:\\Users\\MAK\\Eigene Dokumente\\GitHub\[79 c
hars].py']

First differing element 0:
d:\users\mak\eigene dokumente\github\coala\coalib\tests\collecting\collectors_test_dir\others\py_files\file2.py
D:\Users\MAK\Eigene Dokumente\GitHub\coala\coalib\tests\collecting\collectors_test_dir\others\py_files\file2.py

- ['d:\\users\\mak\\eigene '
?   ^   ^      ^^^  ^

+ ['D:\\Users\\MAK\\Eigene '
?   ^   ^      ^^^  ^

-  'dokumente\\github\\coala\\coalib\\tests\\collecting\\collectors_test_dir\\others\\py_files\\file2.py']
?   ^          ^  ^

+  'Dokumente\\GitHub\\coala\\coalib\\tests\\collecting\\collectors_test_dir\\others\\py_files\\file2.py']
?   ^          ^  ^


----------------------------------------------------------------------
Ran 15 tests in 0.078s

FAILED (failures=2)
←[0;33m[WARNING][19:24:38] ←[0mUnable to collect bears from d:\users\mak\eigene dokumente\github\coala\coalib\tests\collecting\collectors_te
st_dir\bears\incorrect_bear.py. Probably the file is malformed or the module code raises an exception.
←[0;33m[WARNING][19:24:38] ←[0mUnable to collect bears from d:\users\mak\eigene dokumente\github\coala\coalib\tests\collecting\collectors_te
st_dir\bears\incorrect_bear.py. Probably the file is malformed or the module code raises an exception.
######################################################################
 11/75 | ColoredLogPrinterTest
 12/75 | ColorPrinterTest
 13/75 | ConfigurationGatheringTest
test_back_saving (__main__.ConfigurationGatheringTest) ... ok
test_default_coafile_parsing (__main__.ConfigurationGatheringTest) ... ok
test_find_user_config (__main__.ConfigurationGatheringTest) ... ok
test_gather_configuration (__main__.ConfigurationGatheringTest) ... FAIL
test_logging (__main__.ConfigurationGatheringTest) ... ok
test_logging_objects (__main__.ConfigurationGatheringTest) ... ok
test_merge (__main__.ConfigurationGatheringTest) ... ok
test_merge_defaults (__main__.ConfigurationGatheringTest) ... ok
test_nonexistent_file (__main__.ConfigurationGatheringTest) ... ok
test_outputting (__main__.ConfigurationGatheringTest) ... ok
test_targets (__main__.ConfigurationGatheringTest) ... ok
test_user_coafile_parsing (__main__.ConfigurationGatheringTest) ... ok

======================================================================
FAIL: test_gather_configuration (__main__.ConfigurationGatheringTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Users\MAK\Eigene Dokumente\GitHub\coala\coalib\tests\settings\ConfigurationGatheringTest.py", line 46, in test_gather_configurati
on
    self.assertEqual(len(local_bears["default"]), 1)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 12 tests in 0.766s

FAILED (failures=1)
←[0;33m[WARNING][19:24:39] ←[0mThe requested coafile 'D:\Users\MAK\Eigene Dokumente\GitHub\coala\some_bad_filename' does not exist. Thus it
will not be used.
←[0;33m[WARNING][19:24:39] ←[0mThe requested coafile 'D:\Users\MAK\Eigene Dokumente\GitHub\coala\some_bad_filename' does not exist. Thus it
will not be used.
←[0;33m[WARNING][19:24:39] ←[0mThe requested coafile 'D:\Users\MAK\Eigene Dokumente\GitHub\coala\bad_filename' does not exist. Thus it will
not be used.
←[0;33m[WARNING][19:24:39] ←[0mFailed to instantiate the logging method './invalid path/@#$%^&*()_'. Falling back to console output.
FilePrinter needs to be closed manually.
←[0;33m[WARNING][19:24:39] ←[0mFailed to instantiate the logging method './invalid path/@#$%^&*()_'. Falling back to console output.
FilePrinter needs to be closed manually.
←[0;33m[WARNING][19:24:39] ←[0mThe requested coafile 'D:\Users\MAK\Eigene Dokumente\GitHub\coala\bad_file_name' does not exist. Thus it will
 not be used.
←[0;33m[WARNING][19:24:39] ←[0mThe requested coafile 'D:\Users\MAK\Eigene Dokumente\GitHub\coala\bad.one\test
even with bad chars in it' does not exist. Thus it will not be used.
←[0;33m[WARNING][19:24:39] ←[0mThe requested coafile 'D:\Users\MAK\Eigene Dokumente\GitHub\coala\bad.one\test
even with bad chars in it' does not exist. Thus it will not be used.
←[0;33m[WARNING][19:24:39] ←[0mThe requested section 'test1' is not existent. Thus it cannot be executed.
←[0;33m[WARNING][19:24:39] ←[0mThe requested section 'test2' is not existent. Thus it cannot be executed.
######################################################################
 14/75 | ConfParserTest
 15/75 | ConfWriterTest
 16/75 | ConsoleInteractorTest
 17/75 | ConsolePrinterTest
 18/75 | ContextManagersTest
 19/75 | CountVectorTest
 20/75 | DbusAppTest, Skipping: No module named 'dbus'
 21/75 | DbusDocumentTest, Skipping: No module named 'dbus'
 22/75 | DbusServerTest, Skipping: No module named 'dbus'
 23/75 | DecoratorsTest
 24/75 | DependenciesTest
 25/75 | DictUtilitiesTest
 26/75 | DiffTest
 27/75 | DocumentationCommentTest, Skipping: msgfmt is not installed.
 28/75 | EnumTest
 29/75 | EspeakPrinterTest, Skipping: eSpeak is not installed.
 30/75 | FilePrinterTest
 31/75 | FunctionMetadataTest
 32/75 | GlobalBearTest
 33/75 | GlobbingTest
[ENDLESS LOOP]
```

**Comment by fneu** [comment]
@Makman2 @sils1297 The "endless loop" has not been an endless loop at all. `run_test()` stopped at an earlier test when it was being run in the debugger, an both test were doing fine when bring run separately (although they failed of course).

that is a little disturbing.

**Comment by fneu** [comment]
There was indeed a fix missing I implemented earlier. I have no idea where it went, everything else was fine. It works for me on both systems now.

**Comment by sils1297** [comment]
@fneu you workin' here?

**Comment by fneu** [comment]
Yes, please no review anymore today ;)



Am 23. Juni 2015 9:52:17 nachm. schrieb Lasse Schuirmann 
<notifications@github.com>:

**Comment by fneu** [comment]
superseded by #682

**Pull request closed without merging**
