### PR TITLE
Wip/sils/bearrunner v2

### PR DESCRIPTION
**Pull request by sils1297**
Misc bugfixes, revision 2

### CODE REVIEW

**Comment by sils1297** [comment]
rebased on wip/codestyle since this is almost merged

**Comment by Makman2** [comment]
When running coala with this pull request it reports me following:
```
|    .    | 
|    .    | 
|    .    | 
|  32|  32|         if not isinstance(file_diff_dict, dict):
|  33|  33|             raise TypeError("file_diff_dict has to be of type dict.")
|  34|  34| 
|  35|  35|         return self.apply(result, original_file_dict, file_diff_dict, **self.get_metadata().create_params_from_section(section))
|    |    | [NORMAL] LineLengthBear:
|    |    | Line is longer than allowed. (129 > 120)
|    |    | The following options are applicable to this result (choose 0 for no action):
|    |    |  1: Open the file in an editor.
|    |    | Please enter the number of the action you want to execute. 0
```

**Comment by Makman2** [comment]
Especially: what mean the dots in the columns?
`|   .   |`

**Comment by sils1297** [comment]
File a bug about the dots. They're meant as kind of "here's some code but we don't show you more than a few lines"

**Comment by Makman2** [comment]
Then `...` in the line above is better or some other string. I'll open bug.

**Comment by sils1297** [comment]
I don't get any results when running coala on this branch.
```
git checkout origin/wip/sils/bearrunner_v2
sudo ./setup.py install
coala
```
yields only:
```
Executing section PythonCheck...
```

Could you place the command and whole output on pastebing?

**Comment by Makman2** [comment]
It's in the file *build/lib/coalib/results/result_actions/ResultAction.py*.
I just `cd`'ed into the coala directory and ran `./coala`.

**Comment by sils1297** [comment]
Thats a bug in our coafile I forget to file every time: files in the build directory are used for installation, thats probably an old file. Filed #297.

**Comment by Makman2** [comment]
Ah okay that was generated from the old installation that I tried to install...
Never mind :x

**Comment by sils1297** [comment]
care for reviewing the commits now?

2015-02-18 16:49 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
Tomorrow... that's quite much internal stuff...

**Comment by sils1297** [comment]
v3 is #301

**Pull request closed without merging**
