### PR TITLE
CountVector: Implement appropriate __repr__

### LINKED ISSUE #781: Implement nice __repr__()
The current `__repr__()` functions often use `__str__()`, which just contains data but no identification of the object (what `repr()` is supposed to return). Keeping track with python, I would suggest following naming scheme:
```
<ClassName object(member1: value1, member2: value2, maybe additional information) at 0xAAAAAA>
```

@coala-analyzer/coala-contributors opinions?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/24347673-implement-nice-__repr__?utm_campaign=plugin&utm_content=tracker%2F2228228&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F2228228&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Makman2**
Fixes #781.

### CODE REVIEW

**Comment by Makman2** [comment]
yeah no problem
if you have reviewed, could you mark it as "approved for master"?

**Comment by Makman2** [comment]
hm okay needs rebase, nvm

**Comment by Makman2** [comment]
Changed for using instance class name:
`CountVector.__name__` --> `self.__class__.__name__`

**Comment by Makman2** [comment]
This is also blocked by #857 which introduces the new repr decorator.

**Comment by sils1297** [comment]
@Makman2 this is not blocked anymre

**Comment by sils1297** [comment]
...from my side.

**Comment by Makman2** [comment]
#878 takes over with an improved version using `@generate_repr` decorator.

**Pull request closed without merging**
