### PR TITLE
Docs: Lots of changes

### PR DESCRIPTION
**Pull request by AbdealiJK**

### CODE REVIEW

**Comment by AbdealiJK** [comment]
reack
c3196d1 circle: Use sphinx-apidoc and without warnings
b1f0d69 *: Modify docs to use RST and compile w/o warnings
00383de setup: Make apidocs for coalib
ba52a18 README: Mention coala-bears repo
a02cff8 Install.rst: Mention `pip setup.py docs`
b6de349 Install.rst: Mention the npm package.json
7499723 coafile: Ignore docs/API
777aab5 Install.rst: Use coala-bears instead of coala
cef2075 Install.rst: Move note to correct location
543b852 docs: Use pip3 instead of pip everywhere

b18142b index.rst: Reorder Getting Involved toctree
b19761c Writing_Bears.rst: Fix CommunicationBear
37de751 Tutorial.rst: Change expected output of spaces
4cc82b3 docs/conf.py: Remove non-existent static folder
b52b907 index: Add Self_Correcting_Bears to toctree
c73ec99 Writing_Good_Commits: Reorder sections

**Comment by AbdealiJK** [comment]
reack
c3196d1 circle: Use sphinx-apidoc and without warnings
b1f0d69 *: Modify docs to use RST and compile w/o warnings
00383de setup: Make apidocs for coalib
ba52a18 README: Mention coala-bears repo
a02cff8 Install.rst: Mention pip setup.py docs
b6de349 Install.rst: Mention the npm package.json
7499723 coafile: Ignore docs/API
777aab5 Install.rst: Use coala-bears instead of coala
cef2075 Install.rst: Move note to correct location
543b852 docs: Use pip3 instead of pip everywhere

b18142b index.rst: Reorder Getting Involved toctree
b19761c Writing_Bears.rst: Fix CommunicationBear
37de751 Tutorial.rst: Change expected output of spaces
4cc82b3 docs/conf.py: Remove non-existent static folder
b52b907 index: Add Self_Correcting_Bears to toctree
c73ec99 Writing_Good_Commits: Reorder sections

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
