### PR TITLE
Reimplemented SectionManager

### PR DESCRIPTION
**Pull request by Udayan12167**

### CODE REVIEW

**Comment by Udayan12167** [comment]
So i fixed the minor problems.

**Comment by sils1297** [comment]
the code changes of the last two commits look good. However I'm not sure if the tests suffice to prove that the code is right.

A little testing lesson :) I suppose you know of statement and branch coverage. I suppose you optimized statement coverage to 100%, at least travis confirms that. Thats good but actually only a first step. So besides the coverage it's important to test corner cases. Meaning, you try to find input values for which your implementation does **not** work. So you're actively trying to break your code. This is especially important here because all this merging and defaults and several files is a bit error prone and we had bugs with this before.

In order to do this I'd e.g. *at least* add some other sections to the default_coafile test file and also some others to your .coafile so you get all combinations of None/not None merging and so on.

**Comment by sils1297** [comment]
Basically at coala we aim that if the code passes the tests it should not be possible that the code is wrong. (Makes refactoring very easy :))

**Comment by Udayan12167** [comment]
Test cases added please review :)

**Comment by sils1297** [comment]
I pushed the first two commits on master since they're ready and valid on their own.

**Comment by sils1297** [comment]
Please look at those spacig issues:
https://scrutinizer-ci.com/g/coala-analyzer/coala/inspections/6b4d4c61-a8d8-4ae5-a1df-4b1987e3ba90/issues/files/coalib/tests/settings/SectionManagerTest.py?status=new&orderField=path&order=asc

**Comment by Udayan12167** [comment]
Fixed the spacing issues. Added test cases as required.

**Comment by sils1297** [comment]
please rebase onto current master and fix the spacing issues in an own commit. General rule: when something is published one *never* changes it. (The history I mean.)

**Comment by Udayan12167** [comment]
Rebased off current master and fixed spacing issue and converted that method into static.

**Comment by sils1297** [comment]
merged

**Pull request closed without merging**
