### PR TITLE
Git_Help.rst: Clarify rejection of PRs

### PR DESCRIPTION
**Pull request by Makman2**

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
ack 5cde42209f3f3ce9a138f7c742dcb6c6c46a5d71

**Comment by Adrianzatreanu** [comment]
also rebase needed :)

**Comment by Adrianzatreanu** [comment]
ack 503369a9e8953326530f764ec32f3130cf2c6b1e

**Comment by sils1297** [comment]
still rebase needed, lots of stuff was going on I presume

**Comment by sils1297** [comment]
@Makman2 did the rebase for you and added another commit from https://github.com/coala-analyzer/coala/pull/2620

**Comment by sils1297** [comment]
ack
3f4d179 Diff: Implement function delete_lines
16c4f40 Tutorial.rst: Add missing word
1881729 Git_Help.rst: Clarify rejection of PRs

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
