### PR TITLE
Add output to coala-ci(WIP)

### PR DESCRIPTION
**Pull request by abhsag24**
Fixes https://github.com/coala-analyzer/coala/issues/1256

### CODE REVIEW

**Comment by sils1297** [comment]
@abhsag24 need help here?

**Comment by abhsag24** [comment]
@sils1297 would love it! otherwise i'll either have to change my implementation or change a lot of old code! :P

**Comment by sils1297** [comment]
@abhsag24 actually your travis build will be fixed by a simple rebase

**Comment by abhsag24** [comment]
have to add some more tests :)

**Comment by sils1297** [comment]
unack  5a7c5bf

**Comment by sils1297** [comment]
ack a609f94

**Comment by sils1297** [comment]
ack bebf30e

**Comment by sils1297** [comment]
ack 891ca8d b93732d 375e2a5

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
