### PR TITLE
Annotation: Fix typo

### PR DESCRIPTION
**Pull request by sotw1957**
Fixed the wether to whether.

### CODE REVIEW

**Comment by tushar-rishav** [comment]
@sotw1957  Commit msg could be better. It'd be nice if you provide the issue number that your PR if merged, would get fixed. 
`Fixes: Issue_Url`

**Comment by tushar-rishav** [comment]
unack 5427d8b

**Comment by AbdealiJK** [comment]
Hey there,

The git commit message you've used is not in accordance with the coala git commit guidelines.
Can you check out the [commit style documentation](http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html) and ensure you follow the guidelines mentioned there ?

The "fixes" part is the third part of the commit message. There should be a shortlog and a body before that :)

**Comment by AbdealiJK** [comment]
unack f308af9

**Comment by tushar-rishav** [comment]
Moreover, the link that Fixes refers to is wrong. It should refer to the actual issue this PR is solving and not to the PR itself

**Comment by sotw1957** [comment]
i'm on it

**Comment by SanketDG** [comment]
@sotw1957 Can you change your commit message to

```
ApplyPatchAction: Fix typo
```
or better:
```
ApplyPatchAction: Wether -> Whether
```

Everything else looks okay.

**Comment by SanketDG** [comment]
unack 6c0a15e

**Comment by SanketDG** [comment]
@sotw1957 what I meant was the title of the commit:

change
```
Annotation: Fix typo
```
to
```
ApplyPatchAction: Fix typo
```

**Comment by abhsag24** [comment]
ack 7ec34ca :)

**Comment by SanketDG** [comment]
ack 7ec34ca

**Comment by SanketDG** [comment]
@sotw1957 nice!

**Comment by sotw1957** [comment]
Thank you! I learned a lot! :dancer:

**Comment by sils1297** [comment]
see https://github.com/coala-analyzer/coala/pull/1989

**Pull request closed without merging**
