### PR TITLE
Codestyle: not a is None -> a is not None 

### PR DESCRIPTION
**Pull request by charizard42**
change `not a is None` with `a is not None`

Fixes https://github.com/coala-analyzer/coala/issues/1494

### CODE REVIEW

**Comment by tushar-rishav** [comment]
@charizard42 Hey, you might wanna update the commit message. :D Normally it goes like `tag: Short description`, first letter of short description being capital. :) Beside, you need to rebase too.

**Comment by charizard42** [comment]
i did Edit:tagging.py

**Comment by Makman2** [comment]
@charizard42 @tushar-rishav is right, the tag normally is the file where you do changes without the ending. So a valid message would be for example `Tagging: not a is None -> a is not None`
**But:**
I've found also an occurrence inside `coalib/settings/ConfigurationGathering.py` -> `if not autoapply is None:`, this needs to be changed too to completely solve the adressed issue.

**Comment by Makman2** [comment]
Then you could change the tag to `codestyle` maybe, since the fixes affect more than one module^^

**Comment by charizard42** [comment]
@Makman2  how did you search that all across directory?

**Comment by sils1297** [comment]
https://www.kernel.org/pub/software/scm/git/docs/git-grep.html

**Comment by AbdealiJK** [comment]
ack f125fea

**Comment by AbdealiJK** [comment]
You need to rebase

**Comment by sils1297** [comment]
triggered circleci reuild

**Comment by AbdealiJK** [comment]
reack 3fb8bc4

**Comment by AbdealiJK** [comment]
@rultor merge

**Comment by AbdealiJK** [comment]
@charizard42 awesome ! your first commit got merged :)
Why don't you try a difficulty/low or difficulty/medium issue now ?

**Comment by charizard42** [comment]
@AbdealiJK  sure

**Pull request merged**
