### PR TITLE
Merge pull request #1 from coala-analyzer/master

### PR DESCRIPTION
**Pull request by charizard42**
space added

### CODE REVIEW

**Comment by sils1297** [comment]
Hey, that commit is unreviewable. It doesn't follow our commit message guidelines http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages and it's a huge merge commit, please do a *rebase* like described on https://github.com/coala-analyzer/coala/wiki/Getting-Started-to-Contribute and do a commit that contains *only your change*.

**Comment by sils1297** [comment]
unack 42240da

**Comment by AbdealiJK** [comment]
Plus, could you please continue working on the old branch ?
Closing in favour of https://github.com/coala-analyzer/coala/pull/1631

**Comment by charizard42** [comment]
ok

**Pull request closed without merging**
