### PR TITLE
Install.md: Add documentation generation section

### PR DESCRIPTION
**Pull request by sudheesh001**
Add a new file for fetching pip requirements as test-requirements
Updates documentation telling contributors how to generate docs.

Fixes https://github.com/coala-analyzer/coala/issues/1277

### CODE REVIEW

**Comment by sils1297** [comment]
unack 982346

**Comment by sudheesh001** [comment]
@sils1297 Should be the final one :smile:

**Comment by sils1297** [comment]
@sudheesh001 now you're challenging me... you know that your commit message could be improved, huh? You don't really update that documentation generation paragraph but create it. That's misleading ;)

**Comment by sudheesh001** [comment]
Ah I see the point there, Lots of learning , Thanks @sils1297 Amends coming up

**Comment by sils1297** [comment]
ack ef4ab15314b

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
