### PR TITLE
setup.py: Remove '[]' from maintainer name in setup.py

### PR DESCRIPTION
**Pull request by arush0311**
Fixes https://github.com/coala-analyzer/coala/issues/1574

### CODE REVIEW

**Comment by Redridge** [comment]
Hello there @arush0311 
Everything seems fine except the commit message (a little bit).

We usually write before the ":" the file name
So you could change the commit message to read
"setup.py: Remove '[]' from maintainer name"

The easiest way to do this is this
```
git commit --amend
git push origin <branchname>
```
without changing anything.

More on commit messages http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html

The rest is fine :D

**Comment by arush0311** [comment]
Should I submit the PR again?

**Comment by sils1297** [comment]
just amend it
https://github.com/coala-analyzer/coala/wiki/Getting-Started-to-Contribute

2016-02-19 22:18 GMT+01:00 Arush Goyal <notifications@github.com>:

**Comment by arush0311** [comment]
Done.

**Comment by iamshubh22** [comment]
Hey @arush0311. Your short log i.e, first line of your commit message is greater than allowed which is 50 chars. Change your commit message `Fix: Remove '[]' from maintainer name in setup.py"` to `setup.py: Remove '[]' from maintainer name`. Just do `git commit --amend` to amend your previous commit message.
Refer to [https://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html](url) for more details. :smile:

**Comment by Makman2** [comment]
ack e0b13d7

**Comment by Makman2** [comment]
@rultor merge

**Pull request merged**
