### PR TITLE
Move test dir to root level

### PR DESCRIPTION
**Pull request by CruiseDevice**

### CODE REVIEW

**Comment by sils1297** [comment]
@CruiseDevice you know what to do? (On https://github.com/coala-analyzer/coala/wiki/Getting-Started-to-Contribute you'll find some help, or on gitter of course)

**Comment by sils1297** [comment]
WIP as per :point_up: [February 22, 2016 5:00 PM](https://gitter.im/coala-analyzer/coala?at=56cb30a902651b4625376fa0)

**Comment by sils1297** [comment]
please ask us on gitter if you need help

**Comment by Adrianzatreanu** [comment]
Closed due to huge inactivity and the issue is closed already. https://github.com/coala-analyzer/coala/issues/1640

**Comment by AbdealiJK** [comment]
@Adrianzatreanu just a note that that wasnt the issue that was being addressed in this PR (Thats some relic from a bad rebase)
Although this PR can be closed because the corresponding fork/branch doesnt exist anymore ...

https://github.com/coala-analyzer/coala/issues/1636 is what this PR was made for.

**Pull request closed without merging**
