### PR TITLE
Improve grammar in docs of users/writing bears

### LINKED ISSUE #1484: Fix grammatic mistake in the Writing Bears docs
Under the "What is a bear?" Section.
The source code will provided by coala -> The source code will be provided by coala

difficulty/newcomer

### PR DESCRIPTION
**Pull request by ankitaggarwal011**
Improve the grammar in docs of users/Writing_Bears.

Fixes #1484.

### CODE REVIEW

**Comment by AbdealiJK** [comment]
@ankitaggarwal011 Please read http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html .
You need to mention the filaname you're editing and add the `Fixes` keyword

**Comment by AbdealiJK** [comment]
unack 2066acd

**Comment by ankitaggarwal011** [comment]
@AbdealiJK, apologies. I have amended the commit. Thanks.

**Comment by AbdealiJK** [comment]
ack

**Comment by sils1297** [comment]
@AbdealiJK please invite him to coala-reviewers at https://github.com/orgs/coala-analyzer/teams/coala-reviewers

**Comment by AbdealiJK** [comment]
ack cd4ba5a

**Comment by AbdealiJK** [comment]
@sils1297 it says "Only owners can send invitations" I can only add him to the team if he is already in the org

**Comment by sils1297** [comment]
that's sad I promoted you to "team maintainer" and hoped it'd give you
permissions to do that. Github's stupid...

2016-02-15 11:48 GMT+01:00 AbdealiJK <notifications@github.com>:

**Comment by AbdealiJK** [comment]
@ankitaggarwal011 @sils1297 has sent you an invitation to join the coala organization. Could you accept that  then we can assign you to the bug youre working on and push it into master

**Comment by ankitaggarwal011** [comment]
@AbdealiJK @silk1213 Done. Thanks!

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@ankitaggarwal011 cool! Your first commit, huh? Congrats! It already got released at https://pypi.python.org/pypi/coala/0.4.1.dev20160215111353

**Comment by ankitaggarwal011** [comment]
@sils1297, yeah! Cool. A lot of automation, impressive work-flow. Great work!

**Pull request merged**
