### PR TITLE
Docs: Highlight `Pull Request` in Newcomer document

### LINKED ISSUE #1783: Double backticks missing
I think that in our Newcomers document page, the ``Pull Request`` syntax should be more important . We should caption it using double backticks, so it gets shown as code. Prefferably, this should be done all over the document.

### PR DESCRIPTION
**Pull request by justuswilhelm**
Add double backticks to make Pull Request more visible. I've also taken the
liberty of replacing mentions of `PR` with `Pull Request`.
Fixes #1783

### CODE REVIEW

**Comment by abhsag24** [comment]
@justuswilhelm so we have a limit of 50 chars in the shortlog of the commit and 73 in the body(its too long as gitmate has pointed out)  ;) , also just to be sure do you use the full link after the Fixes?

**Comment by justuswilhelm** [comment]
I hope that is already the case with the latest commit f097118

**Comment by abhsag24** [comment]
ohh yeah sorry although we do require you to update the branch via a manual rebase, even if it doesn't have merge conflicts :P

**Comment by sils1297** [comment]
@justuswilhelm so this needs a rebase, I'm not fully bought on codifying every `pull request` mention... doesn't mean it's bad, I just have no idea :P

**Comment by justuswilhelm** [comment]
OK. Hope I've done the right rebase now. :sweat_smile:
@sils1297 tbh, I took the issue very literally and backticked the hell out of this beast. Suggestions are welcome though, if you have concerns.

**Comment by sils1297** [comment]
github still shows `This branch is out-of-date with the base branch` so you haven't rebased it, guess you want to fetch from the original repo and rebase on that

**Comment by sils1297** [comment]
alright I'd take this as it is, I don't know what's better but people seem to find it better so it's probably better :)

**Comment by justuswilhelm** [comment]
My bad, I've rebased from the wrong remote. Thank you for your patience :P

**Comment by sils1297** [comment]
https://github.com/coala-analyzer/coala/pull/1960/commits/6ec241f74746e61a9c6a57fae0195266fdac0783 is ready

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
