### PR TITLE
Update ClangCloneDetectionBear.py status message

### PR DESCRIPTION
**Pull request by NalinG**
Fixes https://github.com/coala-analyzer/coala/issues/906

### CODE REVIEW

**Comment by sils1297** [comment]
unack 73a0f0a, needs work

**Comment by NalinG** [comment]
Really sorry but what do you mean by unack the pull request.

**Comment by sils1297** [comment]
@NalinG does it sound that scary? unack just makes GitMate aware that this commit needs some additional work before it can be merged. It's the normal procedure.

**Comment by AbdealiJK** [comment]
@NalinG we normally "acknowledge" (ack) a change and "unack" it if the change isnt acceptable to be merged into coala

**Comment by sils1297** [comment]
isn't acceptable *yet*

2016-02-10 12:40 GMT+01:00 AbdealiJK <notifications@github.com>:

**Comment by sils1297** [comment]
Hey, I think your commit message is too long, also you do need a rebase onto current master, there was an important change to the test framework. (Do not do a merge, a rebase. :) We can help you with that on gitter if needed.)

**Comment by sils1297** [comment]
otherwise it looks way better than in the beginning, we're getting to it

**Comment by AbdealiJK** [comment]
reack

**Comment by AbdealiJK** [comment]
reack 4b3acbe

**Comment by AbdealiJK** [comment]
@rultor merge

**Pull request merged**
