### PR TITLE
Revert: bash escaping changes

### PR DESCRIPTION
**Pull request by AbdealiJK**

### CODE REVIEW

**Comment by AbdealiJK** [comment]
reverts https://github.com/coala-analyzer/coala/pull/1609

**Comment by sils1297** [comment]
ack  	Revert "Shell.get_shell_type(): Repair" … 	
2d74381
	@AbdealiJK 	Revert "Shell: No split when shell=True" … 	
34d776e
	@AbdealiJK 	Revert "run_shell_command: Remove forbidden param" … 	
1970c4c
	@AbdealiJK 	Revert "Shell: Remove `shell=True`" … 	
e33960c

**Comment by sils1297** [comment]
ack
2d74381
34d776e
1970c4c
e33960c

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
