### PR TITLE
Result:Show filename when autoapplying.

### PR DESCRIPTION
**Pull request by abhsag24**
Fixes https://github.com/coala-analyzer/coala/issues/1188

### CODE REVIEW

**Comment by GitCop** [comment]
The commit message

 * Commit: 342ab5f72879ffbba1b257a5fcecf31fdd73b11b
  * Commits must be in the following format: **%{scope}: %{description}**

Guidelines are available at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages

---
This message was auto-generated by https://gitcop.com

**Comment by abhsag24** [comment]
ok, on it :)

**Comment by sils1297** [comment]
@abhsag24 done with a short review, small things to do but code is almost ready. Nice :)

**Comment by sils1297** [comment]
also this needs a rebase

**Comment by sils1297** [comment]
@abhsag24 hey, can you please address GitMate comments on your own in the future? They always need to be addressed :)

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
