### PR TITLE
LICENSE: remove boilerplate stuff

### PR DESCRIPTION
**Pull request by hypothesist**

### CODE REVIEW

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2394/commits/4d7dd596aa7e3bb7112d1269a91cde1875cef44c

**Comment by hypothesist** [comment]
reack https://github.com/coala-analyzer/coala/pull/2394/commits/2d7ee93d4b8693b2a37c927813aba643d0ffdc6b

**Comment by hypothesist** [comment]
reack https://github.com/coala-analyzer/coala/pull/2394/commits/2d7ee93d4b8693b2a37c927813aba643d0ffdc6b

**Comment by hypothesist** [comment]
@rultor merge

**Comment by ricordisamoa** [comment]
The instructions are integral parts and may not be omitted.
https://www.gnu.org/licenses/gpl-faq.en.html#GPLOmitPreamble

**Comment by sils** [comment]
@ricordisamoa thanks a lot

@adtac can you revert the commit?

**Comment by adtac** [comment]
@ricordisamoa @sils But that's not the preamble. [The preamble starts on Line 8](https://github.com/coala/coala/blob/2d7ee93d4b8693b2a37c927813aba643d0ffdc6b/LICENSE#L8). The stuff that's removed is after an explicit `End of Terms and Conditions`.

**Comment by ricordisamoa** [comment]
> Can I omit the preamble of the GPL, or the instructions for how to use it on your own programs, to save space? (#GPLOmitPreamble)
> The preamble and instructions are integral parts of the GNU GPL and may not be omitted. In fact, the GPL is copyrighted, and its license permits only verbatim copying of the entire GPL. (You can use the legal terms to make another license but it won't be the GNU GPL.)

**Comment by adtac** [comment]
Ah alright, the part about the "instructions for how to use it on your own programs" skipped my mind. I'll revert the commit right away. Thanks!

**Comment by adtac** [comment]
@ricordisamoa Please see https://github.com/coala/coala/pull/3627 and thanks again!

**Comment by ricordisamoa** [comment]
@adtac @sils Thank you

**Comment by sils** [comment]
@ricordisamoa thank you! We would have never found that I guess

**Pull request merged**
