### PR TITLE
index.rst: Change braches to branches

### PR DESCRIPTION
**Pull request by emperorofmars**
Fixes https://github.com/coala-analyzer/coala/issues/1930

### CODE REVIEW

**Comment by AbdealiJK** [comment]
Type in shortlog "Braches"

**Comment by sils1297** [comment]
Hi,

it looks like your PR is out of date and needs a rebase. [This page](http://coala.readthedocs.org/en/latest/Users/Tutorials/Git_Help.html) may help you to get started on this. (*Do not press the update branch button. It's evil.*)

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

Ping us on [our gitter channel](https://gitter.im/coala-analyzer/coala) if you need help!

**Comment by sils1297** [comment]
oh wrong PR, this doesn't need rebase

**Comment by Adrianzatreanu** [comment]
this looks good to me

**Comment by Adrianzatreanu** [comment]
ack fc75d0d

**Comment by sils1297** [comment]
@emperorofmars now you can try the rebase :)

**Comment by Uran198** [comment]
Thanks, merged in https://github.com/coala-analyzer/coala/commit/7dc448dc5cfff314f0a3e0bc7b4e5b00a02c6bc7

**Pull request closed without merging**
