### PR TITLE
rultor

### PR DESCRIPTION
**Pull request by AbdealiJK**

### CODE REVIEW

**Comment by sils1297** [comment]
although the `fixes` is missing...

**Comment by AbdealiJK** [comment]
I realized it after i pushed, and didnt want to wait for CI to finish twice :)

**Comment by sils1297** [comment]
know that feeling. It's ok.

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
Fixes #805

**Comment by sils1297** [comment]
@rultor merge

**Comment by AbdealiJK** [comment]
blocked by https://github.com/coala-analyzer/coala/issues/813

**Comment by AbdealiJK** [comment]
I tested each of these in https://github.com/AbdealiJK/coala/pull/9
I did not test using `zanata-cli` because the current image doesnt install it correctly. There is a PR for that - https://github.com/coala-analyzer/rultor-python/pull/2

**Comment by AbdealiJK** [comment]
Also, the current code always checks if something is installed before installing it.

So, even if we use other docker images, it will install things it needs.

**Comment by AbdealiJK** [comment]
Log of the whole PR working - https://github.com/AbdealiJK/coala/pull/10

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
