### PR TITLE
circle: Build with Python 3.5 stable

### PR DESCRIPTION
**Pull request by sils1297**

### CODE REVIEW

**Comment by Makman2** [comment]
can you retrigger travis? seems again a download error occurred^^

**Comment by Makman2** [comment]
@rultor merge

**Comment by sils1297** [comment]
@Makman2 I didn't reack that commit,. in fact I changed it.

**Comment by Makman2** [comment]
sorry fast forward approved was still there :O

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
