### PR TITLE
LocalBear : fix typo

### PR DESCRIPTION
**Pull request by ManjiriBirajdar**
closed https://github.com/coala-analyzer/coala/issues/2481

### CODE REVIEW

**Comment by Asnelchristian** [comment]
Hi,

it seems that your commit message doesn't contain enough information. Don't worry, most people don't know about good commit messages when they join us, including very experienced developers :) Standards vary from project to project.

The most important part is the first line of your commit message - maintainers will use it to read through a large number of commits and thus it's important that it's short but most importantly concise. I'd heartily recommend reading http://coala.readthedocs.io/en/latest/Getting_Involved/Writing_Good_Commits.html !

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix up the message for you - just tell us :).

Cheers!

**Comment by Asnelchristian** [comment]
btw. your PR is really good :) :+1

**Comment by Asnelchristian** [comment]
And use ``Fixes`` instead of ``Closed``

**Comment by sils1297** [comment]
no it should be Closes, not fixes!

**Comment by Asnelchristian** [comment]
ack https://github.com/coala-analyzer/coala/pull/2599/commits/1a0c2324d88ef1cdadf5a6f074d2e3d19a876a49

**Comment by Asnelchristian** [comment]
Hi,

it looks like your PR is out of date and needs a rebase. [This page](http://coala.readthedocs.org/en/latest/Users/Tutorials/Git_Help.html) may help you to get started on this. (*Do not press the update branch button. It's evil.*)

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix up the message for you - just tell us :).

Ping us on [our gitter channel](https://gitter.im/coala-analyzer/coala) if you need help!

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2599/commits/75e8db753445a01ddeceaab85e591408218977de

**Comment by sils1297** [comment]
reack https://github.com/coala-analyzer/coala/pull/2599/commits/fbb1e3d0415fdd6075af82be82773e61845cffcf

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
