### PR TITLE
Wip/sils/cced

### PR DESCRIPTION
**Pull request by sils1297**

### CODE REVIEW

**Comment by sils1297** [comment]
@rultor config from master please

**Comment by sils1297** [comment]
@rultor merge please

although I expect it to fail I'm interested in the log

**Comment by AbdealiJK** [comment]
@rultor merge - Lets see if rultor merges without errors

**Comment by sils1297** [comment]
@AbdealiJK it won't merge as it uses the old config with the new scripts i.e. its expected to fail

**Comment by AbdealiJK** [comment]
Ah - right - the old one doesn't know that it should decrypt the file.

**Comment by sils1297** [comment]
@AbdealiJK so the log outputs each command, i.e. it'll do the same for the encrypted file which we don't want, so I'll restrict access to the log

**Comment by sils1297** [comment]
@rultor stop please

**Pull request merged**
