### PR TITLE
find config bug

### PR DESCRIPTION
**Pull request by AbdealiJK**

### CODE REVIEW

**Comment by sils1297** [comment]
damn @AbdealiJK this needs a rebase!

**Comment by sils1297** [comment]
/me waited a long time to merge this PR... minutes and hours of time!

**Comment by sils1297** [comment]
reack all commits:
```
  1 pick a967d6e appveyor: Force pip to use wheels
  2 pick 976abcc find_user_config: Handle files, directories better
  3 pick e43d0a4 JSONFormatBear: Remove bare except statement
  4 pick 661c59c EspeakPrinter: Use subprocess.SubprocessError
  5 pick 44f0585 coala_delete_orig: Remove bare except
  6 pick 6f11ebb Processing: Import LOG_LEVEL correctly
  7 pick 9daf481 Processing: Use OSError in get_file_dict()
  8 pick 52e7d83 coala_json: Remove exception handling
  9 pick c928d81 Shell: Add get_shell_type()
 10 pick bbabbae Shell: Move functions around
 11 pick f13125a Shell: Use get_shell_type() to find shell
```

**Comment by sils1297** [comment]
@rultor merge

**Comment by AbdealiJK** [comment]
Thanks for rebasing :)

-----Original Message-----

**Pull request merged**
