### PR TITLE
Move tests dir to root

### PR DESCRIPTION
**Pull request by CruiseDevice**
Also made the required changes in the setup.cfg.

### CODE REVIEW

**Comment by sils1297** [comment]
hey, this needs a rebase. Also are you sure that none of the files actually import something from test files? As that import would need to be changed.

I'd like to have a second look after rebase and a second opinion because this can break things pretty ugly but then we should merge it ASAP as there's a high likelyhood of conflicts.

**Comment by sils1297** [comment]
ah apparently here is an import that needs fixing: https://scrutinizer-ci.com/g/coala-analyzer/coala/inspections/86b2ad9b-37bc-418a-a680-49aadb775c75/issues/files/tests/parsing/StringProcessing/EscapeTest.py?status=new&selectedLabels[0]=9&orderField=path&order=asc&honorSelectedPaths=0

**Comment by sils1297** [comment]
Hey, I just performed a merge and have to ask you to do another rebase, sorry :/

So if you do `git grep coalib.test` nothing turns up anymore, right?

**Comment by sils1297** [comment]
we're close to merging this ;)

**Comment by sils1297** [comment]
`git grep coalib.test` shows at least two relevant results in the documentation for me that need to be changed

**Comment by sils1297** [comment]
wait coverage is weird, is text execution broken?

**Comment by sils1297** [comment]
yeah something's definitely broken here.

**Comment by sils1297** [comment]
you may need to change `.misc/tests.sh` or something

**Comment by CruiseDevice** [comment]
What should i change there? Previously i didn't change anything from .misc/tests.sh

**Pull request closed without merging**
