### PR TITLE
Update Install.rst

### PR DESCRIPTION
**Pull request by priests**
Typo: Replace Max by Mac in Install.rst.

Fixes https://github.com/coala-analyzer/coala/issues/1749

### CODE REVIEW

**Comment by SanketDG** [comment]
@priests can you please take a look at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html and amend your commit as per as the guidelines?

**Comment by priests** [comment]
@SanketDG My mistake ! :)
Updating the comment will do or i shall go for a fresh request ?

**Comment by AbdealiJK** [comment]
Please amend the commit - dont create a new PR.
http://coala.readthedocs.org/en/latest/Getting_Involved/Newcomers.html tells you how to do it :)

**Comment by sils1297** [comment]
hey, please take another look at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html and do an interactive rebase to get rid of that merge commit. Make sure to get the full issue URL into the commit message. You know where you can find us if you need help.

**Pull request closed without merging**
