### PR TITLE
Fix Emacs plugin link

### PR DESCRIPTION
**Pull request by ramnes**

### CODE REVIEW

**Comment by Asnelchristian** [comment]
The commit looks good  :+1:  but you need to improve on your commit message http://coala.readthedocs.io/en/latest/Getting_Involved/Writing_Good_Commits.html use it as reference :)

**Comment by ramnes** [comment]
The diff is really small and the commit title make it obvious; what do you want me to add to the commit message?

**Comment by Asnelchristian** [comment]
you need to add the name of the file been affected in the sortlog of the commit message 
and the link of the issue that your fixing. Just follow the link i gave.

After that we will merge it :)

**Comment by sims1253** [comment]
Your shortlog does not contain a tag, which is not mandatory but we usually do it.
There doesn't seem to be an issue for this, which usually would be the only thing left for small commits like this.
So either do "README.rst: Fix Emacs plugin link" (.rst not madatory) or "Fix Emacs plugin link in README" so it is clear by the commit message alone where you fixed the link.

**Comment by ramnes** [comment]
Done.

You really should reconsider your PR workflow, though, and accept small contributions like this one easier; I just edited the README file in the GitHub interface while reading it, because I figured out it was the best way to help you fixing that small error, avoiding all the issue and stuff cumbersomeness.

With all that discussion about my one five characters diff commit and its message, I really feel like we all lost our time. Merging and amending the commit by yourself would have been way faster for everyone.

**Comment by sils1297** [comment]
Hey, we will definitely consider your opinion. May we contact you for
feedback about changing our workflow?

**Comment by sims1253** [comment]
Thank you for you feedback.
To clarify why we do it this way:

PRs like this are usually linked to a newcommer issue. We use those to teach newcommers our workflow and give them an easy start into the project to work their way up to difficulty low, medium, high... issues. This can certainly feel like overdoing it for such a small issue/pr but in general we get positive feedback from newcommers. If you have ideas/suggestions how to improve this we would like to hear them :)

Feel free do drop by in our [gitter channel](https://gitter.im/coala-analyzer/coala) for easier communication.

**Comment by sims1253** [comment]
ack 17ef521

**Comment by sils1297** [comment]
@rultor merge

**Comment by ramnes** [comment]
I understand. But a quick jump to user's profile will show you easily if he's used to contribute to projects or a real newcomer.

I'm pretty sure that https://github.com/coala-analyzer/coala/pull/2434 was abandoned because the author didn't want to spend more time on such a small PR, just like I almost abandoned the PR after the first comment.

> May we contact you for feedback about changing our workflow?

Sure. Best way to get me is on Freenode, same nickname.

**Comment by sils1297** [comment]
Hey @ramnes @sims1253 @Asnelchristian  what do you think of this as a pre-defined github response, as a guideline for contributors for review (see also: https://github.com/coala-analyzer/coala/wiki/Reply-Templates):

---

Hi,

it seems that your commit message doesn't contain enough information. Don't worry, most people don't know about good commit messages when they join us, including very experienced developers :) Standards vary from project to project.

The most important part is the first line of your commit message - maintainers will use it to read through a large number of commits and thus it's important that it's short but most importantly concise. I'd heartily recommend reading http://coala.readthedocs.io/en/latest/Getting_Involved/Writing_Good_Commits.html !

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix up the message for you - just tell us :).

Cheers!

**Pull request merged**
