### PR TITLE
Travis - linux support

### PR DESCRIPTION
**Pull request by AbdealiJK**

### CODE REVIEW

**Comment by AbdealiJK** [comment]
leave this open please, If cache isn't there - this will take wayy too long

**Comment by sils1297** [comment]
@AbdealiJK still working on this?

**Comment by AbdealiJK** [comment]
It's something I worked on. It wasn't complete because Travis hadn't whitelisted some apt packages. They still haven't whitelisted it.


-----Original Message-----

**Comment by sils1297** [comment]
@AbdealiJK we may want to close this, even if travis resolves that issue, if we switch to travis completely build times will rise again and travis build times are high enough. Your thoughts?

**Comment by AbdealiJK** [comment]
Why would build times rise if travis closes the issue ?
If travis closes the issue, we can go to containers (for linux) and the mac
build times wouldn't be affected

On Tue, Oct 13, 2015 at 11:24 PM, Lasse Schuirmann <notifications@github.com

**Comment by sils1297** [comment]
@AbdealiJK well, the number of parallel builds on travis is limited (I think to four) and thus if we add more builds it takes longer

**Comment by AbdealiJK** [comment]
Ah, I see -you want circleci dedicated for linux and travis dedicated for
osx.

Alright then

On Wed, Oct 14, 2015 at 11:27 AM, Lasse Schuirmann <notifications@github.com

**Pull request closed without merging**
