### PR TITLE
Move coalib/tests to root

### PR DESCRIPTION
**Pull request by srisankethu**
Fixes https://github.com/coala-analyzer/coala/issues/1636

### CODE REVIEW

**Comment by srisankethu** [comment]
Why did Scrutinizer fail?

**Comment by AbdealiJK** [comment]
The scrutinizer is giving expected results. Ignore it, it's fine.

**Comment by AbdealiJK** [comment]
unack dbfc9eb

**Comment by srisankethu** [comment]
@AbdealiJK So you want me to remove this in setup.py and circle.yml?

**Comment by AbdealiJK** [comment]
yep

**Comment by srisankethu** [comment]
@AbdealiJK Check :+1:

**Comment by srisankethu** [comment]
@AbdealiJK

**Comment by sils1297** [comment]
unack 87637bd , almost there!

**Comment by srisankethu** [comment]
Checked and all done :+1: .Tried `python3 setup.py bdist` and found tests in root.

**Comment by sils1297** [comment]
@srisankethu tests should *not* be there!

**Comment by srisankethu** [comment]
@sils1297 I found tests here dist/usr/local/lib/python3.4/dist-packages/tests

**Comment by sils1297** [comment]
@srisankethu the whole reason we have that exclude thing is so tests are *not* included because the user doesn't need them, tests are for developers only, maybe just keep the line as it was before and verify that tests are not distributed with it?

**Comment by srisankethu** [comment]
Ok

**Comment by sils1297** [comment]
ack 9abef0f

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
