### PR TITLE
seperator/separator issue fixed

### PR DESCRIPTION
**Pull request by cdesio**

### CODE REVIEW

**Comment by Asnelchristian** [comment]
follow this for the commit message coala.readthedocs.io/en/latest/Getting_Involved/Writing_Good_Commits.html  :)

**Comment by tushar-rishav** [comment]
ack https://github.com/coala-analyzer/coala/pull/2513/commits/372e4531fc6203e53e13256bd850640e2c906d05

**Comment by tushar-rishav** [comment]
@rultor merge

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
