### PR TITLE
Added venv/ to .gitignore file as requested in issue #1761

### PR DESCRIPTION
**Pull request by sapo1438**
For the virtualenv users.

### CODE REVIEW

**Comment by mr-karan** [comment]
Commit message is wrong. Use imperative tense. @sapo1438

**Comment by tushar-rishav** [comment]
unack e3ab4f7

**Comment by AbdealiJK** [comment]
Hey there,
You're used "Added" in the commit message's body. Again, this shold be imperative and hence should be "Add".

Everything looks great :) Good job !

**Comment by AbdealiJK** [comment]
unack 4d315ad

**Comment by Uran198** [comment]
ack 1f2bec2

**Comment by SanketDG** [comment]
@rultor merge

**Comment by sapo1438** [comment]
Contributed to an open source project - Check :D

**Comment by sils1297** [comment]
see https://github.com/coala-analyzer/coala/pull/1989

**Pull request closed without merging**
