### PR TITLE
LICENSE : Fixes https://github.com/coala-analyzer/coala/issues/1327

### PR DESCRIPTION
**Pull request by NalinG**
Made the file non-executable

### CODE REVIEW

**Comment by NalinG** [comment]
Really Sorry for this.

**Comment by sils1297** [comment]
unack f59207a, needs work on the commit message.

**Comment by AbdealiJK** [comment]
@NalinG this is a really small issue and could be fixed in about 10 mins

Could you look into it soon so that we can close this PR and issue ?

**Comment by AbdealiJK** [comment]
Closing as https://github.com/coala-analyzer/coala/pull/1434 supersedes it

**Comment by NalinG** [comment]
Sorry for late reply.Sent the PR already :)

**Pull request closed without merging**
