### PR TITLE
Collectors: Fixing param docs

### PR DESCRIPTION
**Pull request by swrj**
Fixing capitalization in parameter docs.

Fixes https://github.com/coala-analyzer/coala/issues/2506

### CODE REVIEW

**Comment by sils1297** [comment]
Hey,

the reason that build fails is because your commit message isn't imperative tense (at the bottom of the log you'll see that.) Don't worry, most people don't know about good commit messages when they join us, including very experienced developers :) Standards vary from project to project.

The most important part is the first line of your commit message - maintainers will use it to read through a large number of commits and thus it's important that it's short but most importantly concise. I'd heartily recommend reading http://coala.readthedocs.io/en/latest/Getting_Involved/Writing_Good_Commits.html !

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix up the message for you - just tell us :).

Cheers!

**Comment by sils1297** [comment]
a good verb could be `Capitalize`

**Comment by sils1297** [comment]
You also might want to fix your author information to get your commit correctly attributed to you. (`git commit --amend --author "Full Name <e.mail@address.tl>"`)

**Comment by swrj** [comment]
To clarify: The shortlog is fine but I need to change the long description to imperative tense right? So I just have to change the message to say "Capitalize param docs", fix my author information and then pushing the branch again right?
Thanks for all the help!

**Comment by sils1297** [comment]
Hey, the shortlog needs work, i.e. the first line. We're not that strict with the long docs because mostly people will only ever read the shortlog so that one has to be really concise and well standardized.

**Comment by sils1297** [comment]
Ouh did you push the update branch button? We don't want that.

You need a rebase. [This page](http://coala.readthedocs.org/en/latest/Users/Tutorials/Git_Help.html) may help you to get started on this.

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix it up for you - just tell us :).

Ping us on [our gitter channel](https://gitter.im/coala-analyzer/coala) if you need help!

**Comment by sils1297** [comment]
But it's ok most people do it sooner or later, I hate github for putting that button there ;)

**Comment by swrj** [comment]
When I typed git rebase --interactive upstream/master this showed up on vim: 


pick b687864 Collectors: Capitalize param docs
pick 1e5de65 Collectors: Fixing param docs

# Rebase 03fcb55..043c6c1 onto 03fcb55 (2 command(s))
#
# Commands:
# p, pick = use commit
# r, reword = use commit, but edit the commit message
# e, edit = use commit, but stop for amending
# s, squash = use commit, but meld into previous commit
# f, fixup = like "squash", but discard this commit's log message
# x, exec = run command (the rest of the line) using shell
# d, drop = remove commit
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
~

What should I do? Sorry if this is a silly question.

**Comment by sils1297** [comment]
edit the pick in the second line into a fixup (you  don't want your second commit right? Just the first one but with all the changes) and then close it and everything will be magically corrected by git :)

**Comment by swrj** [comment]
Yup that worked! Unfortunately somehow push --force brings up an error that there is no upstream branch. I pushed the last commit using git push origin master. Can I do that again? Or should I type git push --set upstream origin newbranch?

**Comment by sils1297** [comment]
then do `git push origin master --force` now

**Comment by swrj** [comment]
Weird, I got this message: Everything up to date.

**Comment by sils1297** [comment]
can you ping us on gitter?

**Comment by swrj** [comment]
I think I figured it out. I started all over again. The new pull can be found here: https://github.com/coala-analyzer/coala/pull/2643 
Sorry for all the inconvenience. I'll ping you guys on gitter ASAP.

**Comment by swrj** [comment]
You can close this pull request.

**Pull request closed without merging**
