### PR TITLE
Last piece of windows compatability

### PR DESCRIPTION
**Pull request by Makman2**
Appends the python file extension to coala. This allows Windows users
to run coala from command line if they have python in their PATH.
Also using the ".py" file extension is more consequent for python
files.

### CODE REVIEW

**Comment by Makman2** [comment]
I think this would then ensure complete Windows compatability :)
Only need to wait for CI on appveyor and we're ready :D

**Comment by Makman2** [comment]
Ah maybe add a note to the installation guide?

**Comment by Makman2** [comment]
Problems with other tests on Windows again...

**Comment by Makman2** [comment]
Squash the 1., 2. and 4. commit together?

**Comment by sils1297** [comment]
yes, please squash, also rethink commit message, you're escaping paths, not fixing bugs.

**Pull request merged**
