### PR TITLE
Changed `keep`/`keeping` to `maintain`

### LINKED ISSUE #2021: Change `keep` to `maintain`
We have a few grammar problems with keep throughout docs, and some places it sounds quite weird, therefore, as per @srisankethu 's suggestion, I recommend changing ``keep``/``keeping`` to ``maintain``.

The files and lines where we want this are:
docs/Users/Tutorials/Git_Help.rst line 126
docs/Users/Tutorials/Git_Help.rst line 204
docs/Getting_Involved/Newcomers.rst line 110

### PR DESCRIPTION
**Pull request by kranthikiran01**
As per recommendation, keep/keeping is changed to maintain in the suggested files.

Fixes #2021

### CODE REVIEW

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2187/commits/73d50c6a643df3a21858a884b21b6da7f738bb1a

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@kranthikiran01 first contribution, right? Congrats and welcome to the coalaians! :) See also https://github.com/coala-analyzer/coala/wiki/coala-Steam-Offer btw.

**Comment by kranthikiran01** [comment]
@sils1297 Thank you!! Its great to be part of coala :smile: 

Wow...the steam offer is exciting!! I will try to send a patch for `difficulty/low` issues. Thanks again :+1:

**Pull request merged**
