### PR TITLE
Fixes coala-analyzer#1494

### PR DESCRIPTION
**Pull request by 707**
Changed `not a is None` to `a is not None` in a occurring places. #1494

### CODE REVIEW

**Comment by sils1297** [comment]
somebody else will do a full review later, I have invited you to the team in the meantime so you can be assigned to issues

**Comment by sils1297** [comment]
hey, we can help you rebase your PR on https://gitter.im/coala-analyzer/coala , don't click github's merge branch button, it does nothing but harm.

**Comment by sils1297** [comment]
btw. welcome :)

**Comment by AbdealiJK** [comment]
Also, the commit message isnt according to the guidelines mentioned in http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html

**Comment by sils1297** [comment]
Hey, please ping us on https://gitter.im/coala-analyzer/coala if you need any help! : )

**Comment by sils1297** [comment]
Hey, @707 you have not accepted the invitation to our org and not responded to our requests. I'm just assuming you aren't interested anymore and will close this because we can't assign you if you're not in the org and this'll lead to conflicts later, especially since newcomer issues are rather popular.

Ping us if you're still interested so we can figure everything out.

**Comment by 707** [comment]
Hi Lasse,
I'm sorry for the late reply. I just signed up on coala's gitter.
Do you have any beginner guides to how i can properly help out?
Thanks for reaching out.

, Nadeem

On Sun, Feb 21, 2016 at 9:30 PM, Lasse Schuirmann <notifications@github.com>
wrote:

> Hey, @707 <https://github.com/707> you have not accepted the invitation
> to our org and not responded to our requests. I'm just assuming you aren't
> interested anymore and will close this because we can't assign you if
> you're not in the org and this'll lead to conflicts later, especially since
> newcomer issues are rather popular.
>
> Ping us if you're still interested so we can figure everything out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/coala-analyzer/coala/pull/1502#issuecomment-186850050>
> .
>



-- 
"Muwa-ha-ha-ha-ha!".......said the devil >(

**Comment by sils1297** [comment]
https://github.com/coala-analyzer/coala/wiki/Getting-Started-to-Contribute , please accept org invitation!

**Pull request closed without merging**
