### PR TITLE
DefaultArgParser: Change output metavar to FILE

### PR DESCRIPTION
**Pull request by sils1297**
Fixes https://github.com/coala-analyzer/coala/issues/2237

### CODE REVIEW

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2260/commits/fee949bafa8c3689e05d3c28dd4aea7b59c48983

**Comment by sils1297** [comment]
(re)

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@scottbelden can I get your twitter handle by the way?

**Comment by scottbelden** [comment]
@sils1297 I never bothered creating a twitter so I don't have one.

**Comment by sils1297** [comment]
No problem, do you mind if I still tweet about you doing great stuff?

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala-analyzer.org/ - http://viperdev.io/ - http://gitmate.com/

**Comment by scottbelden** [comment]
Not at all. Go right ahead.

**Pull request merged**
