### PR TITLE
Self-Correcting Bear Tutorial: Add to docs

### PR DESCRIPTION
**Pull request by aayn**
Added tutorial about self-correcting bears using `IndentBear` as an
example.

Fixes https://github.com/coala-analyzer/coala/issues/1638

### CODE REVIEW

**Comment by sils1297** [comment]
and run coala over your code please :)

**Comment by aayn** [comment]
@sils1297 I did try to run coala, but something's wrong This was the command I ran:
`coala --bear-dirs=../coala-bears/bears/natural_language/ --bears=reSTLintBear --files=docs/Users/Tutorials/Self_Correcting_Bears.rst -s`

 Because it didn't work, I just used gitmate-bot to correct me.

And, I'll make the other changes and PHP PR tomorrow. Must sleep now.

**Comment by sils1297** [comment]
you should be able to just do `pip install coala-bears` and then run `coala` in the dir, that should do it already

**Comment by sils1297** [comment]
ack  d7fb733

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
