### PR TITLE
coala_main: Handle None instead of result list

### PR DESCRIPTION
**Pull request by sils1297**

### CODE REVIEW

**Comment by fneu** [comment]
I guess I have to ask @rultor to merge this?

**Comment by sils1297** [comment]
Yes.

2015-09-23 0:06 GMT+02:00 rultor.com <notifications@github.com>:

**Comment by sils1297** [comment]
@fneu, so why aren't you doing it?

**Comment by fneu** [comment]
@sils1297 because I didn't know when it would answer me. Took a couple of minutes.

**Comment by fneu** [comment]
@rultor merge this please, selfish thing that you are to require your name at the beginning of the sentence ;)

**Pull request merged**
