### PR TITLE
bears: add PerlCritic bear and tests

### PR DESCRIPTION
**Pull request by sudheesh001**
Add the bears for perl critic for perl support
Add perl bear module and tests for perl
Add good perlcritic and bad perlcritic files for testing
Update appveyor and dependencies to run tests on CI
Fixes https://github.com/coala-analyzer/coala/issues/1259

### CODE REVIEW

**Comment by sils1297** [comment]
a rebase will fix your travis issue

**Comment by sils1297** [comment]
unack 60d5a74 needs work

**Comment by sils1297** [comment]
ack 58b56a0d3e51c18

**Comment by sils1297** [comment]
ack 7dcd8181 again, hope it passes now :/

**Comment by sils1297** [comment]
ack b785e1

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@rultor merge - really!

**Comment by sils1297** [comment]
/me gets a bit angry, today things just don't want to work

**Comment by sils1297** [comment]
@RULTOR MERGE !!!

**Comment by recursionbane** [comment]
The sequence of comments here, and rultor's responses, are rather hilarious.

**Pull request merged**
