### PR TITLE
ConsoleInteraction: Print colored output

### PR DESCRIPTION
**Pull request by sils1297**
Fixes https://github.com/coala-analyzer/coala/issues/2546

### CODE REVIEW

**Comment by tushar-rishav** [comment]
ack https://github.com/coala-analyzer/coala/pull/2550/commits/8dc4603b9a826ce03993dd759dc6d2eaf82efff7

**Comment by hypothesist** [comment]
ack https://github.com/coala-analyzer/coala/pull/2550/commits/8dc4603b9a826ce03993dd759dc6d2eaf82efff7

**Comment by hypothesist** [comment]
lol :D

**Comment by hypothesist** [comment]
reack https://github.com/coala-analyzer/coala/pull/2550/commits/100e6f7280b8d85cc397497b34713b09e76c43b5

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
