### PR TITLE
Remove CorrectionBasedBear

### PR DESCRIPTION
**Pull request by AbdealiJK**

### CODE REVIEW

**Comment by sils1297** [comment]
@AbdealiJK tests fail

**Comment by AbdealiJK** [comment]
Just saw it - figuring it out

**Comment by sils1297** [comment]
@AbdealiJK builds seem to be failing due to the go stuff.

**Comment by AbdealiJK** [comment]
@sils1297 that seems to be a random error.

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@rultor merge

**Comment by AbdealiJK** [comment]
@sils1297 thanks for rebasing it for me
@Makman2 DIdnt know that existed - sorry !

**Pull request merged**
