### PR TITLE
coalib/__init__.py:Remove pypy support

### PR DESCRIPTION
**Pull request by vidhan13j07**
Fixes https://github.com/coala-analyzer/coala/issues/1590

### CODE REVIEW

**Comment by sils1297** [comment]
unack 1805660, needs work

**Comment by sils1297** [comment]
your commit message is surprisingly good! Kudos for that!

**Comment by vidhan13j07** [comment]
Oh! I did not realise that . I'll make suitable changes and send the PR again .

**Comment by AbdealiJK** [comment]
unack aa9eb0b

**Pull request closed without merging**
