### PR TITLE
Remove unneeded documentation

### LINKED ISSUE #1343: coalib/tests/bearlib/__init__.py - documentation is wrong
The documentation in `coalib/tests/bearlib/__init__.py` has been erroneously copied from `coalib/bearlib/__init__.py`.

This needs to be removed.
To fix this, simply open `coalib/tests/bearlib/__init__.py` make the file empty and submit that as a patch.

### PR DESCRIPTION
**Pull request by srisankethu**
fixes #1343

### CODE REVIEW

**Comment by srisankethu** [comment]
@sils1297 Why is ci test failing when I did the same thing as in #1379

**Comment by AbdealiJK** [comment]
@srisankethu try running coala in your computer on this PR

**Comment by srisankethu** [comment]
@AbdealiJK How do I install install setuptools in Ubuntu because I'm struck there

**Comment by AbdealiJK** [comment]
Does `sudo apt-get install python3-setuptools` not work for you ?

**Comment by srisankethu** [comment]
@AbdealiJK Thanks I missed '3'

**Pull request closed without merging**
