### PR TITLE
Add guide for writing tests

### PR DESCRIPTION
**Pull request by Makman2**

### CODE REVIEW

**Comment by Makman2** [comment]
Maybe missing: Some asserts I don't covered, for example one that checks whether a call does **not** throw an error.

**Comment by Makman2** [comment]
Pushed new patch commit^^

**Comment by sils1297** [comment]
how about merging them again?

2015-03-03 21:16 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
Okay everything settled, I'll squash each commit... stand by :P

**Comment by sils1297** [comment]
and maybe review some commits...?

2015-03-03 21:21 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
update done, ready for merge

**Comment by Makman2** [comment]
Patch commit pushed^^

**Comment by sils1297** [comment]
could you squash and rebase?

**Comment by sils1297** [comment]
I took the freedom of doing that for you.

**Comment by sils1297** [comment]
still missing a hint about the -c and -H argument, and thats a really important one IMHO.

**Comment by Makman2** [comment]
I tried to install coverage3 but I think I got the wrong package. I don't know how this works^^
Could you maybe write the paragraph/hint/note?
Maybe we could keep it then also as an extra commit, No need to squash everytime, the guide is a good starting point now I think.

**Comment by sils1297** [comment]
I think the package is usually named `python-coverage3`. It works that way that you just install it and then run_tests.py takes care of everything else, no setup from you required, it's all done by me :)

**Comment by sils1297** [comment]
I'm so picky about this being in initially because it's very *very* important and you usually want to check your coverage whenever you write something. (At least for coala.)

**Comment by Makman2** [comment]
I'll try it, I first installed `python-coverage`. Everything seemed to point to it when googling for coverage3^^

**Comment by Makman2** [comment]
no such package in ubuntu. I had kept back packages, but I upgraded them and still not working.
Really can you please write the paragraph? As I said even no need to squash it, can be kept as an own commit since it extends the guide.

**Comment by sils1297** [comment]
ok, then squash your stuff and I'll push it to master.

**Comment by sils1297** [comment]
squashing, also inserting full bug URL instead of number only

**Pull request merged**
