### PR TITLE
Collectors: Capitalize param docs

### PR DESCRIPTION
**Pull request by swrj**
Fixing capitalization in parameter docs.

Fixes https://github.com/coala-analyzer/coala/issues/2506

### CODE REVIEW

**Comment by sils1297** [comment]
Hey,

we use some bug prediction in coala which relies on the `Fixes` keyword in commit messages. To get good results from that we need to use `Closes` for normal issues instead of `Fixes` which should only be used for real bugs. (See also [the commit message docs](http://coala.readthedocs.io/en/latest/Getting_Involved/Writing_Good_Commits.html).)

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

Cheers!

**Comment by sils1297** [comment]
looks ogod otherwise

**Comment by swrj** [comment]
Alright I will try amending it from "Fixes" to "Closes". If I run into any problems I'll message you guys on Gitter!

**Comment by sils1297** [comment]
https://github.com/coala-analyzer/coala/pull/2643/commits/99d4c392ffbb1e1c893b0db7dfb64c3e082f741c is ready

**Comment by swrj** [comment]
I think I finally figured everything out haha. Hope everything looks good?

**Comment by sils1297** [comment]
yes the `is ready` is an acknowledgement that your code is approved :)

**Comment by sils1297** [comment]
this is your first contribution? Congrats and welcome to the coalaians! :)

Rultor will now automatically release your changes as a prerelease so users can experience the goodness of your changes right now.

See also https://github.com/coala-analyzer/coala/wiki/coala-Steam-Offer btw.

**Comment by sils1297** [comment]
(waiting for all builds to pass before merge though)

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
there you go :)

**Pull request merged**
