### PR TITLE
Fix show bears

### PR DESCRIPTION
**Pull request by AbdealiJK**

### CODE REVIEW

**Comment by AbdealiJK** [comment]
I have no clue why `codecov` marks that line to be partially covered only. ideas anyone ?

**Comment by sils1297** [comment]
@AbdealiJK first guess would be that the lambda is never executed

**Comment by AbdealiJK** [comment]
reack
fd555dc coalib/__init__.py: Add __version__ variable
e49395c collect_all_bears_from_sections: Don't warn
8ffd026 coalaTest: Fix show_all_bears test
6b58b14 Collectors: Add bool for warning in collect_bears

**Comment by sils1297** [comment]
reack fd555dc coalib/init.py: Add version variable e49395c collect_all_bears_from_sections: Don't warn 8ffd026 coalaTest: Fix show_all_bears test 6b58b14 Collectors: Add bool for warning in collect_bears

**Comment by AbdealiJK** [comment]
reack 	 1c1f11b

**Comment by AbdealiJK** [comment]
@rultor merge

**Pull request merged**
