### PR TITLE
WIP: Sils/rename

### PR DESCRIPTION
**Pull request by sils1297**
CC @AbdealiJK for review

this introduces the delete and renaming only for the Diff class, other commits will follow so the actions behave accordingly.

Evolved from https://github.com/coala-analyzer/coala/pull/1801

### CODE REVIEW

**Comment by Makman2** [comment]
haven't you merged the non-wip version already? @sils1297

**Comment by sils1297** [comment]
@Udayan12167 can close and delete this is it doesn't contain relevant commits anymore

@Udayan12167 are *all* actions refactored to support deletions renamings properly? Can we have an example bear and make an asciicast of coala showing renaming diffs, doing the rename etc.?

**Comment by sils1297** [comment]
yes, one of the commits here isn't merged yet

**Comment by Makman2** [comment]
still valid? and which commit isn't merged yet?

**Comment by sils1297** [comment]
no I think this is all done by now

**Pull request closed without merging**
