### PR TITLE
Makman2/docext

### PR DESCRIPTION
**Pull request by Makman2**

### CODE REVIEW

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2615/commits/59683b0ed6b69601a1aa3458099311c760696630

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2615/commits/37e357fe48b25a2306b3d03ff5e64b4b1fd97576

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2615/commits/fb7690911be76e935167c940c9798d2e881c1515

**Comment by Makman2** [comment]
@rultor merge

**Pull request merged**
