### PR TITLE
Sils/pytest

### PR DESCRIPTION
**Pull request by sils1297**
adds a pytest config despite tests still failing with pytest

### CODE REVIEW

**Comment by sils1297** [comment]
@coala-analyzer/coala-reviewers noone wants to review this?

**Comment by Makman2** [comment]
I thought we don't want pytest?

**Comment by sils1297** [comment]
@Makman2 we probably want it on long term but we don't want it for now. This adds a first basic configuration which I already did so IMO we can merge it to have a basis for that.

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
