### PR TITLE
Sils/cherries

### PR DESCRIPTION
**Pull request by sils1297**
ack f72655a .gitignore: Add docs/API/
17095d3 OpenEditorAction.py: Update Success Message

### CODE REVIEW

**Comment by sils1297** [comment]
ack f72655a .gitignore: Add docs/API/
17095d3 OpenEditorAction.py: Update Success Message

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@madminions hey, I just merged your first contribution - congrats and welcome! :)

**Comment by sils1297** [comment]
Users can already enjoy it with pip install coala --pre because we're using automated development releases.

**Comment by madminions** [comment]
Thanks!!!

**Pull request merged**
