### PR TITLE
Added all $ signs i saw. Maybe i missed some.

### PR DESCRIPTION
**Pull request by svsn2117**
Issue URL: https://github.com/coala-analyzer/coala/issues/1747

### CODE REVIEW

**Comment by tushar-rishav** [comment]
@svsn2117 Please go through  http://tinyurl.com/coala-commit once. It'd be nice if you mention what commit your PR would fix. So that Github would automatically close the issue once your PR is merged.

**Comment by tushar-rishav** [comment]
Use `Imperative Present Tense` in commit message. No past or future tense etc.

**Comment by tushar-rishav** [comment]
unack 713473f

**Comment by AbdealiJK** [comment]
Also, "Added all $ signs i saw. Maybe i missed some." is not a good commit message

The git commit message you've used is not in accordance with the coala git commit guidelines.
Can you check out the [commit style documentation](http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html) and ensure you follow the guidelines mentioned there ?

To ensure you didn't miss anything, use `git grep`. A commit that you're not sure of will not get pushed into master.

**Comment by sils1297** [comment]
commit message, how about:

```
docs: Add $ for shell commands

Fixes <full url>
```

- Upper case `A`
- Colon for tag seperation
- Fixes note

**Comment by abhsag24** [comment]
unack 7be73c8 stll no `Fixes <full url>`

**Comment by Uran198** [comment]
You should remove colons from:
>Fixes: coala-analyzer#1747
As github may not close related issue.

**Comment by Uran198** [comment]
unack 08f8871

**Comment by sils1297** [comment]
see https://github.com/coala-analyzer/coala/pull/1989

**Pull request closed without merging**
