### PR TITLE
Install.md: Add note about python3 requirement

### PR DESCRIPTION
**Pull request by sudheesh001**
Added a tiny note about requirement for python3 for coala.

Fixes https://github.com/coala-analyzer/coala/issues/1270

### CODE REVIEW

**Comment by sils1297** [comment]
unack c9d87b7  also needs rebase apparently

**Comment by sils1297** [comment]
@sudheesh001 needs a rebase still, don't forget to fetch first from upstream

**Comment by sils1297** [comment]
@sudheesh001 what about the other comment that we already have a python 3 note a ew lines above?

**Comment by sils1297** [comment]
ack 48cb7f30c105d

**Comment by Makman2** [comment]
btw we can remove the recommendation @sils1297 , python 3.3 or later is required, 3.2 won't work^^

**Comment by sils1297** [comment]
@Makman2 you mean " you need" instead of "we recommend"?

**Comment by Makman2** [comment]
@sils1297 yes

**Comment by sudheesh001** [comment]
Changes made :smile:

**Comment by sils1297** [comment]
@Makman2 IMO it does the job well, I'm in favour of merging

**Comment by sils1297** [comment]
ack 433dead14 since it improves the code, if @Makman2 wants more he can file a bug

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
