### PR TITLE
CONTRIBUTING.rst:  Convert .md file to .rst

### LINKED ISSUE #1549: Convert CONTRIBUTING.md to a rst file
https://github.com/evonove/django-oauth-toolkit/blob/master/CONTRIBUTING.rst - contributing.rst is an accepted file in github

Need to convert our current markdown file to rst.

Also, when this is done - `coafile` 's [DOCS] section needs to be modified to reflect the new filename

### PR DESCRIPTION
**Pull request by pavithirakc**
.rst is an accepted file in github now.Hence the current markdown file
is converted to rst.Also,coafile's DOCS section is updated accordingly.

fixes #1549

### CODE REVIEW

**Comment by sils1297** [comment]
Hi and welcome! For starters, if you have any kind of issue, just drop by at https://gitter.im/coala-analyzer/coala so we can help you, especially in the beginning there's usually a lot to learn concerning the workflow. As you can see our little pet bot isn't really content with your commit message, you can see guidelines for that at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages . Second, your changes kind of belong together so we'd rather have them in the same commit. Could you squash them together? Git offers a `rebase --interactive` to do that kind of stuff, again if you need help with that we're there for you :)

**Comment by sils1297** [comment]
The overall code looks good.

**Comment by pavithirakc** [comment]
@sils1297  I have squashed my commits and changed the commit message.

**Comment by sils1297** [comment]
ok apart from the conversion this needs a rebase, squashing works well already. Did you get the invitation to our team? https://github.com/coala-analyzer

**Comment by sils1297** [comment]
unack 63f4b84

**Comment by sils1297** [comment]
unack  ea629de , this needs a bit of love still and a rebase

**Comment by AbdealiJK** [comment]
As you can see, you've left a few spaces after the end of a line - this is something we don't allow. You can fix this by simply running `coala` on the code.

Also, the git commit. The body of it (The ".rst is an accepted fil..." part) shouldnt be 1 huge line, rather break it up into smaller lines, each with a maximum of 72 characters (read more: http://stackoverflow.com/questions/2290016/git-commit-messages-50-72-formatting)

**Comment by AbdealiJK** [comment]
Also, you need a rebase

**Comment by sudheesh001** [comment]
unack b67191f

**Comment by sudheesh001** [comment]
@pavithirakc Please run `coala` and it'll make the corrections for you, then rebase and push it again :smile:

**Pull request closed without merging**
