### PR TITLE
Remove checkstyle.jar

### PR DESCRIPTION
**Pull request by SambitAcharya**
Fixes https://github.com/coala-analyzer/coala/issues/1412

### CODE REVIEW

**Comment by Makman2** [comment]
@SambitAcharya next time push force, then you don't need to reopen a new PR so we can track it better :)
And about the issue: The .jar file you remove is needed from our tests, and `setup.py` downloads it accordingly. Problem is `setup.py` is executed after doing tests. There's an ugly workaround for this, invoking `./setup.py --help`, since the download of the jar happens on every usage of that python script. That's something we maintainers need to discuss how we clean that up correctly. Please try if you get managed to add the command to the CI-files, if you have problems with it ping us and we will guide you :)

**Comment by Makman2** [comment]
ack 6dfff78 :+1:

**Comment by Makman2** [comment]
blocked by https://github.com/coala-analyzer/coala/issues/1465

**Comment by Makman2** [comment]
nvm

**Comment by sils1297** [comment]
yeah this needs a proper rebase, somebody can guide you through it on gitter. Marking it wip for now :)

**Comment by Makman2** [comment]
@SambitAcharya I've made a mistake for the windows build, the python command shall start with `python` and not `python3`. Could you change that? (inside `.misc/appveyor.yml`)

**Comment by SambitAcharya** [comment]
@Makman2 I made the changes. Let me know if i have rebased properly.

**Comment by sils1297** [comment]
@SambitAcharya looks like you didn't fetch before doig the rebase

**Comment by sils1297** [comment]
alright something has gone terribly wrong here, can you please fetch and rebase again?

**Comment by SambitAcharya** [comment]
@sils1297 i had done that before. Can i just close this issue and send a new PR with the necessary changes?

**Comment by sils1297** [comment]
It would be better if you learn how to do the rebase properly. It's not that hard once you get to know it and its very essential to our workflow. We can help you doing it right at gitter.

**Comment by Makman2** [comment]
ack 87f4153 81e8fea

**Comment by Makman2** [comment]
@rultor merge

**Pull request merged**
