### PR TITLE
JSONFormatBear: Add keep_unicode argument

### PR DESCRIPTION
**Pull request by sils1297**
Fixes https://github.com/coala-analyzer/coala/issues/1527

### CODE REVIEW

**Comment by sils1297** [comment]
@Makman2 did I mention that I *hate* unicode on windows?

**Comment by AbdealiJK** [comment]
@sils1297 you can simply do an if condition for the time being and mention that windows doesnt support keeping unicode ?
(As this blocks the folks a `zeroclickinfo-goodies` from using coala ... assuming they do not use windows)

**Comment by AbdealiJK** [comment]
:/ I just tested this on a windows cmd and they seem to pass

**Comment by AbdealiJK** [comment]
@sils1297 you can fix this by opening the file in `coalib.misc.ContextManagers.prepare_file` using something like
```
with open(filename, 'w', encoding='utf-8') as file:
```

Just tested it out and it worked.

**Comment by sils1297** [comment]
ack df77299 5021200 9b95c12, apparently gitmate really cares about it being lower case...

**Comment by sils1297** [comment]
alright, updated gitmate, it should handle casing now at least for ack/unack

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
