### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by Adrianzatreanu**

### CODE REVIEW

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2333/commits/b755cf818137fff83e62929991581dca1e8871ca

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2333/commits/de7efc08f23cf9b2809b0b193c350cafa1d16563

**Comment by sils1297** [comment]
rebase, reack and merge :)

**Comment by Adrianzatreanu** [comment]
done, and added a new one.

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2333/commits/c9165700b0cc99e915b4c1d57f7804e583e976fc

**Comment by sils1297** [comment]
reack 6c6ec4b

**Comment by sils1297** [comment]
reack https://github.com/coala-analyzer/coala/pull/2333/commits/c9165700b0cc99e915b4c1d57f7804e583e976fc

**Comment by sils1297** [comment]
reack 40e8d45

**Comment by sils1297** [comment]
reack 40e8d45

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
