### PR TITLE
DictUtilities.py: Fix incorrect example in docstring

### PR DESCRIPTION
**Pull request by stevemontana1980**
Change the result of inverse_dict to the correct value

Fixes https://github.com/coala-analyzer/coala/issues/2438

### CODE REVIEW

**Comment by sims1253** [comment]
Gitmate gives you two things that need to be fixed before this can be merged. Your shortlog is too long and there is a line that is too long in the code.

**Comment by Udayan12167** [comment]
Hi @stevemontana1980 , thanks for the pull request. As you see we have a gitmate-bot which automatically comments the problems with your PR. So it says here that your line length is longer than 80 characters which is the coala repository standard. So basically what gitmate-bot does is run coala on your pull request. To ensure that your pull request doesn't have any coding standard errors such as the line length and commit short log length in this case you just need to run coala on coala before pushing. For any further queries hit any of us up on gitter. Looking forward to more contributions from you. :)

**Comment by hypothesist** [comment]
ack https://github.com/coala-analyzer/coala/pull/2466/commits/12e0f71e9bf230146c5b5d0d6191709c1bf0d1f4

**Comment by hypothesist** [comment]
reack https://github.com/coala-analyzer/coala/pull/2466/commits/82a4da5d42c9126349bece2514b7773d73dd6226

**Comment by hypothesist** [comment]
@rultor merge

**Pull request merged**
