### PR TITLE
.coafile: Update coafile to change docs extension

### PR DESCRIPTION
**Pull request by ankitaggarwal011**
Migration from md to rst docs has to be updated in .coafile to run coala
on docs (rst files).

Fixes https://github.com/coala-analyzer/coala/issues/1341

### CODE REVIEW

**Comment by sils1297** [comment]
@ankitaggarwal011 please don't do any more newcomer issues after this, we don't have as many of them as we'd like.

**Comment by sils1297** [comment]
@ankitaggarwal011 hey you need to run coala over your code! :) apparently there's spacing issues with the rst files that coala can correct

**Comment by ankitaggarwal011** [comment]
@sils1297, sure.

**Comment by sils1297** [comment]
just running `./coala` will show you what's wrong and in most cases  autocorret it

**Comment by sils1297** [comment]
@AbdealiJK can you review this please? IIRC you had a possibly conflicting commit?

**Comment by ankitaggarwal011** [comment]
@sils1297, @AbdealiJK, I ran the ./coala and it didn't produce any warnings or errors. But this time, the gitmate produced these errors. Does these spacing issues has to be resolved in this PR?
I can squash all the commits into one and push. Let me know. Thanks!

**Comment by sils1297** [comment]
ys, please squash them and rebase properly. (I.e. don't squash with commits that are e.g. on master.)

**Comment by ankitaggarwal011** [comment]
@sils1297 , can you please help here. How do i rebase properly without squashing the commits that are on master?

**Comment by sils1297** [comment]
@Makman2 got some time? U have no time right now

**Comment by Makman2** [comment]
@ankitaggarwal011 fixing the problems right away would be good :)

**Comment by ankitaggarwal011** [comment]
@sils1297, @AbdealiJK, @Makman2, I have tried running ./coala over the code as suggest by sils1297, but that didn't produce any error or corrected any files. 
Gitmate produced some spacing issues in index.rst file, I have fixed those now, however, some tests are still failing. I am unable to see the details. Can you please review. Thanks!

**Comment by Makman2** [comment]
@ankitaggarwal011 you haven't fixed all issues, look at the bottom of the circleci build, there it displays the problems.

**Comment by AbdealiJK** [comment]
@ankitaggarwal011 Im moving this commit to my PR https://github.com/coala-analyzer/coala/pull/1522 as I already have fixed things there and gotten everything to work

**Comment by ankitaggarwal011** [comment]
@AbdealiJK, Cool!

**Pull request closed without merging**
