### PR TITLE
Removed rultor reader note from Review.md

### PR DESCRIPTION
**Pull request by bmanojkumar**
As suggested I have removed the rultor reader note from [Review.md](Review.md) file

### CODE REVIEW

**Comment by GitCop** [comment]
The commit message

 * Commit: 1b7c24954023e165a925f73aa731c1a933540024
  * Commits must be in the following format: **%{scope}: %{description}**

Guidelines are available at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
The commit message

 * Commit: 1b7c24954023e165a925f73aa731c1a933540024
  * Commits must be in the following format: **%{scope}: %{description}**

Guidelines are available at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages

---
This message was auto-generated by https://gitcop.com

**Comment by sils1297** [comment]
hey @bmanojkumar can you use a `git rebase --interactive` to get rid of that merge commit and squash your commits to one? Ping me on gitter if you need help : )

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@bmanojkumar very cool, thanks for your contribution!

**Comment by bmanojkumar** [comment]
@sils1297 Thank you so much for mentoring, it took a while for me to understand rebase and squash :+1:

**Pull request merged**
