### PR TITLE
WIP: Cancellation

### PR DESCRIPTION
**Pull request by Udayan12167**

### CODE REVIEW

**Comment by sils1297** [comment]
@Makman2 that build failed on appveyor waiting for an input, can you test this on windows ASAP?

**Comment by sils1297** [comment]
@Udayan12167 could you rebase and put the first commit of this in an own PR so we can merge that without solving the windows/cancellable issue?

**Comment by Makman2** [comment]
But please don't forget to ignore this test on windows^^

**Comment by sils1297** [comment]
@Makman2 any progress? Note that Udayans project relies on this...

**Comment by Makman2** [comment]
@sils1297 what do you mean with progress? Just make a platform dependent if that skips the test, something like
```python
if os.environment == "Windows":
  skiptest()
```
(Sorry I don't know the current environment variables and test skip mechanisms now, but I hope you got the idea :D)

**Comment by sils1297** [comment]
@Makman2 cancellability reaches to the core of coala we can't really implement it while skipping test for a supported platform.

**Comment by sils1297** [comment]
hey @Makman2 any progress?

**Comment by Makman2** [comment]
no, but I will do that the next days^^

**Comment by Makman2** [comment]
Reminder for me: Put actual `interrupt_process` definition into the platform-if.

**Comment by Makman2** [comment]
I think this is solved for now...

**Comment by Makman2** [comment]
@Udayan12167 do you still need the branch?

**Pull request closed without merging**
