### PR TITLE
documentation issues fixed

### PR DESCRIPTION
**Pull request by keerthisuresh**
code modified to obey
http://coala.readthedocs.org/en/latest/Getting_Involved/Codestyle/
Fixes#947

### CODE REVIEW

**Comment by sils1297** [comment]
Hi @keerthisuresh , thanks for submitting this PR! We will now review it, that's a normal process. It is very usual that on your first pull request we find several issues and there will be several iterations but it's nothing to be afraid of, we'll guide you through it and you can ask us for help whenever you need it.

**Comment by sils1297** [comment]
This is a little tricky, please do not use the github "Update branch" button, github then creates all those merge commits and they clutter the commit history, in the end it makes it very hard to see what actually happened. We usually use a rebase instead. If I'm assuming correctly you probably know @AbdealiJK or @Udayan12167 ? Maybe it's the best if they show you personally how that works - if that's an option. Otherwise I can explain it to you on gitter, just ping me on https://gitter.im/coala-analyzer/coala .

**Comment by keerthisuresh** [comment]
Sorry , won't happen again

**Comment by AbdealiJK** [comment]
@keerthisuresh I had mentioned how to update the branch by rebasing it. Could you rebase it and not merge ?
The merge creates this unnecessary commit https://github.com/keerthisuresh/coala/commit/1dd3debcd0c30ac55e4fb09f114dad7d2a471787 for no reason rebasing keeps it clean

**Comment by sils1297** [comment]
@keerthisuresh no need to be sorry, we all had our problems in the beginning :)

**Pull request closed without merging**
