### PR TITLE
Drop Python 3.3 support

### PR DESCRIPTION
**Pull request by sils1297**

### CODE REVIEW

**Comment by sils1297** [comment]
CC @underyx :)

**Comment by Adrianzatreanu** [comment]
ack 805d8a0

**Comment by underyx** [comment]
@sils1297 don't forget the explanation! :D

**Comment by sils1297** [comment]
not changing the commit now though, we're in need of this desperately right now because of the number of contributors around the table. Did you see our video yesterday?

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
