### PR TITLE
Add coala-orig to delete .orig files 

### LINKED ISSUE #1253: Find a way to delete .orig files created by ApplyPatchAction
right now orig files once created never get modified or deleted, until the user them-self deletes them, coala should provide a way to delete these files, either on start up or through a command line argument or maybe provide some other way to handle these files.

### PR DESCRIPTION
**Pull request by abhsag24**
Fixes #1253

### CODE REVIEW

**Comment by sils1297** [comment]
@abhsag24 there's one valid scrutinizer issue, an unused import

**Comment by sils1297** [comment]
@abhsag24 while you're at it, a rebase is needed too

**Comment by sils1297** [comment]
@abhsag24 still. Did you fetch from the main repo?

**Comment by abhsag24** [comment]
@sils1297 yes i wanted to make it quick ended up making a lot of errors :(

**Comment by sils1297** [comment]
unack 42621408

**Comment by sils1297** [comment]
unack aa3c44f73c

**Comment by sils1297** [comment]
unack 039da0fa97

**Comment by sils1297** [comment]
unack 1207bb8

**Comment by sils1297** [comment]
unack  347fd83  cc41cf1

**Comment by sils1297** [comment]
ack cedc6dee2c assuming you tested it also manually because this contains no test

**Comment by sils1297** [comment]
unack 9fc911d3858

**Comment by abhsag24** [comment]
@sils1297 i did test it manually but i think i 'll write a test now , thanks for the reminder :)

**Comment by abhsag24** [comment]
@sils1297 on the other hand i think it would be easier when #1280 gets a solution, then we can add the test as an own commit :)

**Comment by abhsag24** [comment]
it's unfinished i was updating my master and i accidentaly pushed unfinished work, i'll add the tests soon!

**Comment by abhsag24** [comment]
https://github.com/abhsag24/coala/commit/99a010ac0dc0aa439b8b11433735f41666a0b961
https://github.com/abhsag24/coala/commit/acbdb3fc31fae310e2f5c015f12e070eb012e857
for reference

**Comment by sils1297** [comment]
@abhsag24 please rebase to fix the travis issue

**Comment by abhsag24** [comment]
Ready for review :)

**Comment by sils1297** [comment]
ack d2c2ed46 edb8a814d3

**Comment by sils1297** [comment]
unack 59c849a0bc351b5732261026d896bc515ef467ba

**Comment by sils1297** [comment]
ack 261f9d8 though there seems to be some appveyor issue left :/

**Comment by abhsag24** [comment]
ready for review :)

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
