### PR TITLE
Fix typo: ShowPatchAction.py: `Wether` -> `Whether`

### PR DESCRIPTION
**Pull request by Satyam-Bharadwaj**
Fix typo: ShowPatchAction.py: `Wether` -> `Whether`

### CODE REVIEW

**Comment by sils1297** [comment]
Hi,

sorry for letting you waiting so long.

It seems that your commit message could receive some love. Don't worry, most people don't know about good commit messages when they join us, including very experienced developers :) Standards vary from project to project.

The most important part is the first line of your commit message - maintainers will use it to read through a large number of commits and thus it's important that it's short but most importantly concise. I'd heartily recommend reading http://coala.readthedocs.io/en/latest/Getting_Involved/Writing_Good_Commits.html ! Your's is already close and typos are kind of weird but maybe we can change this to `README: Change ... to ...` or so?

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix up the message for you - just tell us :).

Cheers!

**Comment by Satyam-Bharadwaj** [comment]
Hi,
@sils1297 this link that you just suggested http://coala.readthedocs.io/en/latest/Getting_Involved/Writing_Good_Commits.html 
seems to be broken.

Can you please suggest some alternatives.

Thank You

**Comment by sils1297** [comment]
http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html

but that messsage seens good

**Comment by Satyam-Bharadwaj** [comment]
@sils1297  Can you guide me as to why the ci/circleci test failed when i changed only the commit message and it succeeded last time.

**Comment by sils1297** [comment]
hey is this related to any issue?

**Comment by Satyam-Bharadwaj** [comment]
I m sorry i should've mentioned it in the commit message .
https://github.com/coala-analyzer/coala/issues/2719
this is the issue

**Comment by sils1297** [comment]
cool, can you change the commit message to include the Closes note?

**Comment by sils1297** [comment]
can you use the `Closes` as explained in the link I gave you about the commit messages?

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2721/commits/5c0fbea53c2a16b2d3dbc7234f342044192801a1

**Comment by sils1297** [comment]
Hey, this is your first contribution, right? Congrats and welcome to the coalaians! :)

Rultor will now automatically release your changes as a prerelease so users can experience the goodness of your changes right now.

See also https://github.com/coala-analyzer/coala/wiki/coala-Steam-Offer btw.

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
