### PR TITLE
coalaJSONTest.py: Add test to run coala-json

### PR DESCRIPTION
**Pull request by tushar-rishav**
Improve coverage by running `coala-json`

Fixes https://github.com/coala-analyzer/coala/issues/1384

### CODE REVIEW

**Comment by tushar-rishav** [comment]
@sils1297 You want me to make the changes and push?

**Comment by sils1297** [comment]
unack  ba1eec8 - this needs some love still ;)

**Comment by tushar-rishav** [comment]
@sils1297 Sure thing. :smile:

**Comment by sils1297** [comment]
unack 8367888, @tushar-rishav best you discuss how to improve this with @Makman2 or @AbdealiJK , we need a neat location for that function I can't think of any right now.

**Comment by sils1297** [comment]
unack f16efdd anyway :)

**Comment by sils1297** [comment]
@tushar-rishav did you see that scrutinizer apparently found some unused imports in your code? https://scrutinizer-ci.com/g/coala-analyzer/coala/inspections/86078a6b-0d2c-4b0c-931c-d3b557c427c2/issues/

**Comment by sils1297** [comment]
unack c2239835b

**Comment by sils1297** [comment]
ack a51f40fdb4d

**Comment by sils1297** [comment]
unack   d4f1a9 136b599

**Comment by sils1297** [comment]
we're almost there :) few corrections and a rebase needed

**Comment by sils1297** [comment]
reack e18c78e

**Comment by sils1297** [comment]
ack  	@tushar-rishav 	TestUtilities.py: Create utility to run coala … 	58cb929
	@tushar-rishav 	coalaTest.py: Fix regex match for test_find_issues … 	54d0812
	@tushar-rishav 	coalaJSONTest.py: Add test to cover`coala_json.py` … 	bd696a5

**Comment by sils1297** [comment]
ack 58cb929 54d0812 bd696a5

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
