### PR TITLE
Self Correcting Bears doc: Fix typo

### PR DESCRIPTION
**Pull request by aayn**
Fixed a minor typo in `Self_Correcting_Bears.rst`

### CODE REVIEW

**Comment by aayn** [comment]
Just saw this in the tutorial. Had to fix it.

**Comment by sils1297** [comment]
can you file a newcomer bug next time? We love newcomer bugs :P

**Comment by sils1297** [comment]
don't have time for review but looks good on first sight

**Comment by aayn** [comment]
OK Sorry. I forgot about that.
It's just one word of change, so can't be wrong : )

**Comment by aayn** [comment]
@Makman2 No. No issue. And, Okay. :)

**Comment by Makman2** [comment]
@aayn found the issue :D
https://github.com/coala-analyzer/coala/issues/1704

**Comment by aayn** [comment]
@Makman2 Oh. Oops :sweat_smile:
Done.

**Comment by Makman2** [comment]
ack d4b6417

**Comment by Makman2** [comment]
@rultor merge

**Pull request merged**
