### PR TITLE
Bear: Rename run_bear() to run()

### PR DESCRIPTION
**Pull request by Udayan12167**
I have succesfully renamed the run_bear() method to run() and the run() method to execute(). I hope i did it correctly. Please review!

### CODE REVIEW

**Comment by sils1297** [comment]
Seems you got all the git stuff right :)

**Comment by sils1297** [comment]
From https://github.com/coala-analyzer/coala/blob/master/doc/getting_involved/COMMIT_MESSAGES.md :

> The tag is usually the affected class or package and not mandantory.

Did you read that? Can I improve documentation somehow?

**Comment by Udayan12167** [comment]
Yeah i did read that and you can drop in an example git message along with the format.

**Comment by sils1297** [comment]
see #312 , if this is better for you, put an "ack" in a comment so I can push it to master. If you see anything in there that could be improved, please point out!

**Comment by sils1297** [comment]
you'll need to rebase because I merged #312

**Comment by Udayan12167** [comment]
I fixed the documentation too.

**Comment by sils1297** [comment]
cool, so one commit message correction left and then we can push it :)

**Comment by Udayan12167** [comment]
Which commit message?

**Comment by sils1297** [comment]
https://github.com/Udayan12167/coala/commit/14be6c2e951f59b18ea859593071cbbdce313461
does not have a correct commit message, long description is limited by 72 chars, breaking earlier unneededly decreases readability.

**Comment by sils1297** [comment]
Pushed to master, thanks for your contribution! I've updated the coala-tutorial repository too to mirror this change. (There are some example bears there.)

**Pull request merged**
