### PR TITLE
Bear.py: Add ``Code Simplification``

### PR DESCRIPTION
**Pull request by Asnelchristian**
Closes https://github.com/coala-analyzer/coala/issues/2419

### CODE REVIEW

**Comment by Makman2** [comment]
I think we should something else than `Code Simplification`, this `Code` feels a bit redundant. Maybe just `Simplification`?

**Comment by Asnelchristian** [comment]
we discuss about that and we agreed on ``Code Simplification`` but i get your point.

**Comment by Makman2** [comment]
alright :+1:

**Comment by Adrianzatreanu** [comment]
ack 2db418e

**Comment by Adrianzatreanu** [comment]
ack 2db418e

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Pull request merged**
