### PR TITLE
Glob: add glob and tests

### PR DESCRIPTION
**Pull request by smfn3321**

### CODE REVIEW

**Comment by sils1297** [comment]
tests are not finished I presume

**Comment by sils1297** [comment]
Commit messages: Upper case letter after colon

**Comment by smfn3321** [comment]
I am trying but git doesn't want to accept it as a change.... merged both commits to git would eat it.

**Comment by smfn3321** [comment]
resolved issues and rebased on current master

**Comment by sils1297** [comment]
huh?

**Comment by sils1297** [comment]
Coveralls seems to have a problem. merging anyway.

**Pull request merged**
