### PR TITLE
Remove bears/test in Writing_Tests.rs

### PR DESCRIPTION
**Pull request by iamgroot42**
Replaced `bears/test` with `test`
Fixes https://github.com/coala-analyzer/coala/issues/1821

### CODE REVIEW

**Comment by sils1297** [comment]
hey, seems there's a `t` missing in your commit message, also you need to add a fixes note. See http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html

**Comment by sils1297** [comment]
btw. welcome, is this your first commit? :) Do you need an org invitation?

**Comment by sils1297** [comment]
I've sent you an org invitation, see http://coala.readthedocs.org/en/latest/Getting_Involved/Newcomers.html#start-working if you can't find it

**Comment by iamgroot42** [comment]
@sils1297 yeah first commit to coala.
An org invitation would be awesome :)

**Comment by sils1297** [comment]
as per review c340ca1 needs work

**Comment by Adrianzatreanu** [comment]
hey @iamgroot42 are you still working on this :) ? if you need help, feel free to ping us on gitter https://gitter.im/coala-analyzer/coala ! we're online to help you :)

**Comment by Adrianzatreanu** [comment]
closing due to inactivity.

**Pull request closed without merging**
