### PR TITLE
docs: Move Git_Help to Tutorials section

### PR DESCRIPTION
**Pull request by mr-karan**
Moved Git Help from `Users` to `Tutorials` directory

Fixes https://github.com/coala-analyzer/coala/issues/1758

screenshot from 2016-03-01 13-13-04

### CODE REVIEW

**Comment by AbdealiJK** [comment]
unack 8db0e2c

**Comment by sils1297** [comment]
/me likes that he appended a screenshot :)

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-01 10:01 GMT+01:00 AbdealiJK <notifications@github.com>:

**Comment by sils1297** [comment]
hey we want only one commit, I think http://coala.readthedocs.org/en/latest/Getting_Involved/Newcomers.html might be helpful, you need a rebase interactive :)

**Comment by SanketDG** [comment]
ack db1d2407dfb6231df9e980ecd0dce230c4ebebb9

**Comment by SanketDG** [comment]
@mr-karan could have been a better commit message:

```
docs: Moved git help to Tutorials section 
```

**Comment by AbdealiJK** [comment]
unack db1d240

**Comment by AbdealiJK** [comment]
The commit message has to be in imperative `docs: Move Git_Help to Tutorials section `

**Comment by SanketDG** [comment]
ack 8e39c9f

Needs a rebase.

**Comment by mr-karan** [comment]
Can you instruct me how ? A bit confused. This is what I've been doing till now : 
```
git rebase -i master
# Pick, fixup/squash commits
git push remote movefile
```

**Comment by Makman2** [comment]
ack fb3f633

**Comment by AbdealiJK** [comment]
@rultor merge

**Pull request merged**
