### PR TITLE
docs: Add `setup.py develop`

### PR DESCRIPTION
**Pull request by hypothesist**
Add `python setup.py develop` to the documentation
explaining what it does and its uses.

Fixes https://github.com/coala-analyzer/coala/issues/1390

### CODE REVIEW

**Comment by Redridge** [comment]
basically change
Add `setup.py develop` to documentation
to
docs: Add 'setup.py develop'

in the commit message
Also in the future don't remove PR's

**Comment by hypothesist** [comment]
Done

**Comment by sils1297** [comment]
ack 89c02e0

**Comment by AbdealiJK** [comment]
Moving this to https://github.com/coala-analyzer/coala/pull/1625

**Pull request closed without merging**
