### PR TITLE
Newcomers: Shift link to next line.                                                                                                                          

### PR DESCRIPTION
**Pull request by swatilodha**
Fixes https://github.com/coala-analyzer/coala/issues/1780

### CODE REVIEW

**Comment by sils1297** [comment]
wip as per gitter discussion

**Comment by swatilodha** [comment]
Do I need to update the comment ?

**Comment by AbdealiJK** [comment]
@swatilodha yep :)
Let us know if you need help

**Comment by sils1297** [comment]
commit message needs work as per discussion on gitter and http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html

**Comment by swatilodha** [comment]
Is it okay now?

**Comment by sils1297** [comment]
you didn't change it!

**Comment by sils1297** [comment]
do not change the pull request title, you need to change the *commit message*!

**Comment by sils1297** [comment]
no need to close this PR, just amend and force push!

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-04 10:51 GMT+01:00 swatilodha <notifications@github.com>:

**Comment by sils1297** [comment]
http://coala.readthedocs.org/en/latest/Users/Tutorials/Git_Help.html#follow-up

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-04 10:52 GMT+01:00 Lasse Schuirmann <lasse.schuirmann@gmail.com>:

**Comment by swatilodha** [comment]
I've done the required changes.

**Comment by Makman2** [comment]
Please don't use merge commits, but rebases to update on our current master. So:
```
git fetch upstream
git rebase upstream/master
git push --force
```
This will automatically remove the already existing merge commit also :)

**Comment by swatilodha** [comment]
I've run the above commands but doesn't gives me option "update branch".

**Comment by Makman2** [comment]
I don't understand what you mean with
> [...] but doesn't gives me option "update branch".

Can you paste the commands and their outputs?

**Comment by AbdealiJK** [comment]
To clarify a bit ... the command `git rebase upstream/master` should have updated your branch.

It doesn't give you an option on whether to do it or not ... if you run the command, your branch will be updated.

Next, `git push --force` will update github with your local branch. i.e. you're forcing github to show your new branch which is updated with the earlier rebase you did

**Comment by swatilodha** [comment]
I understood you now. So now that I've changed the commit message, is the bug finally fixed and ready to be merged?

**Comment by sils1297** [comment]
@swatilodha you do need to do the rebase and then push force it up, ask around at gitter if you need any help

**Comment by Adrianzatreanu** [comment]
@swatilodha hey are you still working on this? :)

**Comment by Adrianzatreanu** [comment]
closing due to long inactivity.

**Pull request closed without merging**
