### PR TITLE
bears: Add Golint bear and tests

### PR DESCRIPTION
**Pull request by sudheesh001**
Add the bears for golint for deeper go support.
Add tests for good golint and bad golint files.

### CODE REVIEW

**Comment by AbdealiJK** [comment]
@SanketDG I was not online when you asked me to take a look at [this](https://circleci.com/gh/coala-analyzer/coala/3960) on gitter.
I believe the issue is that circleci uses Ubuntu 12.04 whereas you must be testing this on another ubuntu version. it would seem the 12.04 apt-get package needs some user interaction - which circleci cannot give.

Are you sure golang isn't already installed in circleci ? I think it would be ... (It has nearly all languages pre installed)
You can debug this better by using the ssh feature provided by circleci.

**Comment by sudheesh001** [comment]
@sils1297 Looks like this is ready.

**Comment by sils1297** [comment]
@AbdealiJK you know that you can totally merge stuff?

**Comment by sils1297** [comment]
ack f892b96

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
