### PR TITLE
Appveyor badge - changed from sils1297's account to an account named coala

### LINKED ISSUE #1671: Change appveyor badge in readme
The appveyor badge shows:

```
.. |Windows Build status| image:: https://img.shields.io/appveyor/ci/sils1297/coala/master.svg?label=windows%20build
   :target: https://ci.appveyor.com/project/sils1297/coala/branch/master
```
We recently changed from sils1297's account to an account named "coala"
So, it needs to be changed appropriately

### PR DESCRIPTION
**Pull request by AdeshAtole**
Fixes #1671

### CODE REVIEW

**Comment by Makman2** [comment]
Hi @AdeshAtole :)
Since this is your first contribution to our project, please read the getting-started guidelines [here](http://coala.readthedocs.org/en/latest/Getting_Involved/README.html).
Your changes are good but your commit message needs adjustment, you can read more on it [here](http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html) :D

Feel free to contact us at our gitter channel for help :)

**Comment by Makman2** [comment]
unack 8dc4a04

**Comment by AdeshAtole** [comment]
@Makman2 Do I need to close this PR and open a new one?

**Comment by AbdealiJK** [comment]
Nope, you can just amend the commit and push - this PR will get changed on its own when it notices your branch has changed

**Comment by sils1297** [comment]
Hey, the commit looks good but it needs a rebase, that should also remove the merge commit. If you don't know how that works, few keywords: fetch from upstream, then rebase on upstream/master. GitHub has a few tutorials on that or somebody might be able to help you on gitter.

**Comment by Makman2** [comment]
@AdeshAtole just for quickhelping here :)
```
git fetch upstream
git rebase upstream/master
git push --force
```
If you don't have setup an upstream for your fork, see https://help.github.com/articles/configuring-a-remote-for-a-fork/ :+1:

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@AdeshAtole neat! You're now ready to do real work! We'd love it if you try not to solve newcomer issues because we don't have enough - if you find typos or something please file some so other newcomers can enjoy the comfort.

**Comment by AdeshAtole** [comment]
@sils1297 Sure!! :+1:

**Pull request merged**
