### PR TITLE
various bits, including pushing forward code clone detection

### PR DESCRIPTION
**Pull request by sils1297**
at least the first two commits are ready, nonready commits are marked with WIP in commit message so please go ahead reviewing the others.

### CODE REVIEW

**Comment by sils1297** [comment]
all finished

**Comment by Makman2** [comment]
You have test errors, haven't you?

**Comment by Makman2** [comment]
or shall I review the commits until "all finished"?

**Comment by sils1297** [comment]
@Makman2 yeah. The test errors are because of ubuntu dependency problems, you can do the first two commits.

**Comment by sils1297** [comment]
@Makman2 now its all finished and tests pass.

**Comment by Makman2** [comment]
I'll look at the Clang commits later, they are quite big^^

**Comment by Makman2** [comment]
Why did you close all issues related to this PR? They are not merged oO

**Comment by sils1297** [comment]
I merged the acked ones. Who says you can't merge half prs?

2015-05-02 19:33 GMT+02:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
I'm too much relying on GitHub... sorry :O

**Comment by Makman2** [comment]
The biggest problem is that these commit break coala on windows, many tests start failing. I think because we support windows now (patches laying in #503) we should try to keep it working on windows^^

**Pull request closed without merging**
