### PR TITLE
Git_Help: Change commiting -> committing

### PR DESCRIPTION
**Pull request by kmo1**
Closes https://github.com/coala-analyzer/coala/issues/2474

### CODE REVIEW

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2626/commits/c112f50a6d77daaad98f408d0a38efeb461cb648

**Comment by sils1297** [comment]
unack https://github.com/coala-analyzer/coala/pull/2626/commits/a4215d628255573d5cd84b60f235105cca05456f , there's a colon after the closes and github won't automatically close the issue. Also feel free to pick up difficulty low issues from now :)

**Comment by sils1297** [comment]
newcomer issues are for learning essentially, they usually do take us more time to file than to fix

**Comment by sils1297** [comment]
ah builds on your first commit seem to fail you might wanna look at that, ping us if you need help! :)

**Comment by kmo1** [comment]
I made some mistakes so I'm going to create a new pull request, apologies for burning time

**Comment by abhsag24** [comment]
moved one of the commits to https://github.com/coala-analyzer/coala/pull/2631

**Pull request closed without merging**
