### PR TITLE
WIP Add AlexBear

### PR DESCRIPTION
**Pull request by sils1297**
needs input from @wooorm for installing alex properly on CI

### CODE REVIEW

**Comment by AbdealiJK** [comment]
@sils1297 Do these provide patches also ?
Should I fix the CI issue or should I port it to `Lint` class ?

**Comment by sils1297** [comment]
Do what you want on this one :) Alex can provide corrections I *think* but
the regex doesn't capture those IIRC. You can do a simple integration
first. The problem is that we have to download the JS at some step, we may
want a way to add JS dependencies to our setup.py?

2015-12-08 13:07 GMT+01:00 AbdealiJK <notifications@github.com>:

**Comment by AbdealiJK** [comment]
Closing this in favour of https://github.com/coala-analyzer/coala/pull/1109

**Comment by AbdealiJK** [comment]
Reopening as that PR doesnt handle mdast (yet)

**Comment by sils1297** [comment]
mdast is in https://github.com/coala-analyzer/coala/pull/1128 now

**Pull request closed without merging**
