### PR TITLE
coalib/results/Diff.py: Fix typo in from_clang_fixit class

### PR DESCRIPTION
**Pull request by saurabhiiit**
Fixes https://github.com/coala-analyzer/coala/issues/1765

### CODE REVIEW

**Comment by srisankethu** [comment]
@sils1297  Seems ok to me!

**Comment by AbdealiJK** [comment]
ack dd34afc

**Comment by AbdealiJK** [comment]
ack dd34afc

**Comment by AbdealiJK** [comment]
@rultor merge

**Pull request merged**
