### PR TITLE
Import sorting

### PR DESCRIPTION
**Pull request by AbdealiJK**

### CODE REVIEW

**Comment by AbdealiJK** [comment]
Something weird going on with pyenv in circleci.

It seems `python setup.py install` installs coala fine. But it isnt symlinked to `~/.pyenv/shims` like it should. No idea why.

**Comment by AbdealiJK** [comment]
Blocked by https://github.com/coala-analyzer/coala/pull/1404

**Comment by AbdealiJK** [comment]
@sils1297 you mentioned something abt unused imports?

**Comment by sils1297** [comment]
@AbdealiJK grab me on gitter about the unused import topic. If that doesn't work properly we have a bug.

**Comment by sils1297** [comment]
superseded by https://github.com/coala-analyzer/coala/pull/1406

**Pull request closed without merging**
