### PR TITLE
.misc: Add missing goimports

### PR DESCRIPTION
**Pull request by sudheesh001**
GoImports added to deps.osx and appveyor build for travis
and appveyor to pass the goimports test.

### CODE REVIEW

**Comment by sudheesh001** [comment]
Unrelated test failure: https://circleci.com/gh/coala-analyzer/coala/4314

**Comment by sils1297** [comment]
@sudheesh001 tests pass after restarting that one.

**Comment by sils1297** [comment]
ack 5c5df3a

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
