### PR TITLE
Improve coverage for main routines

### PR DESCRIPTION
**Pull request by tushar-rishav**
Fixes [1444](https://github.com/coala-analyzer/coala/issues/1444)

### CODE REVIEW

**Comment by sils1297** [comment]
unack 19f2496a0

**Comment by AbdealiJK** [comment]
ack d56805a

**Comment by sils1297** [comment]
ack 86cefa5140b  7c2d4adfbd

**Comment by sils1297** [comment]
the rest needs minor work

**Comment by sils1297** [comment]
unack 87a4759 312799e d881b50

**Comment by AbdealiJK** [comment]
ack ec01861eb58836

**Comment by AbdealiJK** [comment]
ack  bcea601 47d1d4d 370f8ae 5d8d241 2dd0b37

**Comment by sils1297** [comment]
fwiw coverage isn't fully fixed yet with this https://codecov.io/github/coala-analyzer/coala/coalib?ref=2dd0b378329d2acc45d0e8917170317b5d7496df

**Comment by AbdealiJK** [comment]
@sils1297 @tushar-rishav Ive already fixed some of that coverage locally - so lets continue with the PR. Ill add the rest in my next PR

**Comment by AbdealiJK** [comment]
commits moved to https://github.com/coala-analyzer/coala/pull/1504

**Pull request closed without merging**
