### PR TITLE
tests/bearlib: Remove double documentation

### PR DESCRIPTION
**Pull request by srisankethu**
Fixes https://github.com/coala-analyzer/coala/issues/1343

### CODE REVIEW

**Comment by srisankethu** [comment]
@Makman2 This would be my last PR for an issue of difficulty/newcomer because this was the first issue I had taken up

**Comment by Makman2** [comment]
ack a7da7b6

**Comment by Makman2** [comment]
@rultor merge

**Comment by Makman2** [comment]
@srisankethu alright, your next PR is merged :D that one went through easily :+1:

**Pull request merged**
