### PR TITLE
GitCommitBear should run from different directory

### LINKED ISSUE #1294: git commit bear doesn't work if coala isn't run in the same directory
it should also work if I provide a coafile with `-c`, @Makman2 can you fix that soonish? This is kind of the reason why this breaks everywhere for my gitmate experiments.

### PR DESCRIPTION
**Pull request by abhsag24**
Fixes #1294

### CODE REVIEW

**Comment by sils1297** [comment]
unack  1f4fd4c e3cf0d7

**Comment by abhsag24** [comment]
https://github.com/abhsag24/coala/commit/8a875cb0c34189e50d398fbe836081dc5bd98e8a for reference

**Comment by abhsag24** [comment]
Ready for review :)

**Comment by sils1297** [comment]
ack 1b9d804  d435da3

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
