### PR TITLE
Modification to Dependencies.py

### PR DESCRIPTION
**Pull request by shubhamrajput**
A generator expression shortening the code to CircularDependencyError  in Dependencies.py

### CODE REVIEW

**Comment by sils1297** [comment]
Hey, this one needs a little git love, we need you to do a `git rebase --interactive` from your PC with this branch and remove those merge commits ;) maybe ask @SanketDG for help, he also just learned it and seems to master it.

**Comment by AbdealiJK** [comment]
@shubhamrajput do you need any help with this ?

**Comment by Makman2** [comment]
@shubhamrajput 
You should get rid of the merge commits when you do
`git fetch upstream/master`
`git rebase upstream/master`
`git push --force`
if your master branch is protected you can temporarily unprotect it inside the GitHub settings and do a `git push --force` again. After that you should have a single clean commit ontop of our master :)

**Comment by AbdealiJK** [comment]
@shubhamrajput still working on this ?
@sils1297 can I cherry pick this ?

**Comment by sils1297** [comment]
@AbdealiJK feel free to cherry pick this and beaufity the commit message, keep author information please.

**Comment by sils1297** [comment]
@shubhamrajput still interested in working on this?

**Comment by sils1297** [comment]
is there an issue reference anyway?

**Comment by sils1297** [comment]
closing unmaintained newcomer PR

**Pull request closed without merging**
