### PR TITLE
README: fix the tutorial link

### PR DESCRIPTION
**Pull request by championswimmer**
Fixes https://github.com/coala-analyzer/coala/issues/1576

### CODE REVIEW

**Comment by championswimmer** [comment]
@AbdealiJK is it good to go now ?

**Comment by AbdealiJK** [comment]
@championswimmer now quite, can you please remove the "Merge branch 'master' into patch-1" commit ?
If you need help with that drop by https://gitter.im/coala-analyzer/coala so we can help you !

**Comment by sils1297** [comment]
Also the fixes note should go into the commit message.

**Comment by sils1297** [comment]
needs work, we can help you at gitter if there's need

**Comment by championswimmer** [comment]
@sils1297 I will make the needed changes :) 
I'll join Gitter too, but I can manage these changes on my own

**Comment by sils1297** [comment]
still needs a rebase (more info on https://github.com/coala-analyzer/coala/wiki/Getting-Started-to-Contribute)

**Comment by AbdealiJK** [comment]
ack 19068fb

**Comment by AbdealiJK** [comment]
@rultor merge

**Pull request merged**
