### PR TITLE
 Dependencies.py: Simplifies code in class CircularDependencyError

### PR DESCRIPTION
**Pull request by lonewolf07**
Fixes https://github.com/coala-analyzer/coala/issues/1281

### CODE REVIEW

**Comment by SanketDG** [comment]
@lonewolf07 This is good to go. All you need to do is squash the commits, do a rebase with the master branch. Come to https://gitter.im/coala-analyzer/coala if you need ay help :)

**Comment by sils1297** [comment]
please also remove the space *before* the colon

**Comment by SanketDG** [comment]
unack 29ae8a121d8bfd64d17333991a6b720254edb416

**Comment by SanketDG** [comment]
ack https://github.com/coala-analyzer/coala/commit/ee2f9fcc41a2cb94a28774a5a7c8ecad7d57ed02

**Comment by SanketDG** [comment]
@rultor merge

**Pull request merged**
