### PR TITLE
Makman2/unregexify

### PR DESCRIPTION
**Pull request by Makman2**
Adds the `use_regex` parameter to all existing StringProcessing functions.

### CODE REVIEW

**Comment by sils1297** [comment]
I assigned @smfn3321 for review, he is probably better suited. I may take a look here and there but thats only supplemental.

**Comment by sils1297** [comment]
please also look at scrutinizer issues, some more duplication detected plus all those names are far too long

**Comment by Makman2** [comment]
The names indicate the test structure, so I don't know how to rename them so the names makes still sense but much shorter.
Also the code duplication applies for the specific tests. I can put them into a function but they would be used only one time, so doesn't make much sense^^

**Comment by sils1297** [comment]
I'm still not convinced we're writing the tests the right way because this is getting so complex and bad.

**Comment by Makman2** [comment]
Give me hint *-*

**Comment by sils1297** [comment]
It's nothing more than this, I don't have any clue on how to improve that. ;)

**Comment by smfn3321** [comment]
Sorry I still can't really review yet, but I agree that tests are way to complicated here. And I'm not complaining about the duplication.

For example, in your last commit you added:
```
def test_unescaped_search_in_between_disabled_regex(self):
    self.assertUnescapedSearchInBetweenEquals(
        self.test_strings,
        self.test_unescaped_search_in_between_disabled_regex_expected,
        self.test_unescaped_search_in_between_disabled_regex_pattern,
        self.test_unescaped_search_in_between_disabled_regex_pattern,
        0,
        True,
        False)
```
The only thing this method does is calling another (previously defined) method with a lot of parameters that one needs to look up (somewhere else). It is really hard to understand what is going on there since you have to look up the params and then the method and it really doesn't help that everything looks so similar.

To be honest, I would actually allow more code duplication in favor of better readability. Since you got a list of test strings, I would consider making it available at the class or module level for all functions. I would define results in the tests themselves though and pass the patterns directly. This way, it is far easier to understand the tests since everything is at one place and readable.

Also, please look at the python zip command, this could probably make the iteration simpler.

**Comment by Makman2** [comment]
`zip()` is definitely a good alternative for assertions. But I'll only include it if I need to refactor tests again^^

But I think the last commit you refer to is already in master, so why do you review that one? :O

Also I don't know if it's that a problem to look up the assertion functions. Once you read the little doc it's obvious what they do. It's no big deal to look up some functions, I need to do that permanently when programming. I would then really go over minimal code-duplication, since changing duplicated code involves changing it everywhere where it's duplicated^^

Btw, the test string is already at module level like any other testing parameter. I think I haven't something local there. The idea behind to put everything into module level is that many tests have similar results that can be easily derived from a "master-result".

**Comment by smfn3321** [comment]
The commit I cited was https://github.com/coala-analyzer/coala/commit/d9c5c2be7cfdc98a57edba391fa469f5de52ef9c which is your second to last commit ^^


--

It really is a shame that subtests did not get introduced before python 3.4
```
class NumbersTest(unittest.TestCase):

    def test_even(self):
        """
        Test that numbers between 0 and 5 are all even.
        """
        for i in range(0, 6):
            with self.subTest(i=i):
                self.assertEqual(i % 2, 0)
```
==>
```
======================================================================
FAIL: test_even (__main__.NumbersTest) (i=1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "subtests.py", line 32, in test_even
    self.assertEqual(i % 2, 0)
AssertionError: 1 != 0

======================================================================
FAIL: test_even (__main__.NumbersTest) (i=3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "subtests.py", line 32, in test_even
    self.assertEqual(i % 2, 0)
AssertionError: 1 != 0

======================================================================
FAIL: test_even (__main__.NumbersTest) (i=5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "subtests.py", line 32, in test_even
    self.assertEqual(i % 2, 0)
AssertionError: 1 != 0
```

**Comment by Makman2** [comment]
Yeah but the commit uses the assert function introduced from me in an earlier pull request.

And what are subtests?
I don't understand your example :D

**Comment by smfn3321** [comment]
It's not really related to this PR, ant only got introduced in 3.4 so we probably won't use it anyway. Subtests are useful when your unit tests performs the same test over a range of inputs (as is the case here). They provide a separate test for every input set that can fail on its own.

Atm, we only know whether the test passed for the entire result list/dict or failed at some point. With subtests, we would have known which inputs worked and which not.

In the above example, a subtest is specified for each integer that checks whether or nor the integer is even. You can see that the test fails separately for every uneven number ;)

**Comment by sils1297** [comment]
@smfn3321 can we somehow emulate that subtest class for python < 3.4 like we do with the barrier?

**Comment by smfn3321** [comment]
https://docs.python.org/3/library/unittest.html#unittest.TestCase.subTest
 
I'm sure that it is *possible* but I don't think it is worth it. It doesn't add any features to coala and we should probably focus on the main program and not the tests. 

I like to use subtests during initial testing on 3.4 for debugging. It is fairly easy to add to a test if you don't understands where exactly it fails.

**Comment by sils1297** [comment]
half of the code in coala is tests, if we can ease that a bit with reasonable amount of work we should do it IMO.

Other possibility is to drop support for python <3.4: https://lists.debian.org/debian-devel-announce/2015/03/msg00016.html and https://packages.debian.org/jessie/python3

**Comment by sils1297** [comment]
Hey, if no one has anything against it we'll drop support for python 3.2
and 3.3 so we can use those subtests.

Ubuntu LTS does have 3.4, the Debian released later this month will also
have that, fedora 22 has it and with brew on Mac you get it. Arch is no
question.
Am 13.04.2015 13:12 schrieb "Fabian Neuschmidt" <notifications@github.com>:

**Comment by Makman2** [comment]
You sure? 3.4 is quite new^^

**Comment by sils1297** [comment]
Its over a year since 3.4.0
Am 13.04.2015 21:04 schrieb "Makman2" <notifications@github.com>:

**Pull request merged**
