### PR TITLE
Makman2/escaping3

### PR DESCRIPTION
**Pull request by Makman2**
Takes over as v3 from #364.

Main changes:
- Restructurized test data/results (each function under test got an own `setUp` function), so code duplication is minimized and also test results are easier to oversee and edit.
- Tests: Added some test strings/cases
- `search_for()`: removed `max_match` parameter, since it's not needed because of the generator behaviour.
And because of that it became just a forwarding function for `re.finditer()`.
- `search_in_between()`/`unescaped_search_in_between()`: Filter generators for easier matching algorithm.

### CODE REVIEW

**Comment by Makman2** [comment]
Comment for build:
`yield from` is introduced in python 3.3

**Comment by sils1297** [comment]
then you can't use it or you need to do a custom branch for python 3.2 since we want to support that

**Comment by Makman2** [comment]
Hm no problem, then just using
```
for elem in iter:
    yield elem
```

**Comment by Makman2** [comment]
Okay changed^^

**Comment by Makman2** [comment]
Man why GitHub again displays the commits in the wrong order? That bugs me somehow...

**Comment by Makman2** [comment]
Ah damn syntax error, I should have run the tests again... stand by...

**Comment by sils1297** [comment]
Yeah, I really hate github for that.

2015-03-16 0:34 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
I don't know why git itself tells me that I introduced an whitespace error because of the `\n` at EOF but looking at the commit 01e77f0 everything seems to be okay.

**Comment by sils1297** [comment]
I *think* git tells you because you got two `\n` before EOF. Ideally your last line holds a few chars (is nonempty) followed by `\n` - which some editors show as an own line and some don't because originally every line has to end with a \n, its not like a line *seperator* but more like a line *ending*.

**Comment by sils1297** [comment]
#388 takes over

**Pull request closed without merging**
