### PR TITLE
Diff.py: changed "doesnt" -> "doesn't"

### PR DESCRIPTION
**Pull request by cdesio**
Closes https://github.com/coala-analyzer/coala/issues/2489

### CODE REVIEW

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2518/commits/5ea38d7d1ab15797c45e6b1bed56796ee756af35

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@cdesio awesome! That's already your second, huh?

**Comment by cdesio** [comment]
Yeah, next time I'll try to avoid push -f :D

**Comment by sils1297** [comment]
Getting it right the first time? That's hard. Except if you're not a newcomer doing newcomer issues ;) We sometimes take months to review bigger PRs :)

**Pull request merged**
