### PR TITLE
Tests: Minor fixes

### PR DESCRIPTION
**Pull request by AbdealiJK**

### CODE REVIEW

**Comment by sils1297** [comment]
@AbdealiJK merge at will

**Comment by AbdealiJK** [comment]
I just realized `alex` seems to fail when I do local npm install

Let me check that out ...

**Comment by AbdealiJK** [comment]
reack  0feadb1 6b57217 d929796

**Comment by AbdealiJK** [comment]
reack  8890d56

**Comment by Makman2** [comment]
@rultor merge

**Pull request merged**
