### PR TITLE
docs: Add example commit message for typos

### PR DESCRIPTION
**Pull request by manojpandey**
Add example commit message about typos in
newcomer page in docs.

Fixes https://github.com/coala-analyzer/coala/issues/1757

### CODE REVIEW

**Comment by AbdealiJK** [comment]
Just put example 1, example 2 ?
This makes it look like we have a specific format for typo errors. We want the typo error message as an example because that's the most popular type of newcomer issue.

**Comment by manojpandey** [comment]
All right, will do. Thanks :)

**Comment by AbdealiJK** [comment]
ack cb6bcb1

**Comment by AbdealiJK** [comment]
@rultor merge

**Pull request merged**
