### PR TITLE
Fix inconsistency in quotes

### PR DESCRIPTION
**Pull request by beatrix-bodo**

### CODE REVIEW

**Comment by AbdealiJK** [comment]
I remember discussing adding a quote-style to the style guide with @sils1297 once.
He said he *likes* having double quotes and single quotes because it's easier to use (or so).

**Comment by sils1297** [comment]
single quotes are awesomely simple to type on an english keyboard layout, I see no benefit in making this consistent. Where is the issue? Didn't it have a needs design? CC @underyx

**Comment by sils1297** [comment]
my fault, this switches *to* single quotes, sorry @beatrix-bodo

**Comment by beatrix-bodo** [comment]
@sils1297 I did this based on the comments, precisely this one:

1. if only ' occur inside string, use "
2. If ' and " are mixed inside string, use '
3. Otherwise use ' everywhere

I'm not sure anymore which one you guys prefer :)

**Comment by Asnelchristian** [comment]
this is good :)

**Comment by Asnelchristian** [comment]
ack https://github.com/coala-analyzer/coala/pull/2726/commits/cba3ea58da193ac3e49f14160f546b0f81b70dcb

**Comment by underyx** [comment]
https://github.com/coala-analyzer/coala/pull/2726/commits/cba3ea58da193ac3e49f14160f546b0f81b70dcb needs work

**Comment by Asnelchristian** [comment]
in that case i am marking it WIP

**Comment by underyx** [comment]
The commit message is actually not in line with the guidelines. @beatrix-bodo please see http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html#what-makes-a-good-commit

The specific issues are 
- The [shortlog](http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html#shortlog) is missing a tag. While this is not mandatory, I think it'd be really useful in this commit to be able to see that the quotes were fixed only in `constants`.
- The [issue reference](http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html#issue-reference) is missing

**Comment by Asnelchristian** [comment]
:( ooh sorry, i missed that, 
THANKS @underyx :)

**Comment by underyx** [comment]
@Asnelchristian no problem 💃 

>uhm... i you meant use " in 2. right

Nope, those rules were taken straight from the [relevant issue's discussion](https://github.com/coala-analyzer/coala/issues/2634#issuecomment-240850799).

**Comment by beatrix-bodo** [comment]
Sorry, I'll change the message @underyx, thanks for the link!

**Comment by sils1297** [comment]
@beatrix-bodo you need a rebase but it looks good :)

**Comment by sils1297** [comment]
Hi,

it looks like your PR is out of date and needs a rebase. [This page](http://coala.readthedocs.org/en/latest/Users/Tutorials/Git_Help.html) may help you to get started on this. (*Do not press the update branch button. It's evil.*)

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix it up for you - just tell us :).

Ping us on [our gitter channel](https://gitter.im/coala-analyzer/coala) if you need help!

**Comment by sils1297** [comment]
ack fa87849

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2726/commits/bfd820adc1dce54ce5997c723a89deedee81dfb1

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
Hey, this is your first contribution, right? Congrats and welcome to the coalaians! :)

Rultor will now automatically release your changes as a prerelease so users can experience the goodness of your changes right now.

See also https://github.com/coala-analyzer/coala/wiki/coala-Steam-Offer btw.

**Comment by beatrix-bodo** [comment]
Yes, it is. Thank you! :)

**Pull request merged**
