### PR TITLE
CachingUtilities: Fix typo nonexist[a->e]nt

### PR DESCRIPTION
**Pull request by pasta-driven**
Fix https://github.com/coala-analyzer/coala/issues/2483

### CODE REVIEW

**Comment by Asnelchristian** [comment]
needs a rebase :) 
git remote add upstream https://github.com/coala-analyzer/coala.git
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
git push --force

**Comment by Asnelchristian** [comment]
may be ``Change `nonexistant` -> `nonexistent` `` for the commit short log  
you can use  this coala.readthedocs.io/en/latest/Getting_Involved/Writing_Good_Commits.html as reference :) 

btw the commit looks good :) :+1:

**Comment by Udayan12167** [comment]
ack b0527ba

**Comment by Asnelchristian** [comment]
@rultor merge

**Pull request merged**
