### PR TITLE
Brackets [] removed from around maintainer names

### PR DESCRIPTION
**Pull request by ravinimmi**

### CODE REVIEW

**Comment by sils1297** [comment]
Hi and welcome,

I've invited you to our team, you can accept that at github.com/coala-analyzer . I'll do a review now, don't be scared, it's very usual that commits need a bit of work until they get accepted.

**Comment by sils1297** [comment]
Pushing the update branch button is never good with our workflow :) but we can't disable it sadly.

**Comment by sils1297** [comment]
hey you also have no link to an issue, so I can't assign you

**Comment by ravinimmi** [comment]
@sils1297  Hi thanks for your support. I guess I was too eager to raise this PR and made a mess. So I am closing this PR and will raise a good clean PR after reading about getting started document.

**Comment by sils1297** [comment]
hey, it's usual that a PR needs work! That applies to all PRs and is totally normal.

**Pull request closed without merging**
