### PR TITLE
First commit

### PR DESCRIPTION
**Pull request by swatilodha**
coala-analyzer/coala#1780 
The link is now on the next line.

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
Awful commit message. Please check http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html and learn how to write a good commit message, we have some rules, use git commit --amend to modify the message

**Comment by Adrianzatreanu** [comment]
Also, why did you modify contributing.md ? this wasnt asked in the issue :)

**Comment by swatilodha** [comment]
Do i need to create a pull request again?

**Comment by Adrianzatreanu** [comment]
No, if you edit using git commit --amend and push again on the same branch, your PR will get updated automatically.

**Comment by swatilodha** [comment]
When I used git commit --amend , the message i type isn't saved. Help?

**Comment by Adrianzatreanu** [comment]
Are you on the same branch?

**Comment by Adrianzatreanu** [comment]
So what you have to do is, type git commit --amend, type a message and then press `esc` to be in command mode and type `:wq` , which is the default save command for VIM. then push it again

**Comment by swatilodha** [comment]
:wq is not a command in "Konsole".
And when I began from the scratch i.e. cloning again, the issue was already fixed. Did you merge it?

**Pull request closed without merging**
