### PR TITLE
setup.py: Normalise license format

### PR DESCRIPTION
**Pull request by nishant-mor**
Fixed: https://github.com/coala-analyzer/coala/issues/1320

### CODE REVIEW

**Comment by sils1297** [comment]
`Fixed:` usually without colon and `Fixes`

**Comment by nishant-mor** [comment]
@sils1297 why ci/circleci failing?

**Comment by sils1297** [comment]
@nishant-mor just run `coala` on your code, it should show you some issue(s) you need to adress

**Comment by sils1297** [comment]
```
Project wide:
|    | [NORMAL] GitCommitBear:
|    | No newline between shortlog and body at HEAD.
```

there you go, your commit message lacks a newline after the first line ;)

**Comment by sils1297** [comment]
included in https://github.com/coala-analyzer/coala/pull/1321 for simpler merge to avoid further rebases

**Pull request closed without merging**
