### PR TITLE
Update OpenEditorAction.py better success message

### PR DESCRIPTION
**Pull request by madminions**

### CODE REVIEW

**Comment by sils1297** [comment]
is this associated to any issue?

**Comment by madminions** [comment]
#1474

**Comment by sils1297** [comment]
@madminions can you accept the invitation to our org?

**Comment by madminions** [comment]
Yes. But how to do that?

**Comment by sils1297** [comment]
on github.com/coala-analyzer I think

**Comment by AbdealiJK** [comment]
@madminions this is really really close to getting merged. As soon as you can modify the commit message and rebase, we'd be able to push it

**Comment by sils1297** [comment]
I assume https://github.com/coala-analyzer/coala/pull/1542 supersedes this

**Pull request closed without merging**
