### PR TITLE
Linter_Bears.rst: Fix grammatic mistake

### PR DESCRIPTION
**Pull request by lonewolf07**
Fixes https://github.com/coala-analyzer/coala/issues/1562

### CODE REVIEW

**Comment by sils1297** [comment]
ack f64a00b, first accepted commit?

**Comment by sils1297** [comment]
Hey, apparently travis hasn't picked up your commit which sucks but we can't do anything about it. The only solution is for you to amend your commit (with the same message, don't change anything) and push force it up again just to trick GitHub into sending the webhooks again. Sorry :/

**Comment by sils1297** [comment]
ack 8be185c

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@lonewolf07 congrats! Feel free to take difficulty/low or higher now. The newcomer stuff is just to learn the workflow and we have a limited amount of newcomer issues.

**Comment by lonewolf07** [comment]
@sils1297 Thanks! Yeah, I will try!

**Pull request merged**
