### PR TITLE
Makman2/doc format bear6

### PR DESCRIPTION
**Pull request by Makman2**
It's done...

### CODE REVIEW

**Comment by sils1297** [comment]
@Makman2 what's up with the coverage?

**Comment by Makman2** [comment]
@sils1297 oh damn I need to make more tests for `extract_documentation`...

**Comment by sils1297** [comment]
@Makman2 you working on the coverage?

**Comment by Makman2** [comment]
@sils1297 yes, but you could anyway review the first 4 commits

**Comment by Makman2** [comment]
coverage fixed

**Comment by sils1297** [comment]
@Makman2 awaiting your rework here

**Comment by Makman2** [comment]
#1138 takes over

**Pull request closed without merging**
