### PR TITLE
install.rst : Fix typo decent -> recent

### PR DESCRIPTION
**Pull request by sudoankit**
Fixed a small typo. Changed "decent" to "recent".

Fixes https://github.com/coala-analyzer/coala/issues/1767

### CODE REVIEW

**Comment by SanketDG** [comment]
@sudoankit you will need to squash your commits.

**Comment by sudoankit** [comment]
Sorry for the merging of master branch.  I am squashing that.

**Comment by AbdealiJK** [comment]
ack 6e60a8d

**Comment by sudoankit** [comment]
I am closing it, and making one more, for both the issues together.

**Pull request closed without merging**
