### PR TITLE
setup: Pull in long description from readme

### PR DESCRIPTION
**Pull request by sils1297**
Fixes https://github.com/coala-analyzer/coala/issues/1843

### CODE REVIEW

**Comment by sils1297** [comment]
ack
01c3fdf ConsoleInteraction: Polish up docs
b2e6b17 ConsoleInteraction: Catch bullet unicode error

**Comment by sudheesh001** [comment]
ack 3600f03

**Comment by sils1297** [comment]
ack 01c3fdf b2e6b17 - I need to teach gitmate to tolerate newlines, doing that now

**Comment by sudheesh001** [comment]
@rultor merge

**Comment by SanketDG** [comment]
@rultor merge

**Comment by sudheesh001** [comment]
@rultor merge

**Pull request merged**
