### PR TITLE
Install.rst: Fix typo at line 19

### PR DESCRIPTION
**Pull request by AdeshAtole**
Fixes https://github.com/coala-analyzer/coala/issues/1692

### CODE REVIEW

**Comment by sils1297** [comment]
hey, please do a rebase (maybe after I've merged the other PR). Also I'd kindly ask you to remove the second commit as this is already your second newcomer issue - we have not enough newcomer issues and this cannot afford that one person solves a lot newcomer issues. You're perfectly ready to go to difficulty/low if you've done one or max. two newcomer issues.

**Comment by sils1297** [comment]
unack 10944de but almost ready :)

**Comment by Makman2** [comment]
ack a4ecd07
though you need again a rebase :D

**Comment by sils1297** [comment]
reack 47e9018

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
