### PR TITLE
Rename IndentBear to GNUIndentBear

### PR DESCRIPTION
**Pull request by MayankVachher**
Fixes https://github.com/coala-analyzer/coala-bears/issues/120

### CODE REVIEW

**Comment by AbdealiJK** [comment]
Your commit seems alright.
Your commit's shortlog seems to need work.

Have you read coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html ?
It talks about the shortlog having a "tag" and a semicolon `:`
Could you add that ?

**Comment by MayankVachher** [comment]
@AbdealiJK Sure.

**Comment by AbdealiJK** [comment]
unack 53a3f3f

**Comment by sils1297** [comment]
https://github.com/coala-analyzer/coala/pull/1903/commits/75f33e86b8a03652cdbd6dae917ed56b1e323924 looks also good, ack

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
