### PR TITLE
setup: Stop build_manpage in Windows

### PR DESCRIPTION
**Pull request by souravsingh**
When Installing Coala for windows, the setup builds man pages,which are not needed for Windows.This change allows for detection of platform and running the man page build command accordingly. Fixes https://github.com/coala-analyzer/coala/issues/1694

### CODE REVIEW

**Comment by souravsingh** [comment]
Can anyone review the PR?

**Comment by tushar-rishav** [comment]
unack 74be8a5

**Comment by sils1297** [comment]
hey, you know that if you just push to your branch the PR will automatically resynchronize? No need to create new PRs always...

**Comment by sils1297** [comment]
and we're really helping you if you drop by at gitter ;)

**Pull request closed without merging**
