### PR TITLE
Diff: Increase `line_nr_end` in `delete_lines`

### PR DESCRIPTION
**Pull request by kmo1**
Closes https://github.com/coala-analyzer/coala/issues/2641

### CODE REVIEW

**Comment by SanketDG** [comment]
ack ea6f3c

**Comment by SanketDG** [comment]
ack ea6fa3c

**Comment by SanketDG** [comment]
@rultor merge

**Comment by SanketDG** [comment]
@kmo1 can you close https://github.com/coala-analyzer/coala/pull/2642 if its not needed anymore?

**Comment by Asnelchristian** [comment]
you need a rebase seemingly

**Pull request merged**
