### PR TITLE
rename param in docstring

### PR DESCRIPTION
**Pull request by netman92**

### CODE REVIEW

**Comment by sims1253** [comment]
The fix looks good but your commit message needs a touch up. Please take a look at our guidelines and add/change what is needed:
http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html

Thank you for the contribution!

By the way, to edit the last commit, use git commit --amend, edit it, save it, and then push again with the extra flag --force :)

**Comment by netman92** [comment]
@sims1253 Thx for comment :)

**Comment by sims1253** [comment]
ack d2ec803

**Comment by sims1253** [comment]
I just learned that we use Closes for typos and not Fixes :)
could you change that?

**Comment by sims1253** [comment]
unack d2ec803

**Comment by sils1297** [comment]
https://github.com/coala-analyzer/coala/pull/2669/commits/94ad34b82b8e56e10de35f03eb16b47936cb80ab is ready

**Comment by sims1253** [comment]
Closed as it got cherrypicked in https://github.com/coala-analyzer/coala/pull/2671

**Pull request closed without merging**
