### PR TITLE
Result.py: Changes :param origin: description

### PR DESCRIPTION
**Pull request by kmo1**
Closes https://github.com/coala-analyzer/coala/issues/2604

### CODE REVIEW

**Comment by sils1297** [comment]
Hey,

I feel like you've read our documentation pretty well already! (Above average for sure, even using the closes correctly :+1: )

`Changes` isn't imperative present tense though, changig that word to `Change` would do the job. I know, we're nitpicking a lot - essentially the more you contribute the better your messages will get and also the less we will care assuming the basics are ok.

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix up the message for you - just tell us :).

Cheers!

**Comment by sils1297** [comment]
https://github.com/coala-analyzer/coala/pull/2621/commits/3f5a5a4051cf8bf8b83aa8835dff137e944c1d38 needs work

**Comment by kmo1** [comment]
thanks for the feedback! I just pushed the update

**Comment by hypothesist** [comment]
Hey @kmo1

IMO the two colons surrounding `param origin` can be dropped; they're kinda redundant. But otherwise, this looks good to me :+1:

Once you make the change, I'll ack it (which is short for acknowledge) and then we can merge!

**Comment by hypothesist** [comment]
unack https://github.com/coala-analyzer/coala/pull/2621/commits/18920e27096948a9beba3ae8ca568ea535e29ddd

**Comment by hypothesist** [comment]
@kmo1 This also needs a rebase. To do this, do

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

and then

```
git pull --rebase upstream master
```

Also drop by at our [Gitter channel](https://gitter.im/coala-analyzer/coala) and say hello! :) You can ask to get this issue assigned to you (this helps prevent two people working on the same issue unknowingly). Or any questions you might have ;)

**Comment by kmo1** [comment]
Thanks for all of the guidance on this. This is my first pull request so if you see any other changes I should make please let me know

**Comment by sils1297** [comment]
https://github.com/coala-analyzer/coala/pull/2621/commits/ed546ff2b659f7679b43e7ef5f5e70ab526891c6 is ready

**Comment by sils1297** [comment]
Hey, this is your first contribution, right? Congrats and welcome to the coalaians! :)

Rultor will now automatically release your changes as a prerelease so users can experience the goodness of your changes right now.

See also https://github.com/coala-analyzer/coala/wiki/coala-Steam-Offer btw.

Welcome and cheers!

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
