### PR TITLE
coala_delete_orig: Remove unneeded ellipsis

### LINKED ISSUE #1514: coala_delete_orig: Modify message
Modify message about `Couldn't delete... <filename>`

@sils1297 please suggest a better message.

### PR DESCRIPTION
**Pull request by yland**
Modify message about Couldn't delete...

Fixes #1514

### CODE REVIEW

**Comment by sils1297** [comment]
unack 545f8b8 , it needs some work on the commit message. We have guidelines for commit messages at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages , so the `Fixes <url>` needs to go down into the body and you'd rather do `Remove unneeded ellipsis` instead of `Modify message` as it gives a better information.

Almost ready, see forward to merging this, sorry the review took so long.

**Comment by sils1297** [comment]
hey @yland need some help? You know where you find us :)

**Comment by yland** [comment]
Hello @sils1297 . Sorry I took so long to rectify this issue. I hope my present changes is what is required.

**Comment by sils1297** [comment]
please read http://coala.readthedocs.org/en/latest/Users/Tutorials/Git_Help.html#follow-up to correct your issue als a rebase (as described there too) is needed

**Comment by sils1297** [comment]
you can change the title of the PR as much as you want, we don't really care about that really. We care about what's in git, not so much in GitHub.

**Comment by SanketDG** [comment]
@yland You will have to squash your commits. See here: https://asciinema.org/a/11269

**Comment by yland** [comment]
@SanketDG I have squashed the commits, following the instructions in the link you provided.

**Comment by sils1297** [comment]
merging this despite the `Fixes` note being wrong but it's just easier to take this noe.

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@yland for future reference you don't want to write `Fixes issue #1234` but only `Fixes <full url>`, important fact is that there's only `FIxes` so github recognizes that and auto closes the issue and secondly we want the full URLs so they can be viewed in the git log and outside github in general.

**Comment by yland** [comment]
Thanks for the patience and directives, I would do well to remember all I have learnt next time.

**Pull request merged**
