### PR TITLE
Newcomers.rst: Add rebasing steps

### PR DESCRIPTION
**Pull request by srisankethu**
Fixes https://github.com/coala-analyzer/coala/issues/1776

### CODE REVIEW

**Comment by SanketDG** [comment]
https://github.com/coala-analyzer/coala/pull/1775 is doing the same thing. This will result in duplication. Do we want this?

Edit: A lot of information is repeated from Git Help, I see.

**Comment by SanketDG** [comment]
@srisankethu can you run `coala` over your code?

**Comment by srisankethu** [comment]
@SanketDG I have missed the spaceinconsistency thing.I have already updated my PR

**Comment by Makman2** [comment]
@SanketDG yeah the issue is similar, though this one shall be a quick-reference for the newcomers so they know what to do when we say "please rebase". Often you don't read the complete explanations on Git_Help.rst (at least you only read over quickly).

**Comment by srisankethu** [comment]
@Makman2 Yes Git_Help asks you to rebase but does not specify how to

**Comment by srisankethu** [comment]
@Makman2 Why is Scritinizer failing? I have got no idea why?

**Comment by Makman2** [comment]
random error, I restarted the inspection^^

**Comment by AbdealiJK** [comment]
I think this PR is confusing ...
We use a different system that `Git_Help` and `origin` in both places mean different thing.

Also the only additional part this PR has is the `git pull -f` (which is very important). I think it's better to just mention in  https://github.com/arafsheikh/coala/commit/7cea6b9e9fca9a55534a10b8981c2f01ddcdbb89 that the user needs to force push after doing a sync.

I think this is more confusing because the conventions used in both the docs are different, and it just make sense to keep all the git commands in one place

**Comment by srisankethu** [comment]
@AbdealiJK So do you want me close this PR(and issue)

**Comment by AbdealiJK** [comment]
Well, that is my opinion.
I'll let others weigh in and if overall people think it's still needed we
can go ahead.

**Comment by srisankethu** [comment]
@AbdealiJK What do you think about adding this to Git_Help and adding a link to Git_Help if rebase is needed.

**Comment by srisankethu** [comment]
@AbdealiJK What do you think about adding this to Git_Help and adding a link to Git_Help if rebase is needed.

**Comment by AbdealiJK** [comment]
@srisankethu I favour that.
SO, it'd be like in the Newcomer.rst we write:
```
Ff asked to doa  rebase please check the "abc" section in Git_Help etc etc
```
or something

And it's link to the content being written in https://github.com/coala-analyzer/coala/pull/1775

**Comment by srisankethu** [comment]
@AbdealiJK Yes Yes!

**Comment by sils1297** [comment]
https://github.com/coala-analyzer/coala/pull/1775 contains a better approach to solve this problem and we should take it. I'm really sorry, those issues should have been detected as duplicates earlier.

**Comment by srisankethu** [comment]
@sils1297 May be this one too -> https://github.com/coala-analyzer/coala/issues/1789

**Pull request closed without merging**
