### PR TITLE
Processing: Provide line & column in ignore ranges

### PR DESCRIPTION
**Pull request by WJCode**
Fixes https://github.com/coala-analyzer/coala/issues/1232

### CODE REVIEW

**Comment by WJCode** [comment]
I had assumed that the line containing "stop ignoring" need not be searched.
Ah ok. There could be code right before the comment character? I'll fix that

**Comment by sils1297** [comment]
yeah maybe the analytics even affects the comment itself, the whole line should be ignored IMO

**Comment by WJCode** [comment]
Indeed it does. Including the entire "stop ignoring" line.

I'll also try to come up with a suitable test case for the previous behaviour.

**Comment by sils1297** [comment]
ack ab87a3d3b7d1

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
