### PR TITLE
Update action everytime

### PR DESCRIPTION
**Pull request by srisankethu**
Fixes https://github.com/coala-analyzer/coala/issues/1825

### CODE REVIEW

**Comment by sils1297** [comment]
@srisankethu as per discussion on gitter this solution isn't really applicable

**Comment by srisankethu** [comment]
@sils1297 So can i added a success parameter to action and check if succeeded then don't change parameter...something like that ?

**Comment by sils1297** [comment]
The success information is already there somewhere, at least somewhere we print a success message and otherwise the exception info

**Comment by srisankethu** [comment]
@sils1297 Ok ! I will try to use that !

**Pull request closed without merging**
