### PR TITLE
Updated documentation under the SourceRange constructor

### PR DESCRIPTION
**Pull request by tltuan**

### CODE REVIEW

**Comment by hypothesist** [comment]
Hey @tltuan 

We have a few rules (community standards) on commit messages. You can find more information over here: http://coala.readthedocs.io/en/latest/Getting_Involved/Writing_Good_Commits.html

- Imperative present tense
- Shortlog should be <= 50 chars

Also you may want to run `coala` on the source code itself to find out possible issues (like for instance, here, you have a line > 80 chars).

**Comment by sils1297** [comment]
Hi,

the build failure is a nondeterministic one so that'll pass next time.

Do you know how to rebase? [This page](http://coala.readthedocs.org/en/latest/Users/Tutorials/Git_Help.html) may help you to get started on this. (*Do not press the update branch button. It's evil.*)

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

Ping us on [our gitter channel](https://gitter.im/coala-analyzer/coala) if you need help!

**Comment by Makman2** [comment]
btw do you mind to set the commit author to your actual github ID? then it's easier to see who has made a commit :) (many Administrators exist out there :P)

**Comment by sils1297** [comment]
Hi,

do you need help figuring this out? We're all happy to help you on [our gitter channel](https://gitter.im/coala-analyzer/coala), just drop by and ask us anything :)

**Comment by Makman2** [comment]
ping @tltuan

**Comment by Adrianzatreanu** [comment]
closing due to long inactivity.

**Pull request closed without merging**
