### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by cw1**
Rearranged paragraphs for a better reading fluency and a more logical order.

### CODE REVIEW

**Comment by SanketDG** [comment]
@cw1 You might want to take a look at
http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html

**Comment by Adrianzatreanu** [comment]
Hey, @cw1 are you still working on this? Feel free to ping us on https://gitter.im/coala-analyzer/coala if you ever need some help

**Comment by Adrianzatreanu** [comment]
closing as per gitter discussion with @sils1297

**Comment by SanketDG** [comment]
cherry picked in https://github.com/coala-analyzer/coala/pull/1943

**Pull request closed without merging**
