### PR TITLE
Linter_Bears:Fixed grammatic mistake

### PR DESCRIPTION
**Pull request by lonewolf07**
Fixes https://github.com/coala-analyzer/coala/issues/1562

### CODE REVIEW

**Comment by Redridge** [comment]
Hi @lonewolf07 and welcome. You did fix the bug but here at coala we have some rules about the commit messages http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html

In this case the verb in the commit message should be at imperative tense i.e. Fixed -> Fix
In order to do this in the simplest way possible you can do
```
git commit --amend
git push origin <yourbranch> --force
```
without changing anything
also @sils1297 should send you an invitation(if not already done) and you should accepted in order to get assigned

**Comment by sils1297** [comment]
he's assigned

**Comment by sils1297** [comment]
cancelling circleci because build queues are full and this needs work

**Comment by sils1297** [comment]
hey, need some help? You know where to find us :)

**Comment by sils1297** [comment]
apparently https://github.com/coala-analyzer/coala/pull/1607 supersedes this, please close old PRs on your own! It's hard for us to keep a central overview, we use git to be decentral.

**Comment by lonewolf07** [comment]
I am busy with exams , will get back to within 2 days, If you could manage! :)

**Comment by sils1297** [comment]
sure :)

**Pull request closed without merging**
