### PR TITLE
coala_ci: Print section names along with results

### PR DESCRIPTION
**Pull request by ankitaggarwal011**
Results are already printed in coala-ci, printing the section names as
well would be neat. Passing the print_section_beginning flag with
run_coala does the job.

Fixes https://github.com/coala-analyzer/coala/issues/1413

### CODE REVIEW

**Comment by ankitaggarwal011** [comment]
@sils1297, please review this. Thanks.

**Comment by sils1297** [comment]
@AbdealiJK please look at it

**Comment by sils1297** [comment]
No time right now, sorry, @AbdealiJK is a fine reviewer :)

**Comment by AbdealiJK** [comment]
ack 27e4674

**Comment by AbdealiJK** [comment]
But you need to rebase, The rebase will fix the appveyor issue

**Comment by sils1297** [comment]
do not rebase, I'll take care of this, there are other merges in the queue we'll just cherry pick them together

**Comment by AbdealiJK** [comment]
Moved to https://github.com/coala-analyzer/coala/pull/1507

**Comment by ankitaggarwal011** [comment]
Has this been merged separately or there are any problems with this commit. Let me know. Thanks.

**Comment by AbdealiJK** [comment]
It's been merged

**Comment by sils1297** [comment]
@ankitaggarwal011 you remember we are doig this rebase thing so we don't care what is merged in which PR, only commits are important. So when there are a lot of merges at the same time we bundle them in one PR to ease the load on our build stuff. Your stuff was part of #1507

**Comment by ankitaggarwal011** [comment]
I understand. Thanks for the information.

**Pull request closed without merging**
