### PR TITLE
Added constants outside the class

### PR DESCRIPTION
**Pull request by kaushikmit**
As per Issue #917  , I have actually moved the constants outside the class.

### CODE REVIEW

**Comment by GitCop** [comment]
The commit message

 * Commit: 37fe772b0643b5fc55f83d46ca52c96da3ef7636
  * Commits must be in the following format: **%{scope}: %{description}**

Guidelines are available at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
The commit message

 * Commit: 1798741b4c68268f8964baa746c260e0960844dc
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages

---
This message was auto-generated by https://gitcop.com

**Comment by sils1297** [comment]
hey please look at the scrutinizer report, you seem to have forgotten one of the imports: https://scrutinizer-ci.com/g/coala-analyzer/coala/inspections/a7b8d585-5236-4f06-ae4b-a5c0d249aaa2/issues/files/coalib/coala_dbus.py?status=new&orderField=path&order=asc&honorSelectedPaths=0

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
