### PR TITLE
Decorators.py: Move to an own package

### PR DESCRIPTION
**Pull request by Adrianzatreanu**
This modifies the imports to the new package
named coala_decorators.

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
I need to do a new release and rename the package first, from ``coala-decorators`` to ``coala_decorators``, will do this soon, marking WIP meanwhile.

**Comment by tushar-rishav** [comment]
@Adrianzatreanu  LGTM. :+1:

**Comment by tushar-rishav** [comment]
ack 37946ac

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Pull request merged**
