### PR TITLE
README: Change website link

### PR DESCRIPTION
**Pull request by manthansharma**
Change website link form http://coala-analyzer.org/ to http://coala.io/

Closes https://github.com/coala-analyzer/coala/issues/2741

### CODE REVIEW

**Comment by sils1297** [comment]
Hey,

we use some bug prediction in coala which relies on the `Fixes` keyword in commit messages. To get good results from that we need to use `Closes` for normal issues instead of `Fixes` which should only be used for real bugs. (See also [the commit message docs](http://coala.io/commit).)

Please also omit the colon after the Closes keyword so GitHub picks it up correctly.

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix up the message for you - just tell us :).

Cheers!

**Comment by manthansharma** [comment]
@sils1297 changed the message acc. to given guidelines

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2746/commits/b5c44e2e7b7a3f91ffe414f7cbc4e41951d30058

**Comment by sils1297** [comment]
Hey, this is your first contribution, right? Congrats and welcome to the coalaians! :)

Rultor will now automatically release your changes as a prerelease so users can experience the goodness of your changes right now.

See also https://github.com/coala-analyzer/coala/wiki/coala-Steam-Offer btw.

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
