### PR TITLE
Minor tweaks in circleci

### PR DESCRIPTION
**Pull request by AbdealiJK**

### CODE REVIEW

**Comment by sils1297** [comment]
@AbdealiJK https://travis-ci.org/coala-analyzer/coala/builds/109308735 needs attention

**Comment by AbdealiJK** [comment]
reack
af31b00 Tagging: Allow tag to be "None"
bebde64 coala_main: Simplify code
3b3441d coala_main: Use simplify_section_result()
57b65f4 coala_main: Use collect_all_bears_from_sections()
d02cd9c Collectors: Add collect_all_bears_from_sections()
fa873e5 coala_main: Move autoapply to gather_configs()
c08d488 ProcessingTest: Use kwarg for gather_configuration
c32f5dd Tagging: Add get_tags_dir()
f0e2784 Tagging: Add log_printer to all functions
8785b14 appveyor: Add nodejs modules
af52fc8 appveyor: Cache appveyor dependencies
9b2edf6 PyLintBear: Add new argument rcfile
aeb4467 BearRunning: Capture OSError and KeyboardInterrupt
3434a48 circleci: Use 3.5 as Node 0
791cd31 circleci: Use stable pyenv version
40b9a1f circleci: Clean up NVM dependencies

**Comment by AbdealiJK** [comment]
reack

**Comment by sils1297** [comment]
reack 6927a6ae2b32a140d6b9c81320e5fa4679dfc751
d937a81e739dd05a36229acda36eda81c2f9aab6
f2274045f152081da6659e6908853b895a7e7c35
8c0b6986865a7d7c4393ed97606d1ae3fa3d787a
3259212e286fc5a31b053e2bb58fe235836df49b
0c8fcfcd2db0266ebb09d8ea2a28cb85358d5f06
c00e639226cebf1ab8cc764e6790325e098cbd2f
19c76e62d6001361e195f396784d2a794d666f88
9d46f4f1b5665b5d33839d52578e015485f13d0d
9de2ba0d7c7ee515af4ea044c08c419f1ef43755
1c4f19b62961a48daf4a63e9fa2574255bfdc0d9
dbc7118a4681fc0f7c6cd1217e136fcf266de597
ce7c9f8853ef6fb97d9bd3211dec691e6c58a2e5
4fe5c49d240da55ca162257cd938dac938acecf9
db8680aa423e84e307658d2e9f05d5493067c42e
557a3c0abd69b257e310dcd9421669261410f548
759fe8ac1b2929f3ce480b0da41342411bd8ab5e
7dbe47ca59e46348fd85b3b8f3d09852d0ddc598
8900cc9b3625936f2e52c70ccbca1423a1654e30

**Comment by sils1297** [comment]
reack 6927a6ae2b32a140d6b9c81320e5fa4679dfc751 d937a81e739dd05a36229acda36eda81c2f9aab6 f2274045f152081da6659e6908853b895a7e7c35 8c0b6986865a7d7c4393ed97606d1ae3fa3d787a 3259212e286fc5a31b053e2bb58fe235836df49b 0c8fcfcd2db0266ebb09d8ea2a28cb85358d5f06 c00e639226cebf1ab8cc764e6790325e098cbd2f 19c76e62d6001361e195f396784d2a794d666f88 9d46f4f1b5665b5d33839d52578e015485f13d0d 9de2ba0d7c7ee515af4ea044c08c419f1ef43755 1c4f19b62961a48daf4a63e9fa2574255bfdc0d9 dbc7118a4681fc0f7c6cd1217e136fcf266de597 ce7c9f8853ef6fb97d9bd3211dec691e6c58a2e5 4fe5c49d240da55ca162257cd938dac938acecf9 db8680aa423e84e307658d2e9f05d5493067c42e 557a3c0abd69b257e310dcd9421669261410f548 759fe8ac1b2929f3ce480b0da41342411bd8ab5e 7dbe47ca59e46348fd85b3b8f3d09852d0ddc598 8900cc9b3625936f2e52c70ccbca1423a1654e30

**Comment by sils1297** [comment]
reack 6927a6a d937a81 f227404 8c0b698 3259212 0c8fcfc c00e639 19c76e6 9d46f4f 9de2ba0 1c4f19b dbc7118 ce7c9f8 4fe5c49 db8680a 557a3c0 759fe8a 7dbe47c 8900cc9

**Comment by AbdealiJK** [comment]
@rultor merge

**Pull request merged**
