### PR TITLE
RELEASE NOTES : Fix incorrect links

### LINKED ISSUE #1383: RELEASE_NOTES.rst: fix incorrect links
Some links were not converted correctly during our move to sphinx/RST documentation. These two links in `RELEASE_NOTES.rst` need to be updated as follows:

Current | Change to
--------------------------------------------------------------------------|----------------------------------------------------------
http://coala.readthedocs.org/en/latest/Users/Exit\_Codes/ | http://coala.readthedocs.org/en/latest/Users/Exit_Codes.html
http://coala.readthedocs.org/en/latest/Users/Glob\_Patterns/ | http://coala.readthedocs.org/en/latest/Users/Glob_Patterns.html

### PR DESCRIPTION
**Pull request by srisankethu**
Fixes #1383

### CODE REVIEW

**Comment by sils1297** [comment]
@srisankethu I've noticed you're reforking coala, that is just wrong and you loose the review comments by deleting your fork. Just checkout your branch locally, do the edits and force push it up, you're making your life way harder than it could be :(

**Comment by srisankethu** [comment]
@sils1297 Can you tell me how can I add a body to my commit? For example message should read
tests/bearlib : Fix incorrect link
Fixes #someissue

**Comment by sils1297** [comment]
`git commit --amend`

**Comment by srisankethu** [comment]
@sils1297 How to write the message itself
I mean't how to add a body to the message

**Comment by sils1297** [comment]
@srisankethu http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages

**Pull request closed without merging**
