### PR TITLE
RELEASE_NOTES: Fix incorrect links

### PR DESCRIPTION
**Pull request by srisankethu**
Fixes https://github.com/coala-analyzer/coala/issues/1383

### CODE REVIEW

**Comment by Makman2** [comment]
@srisankethu I've heard on the gitter channel that you're not really willing to work on your fork like we suggest (via doing a rebase instead of reforking everytime). Please look into the gitter channel where @tushar-rishav tried to help you. Also we don't have unlimited newcomer issues, please chose after this one an issue with `difficulty/low`, we won't merge newcomer issues from you any more after this one^^
Really, please speak with us, we won't bite^^

**Comment by sils1297** [comment]
FYI I'm just merging https://github.com/coala-analyzer/coala/pull/1459 which means this PR will need a rebase.

**Comment by srisankethu** [comment]
@Makman2 It's not that i am not willing to do it the way they asked me to do but I learning ! It's my first time that I am locally contributing and i am not aware of other commands than git pull, git push,git add,git commit.

**Comment by Makman2** [comment]
@srisankethu Hmm, anyway you need to get familiar with `git rebase` here^^ Since you already are eager to learn, that shouldn't be too hard for you :)
So helping you a bit out here:
```
git fetch upstream/master
git rebase upstream/master
git push -f
```
That should do the trick already :) A rebase does nothing more than reapplying your commits onto the given branch/commit (in this case `upstream/master`). Be sure to set the upstream branch like described here: https://help.github.com/articles/configuring-a-remote-for-a-fork/

When you rebased your branch and pushed-force over it, the merge commit should vanish also :+1:

Once you get the hang of it it's no matter for you any more :)

**Comment by srisankethu** [comment]
@Makman2 I have done a merge as I have got a 'Update Branch' icon on my PR so i just clicked on it.It made a merge commit.Is it ok? if not how shall I undo?

**Comment by Makman2** [comment]
@srisankethu sadly not :/ github doesn't allow to do so called fast-forward merges without merge commits. you need to to it manually over command line.
For the rebase the merge commit is no problem, it will automatically remove it since it detects that the merge-changes inside this commit are from top of `upstream/master` and after resolving the diffs the commit is not needed any more :D :+1:

**Comment by srisankethu** [comment]
before doing git fetch upstream I guess i need to do a git remote add upstream <URL>.So this URL should be that of my forked repo or that of coala

**Comment by Makman2** [comment]
@srisankethu that of coala :+1:

**Comment by srisankethu** [comment]
@Makman2 So I have followed this process
1. git remote add upstream https://github.com/coala-analyzer/coala.git
2.git fetch upstream
3.git rebase upstream/master
It seems to have worked but I don't see any changes in my PR

**Comment by Makman2** [comment]
@srisankethu did you `git push -f`?

**Comment by srisankethu** [comment]
@Makman2 Thanks..I didn't know people are this helpful..Great to see help from @Makman2 @sils1297 and @AbdealiJK

**Comment by Makman2** [comment]
@srisankethu That's likely for people being helpful...
Btw if you need help like now really drop by at gitter, I can't track the discussion better and react faster if you address me with `@Makman2`, since I get popups displayed :+1:

**Comment by srisankethu** [comment]
Okk

**Comment by Makman2** [comment]
ack 9fa2306

**Comment by Makman2** [comment]
@rultor merge

**Comment by Makman2** [comment]
@srisankethu alright, your PR is merged :D :v:

**Pull request merged**
