### PR TITLE
Makman2/search nested

### PR DESCRIPTION
**Pull request by Makman2**
The `nested_search_in_between()` function is on the road!

Also this PR adds two new tests for already existing functions.

### CODE REVIEW

**Comment by sils1297** [comment]
none of your shortlogs contain a verb

**Comment by sils1297** [comment]
also needs rebasing now

**Comment by Makman2** [comment]
About commit messages: How shall I change them?

**Comment by Makman2** [comment]
I think we should merge #613 first, even if that would mean to refactor the test like in #613.

**Comment by sils1297** [comment]
needs rebase and conflict resolutino

**Comment by sils1297** [comment]
@Makman2 hey I think you need a rebase

**Pull request merged**
