### PR TITLE
bears: Add HTMLLint bear

### PR DESCRIPTION
**Pull request by Redridge**
Fixes https://github.com/coala-analyzer/coala/issues/1478

Added a bear that user `html-linter`
Added a test for that bear

### CODE REVIEW

**Comment by sils1297** [comment]
unack c939530 though it's already almost ready and I'm very positively surprised about that! Can't wait to get this :)

**Comment by Redridge** [comment]
like this?

**Comment by sils1297** [comment]
ack 629f56b

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
the coverage fail is a codecov bug I think, coverage goes up here.

**Pull request merged**
