### PR TITLE
requirements: Use backwards compatible notation

### PR DESCRIPTION
**Pull request by sils1297**
This will also work on debian hopefully.

### CODE REVIEW

**Comment by sils1297** [comment]
part of fixing https://github.com/coala-analyzer/coala/issues/1852

**Comment by fneu** [comment]
ack https://github.com/coala-analyzer/coala/commit/e599d817e883eb53a6071790022c6e75c3a17924

**Comment by fneu** [comment]
> All is well! :) (0 Problems solved)

That's a weird message btw. Since you kinda solved a Problem with this Commit/pr ;)

**Comment by fneu** [comment]
@rultor merge

**Pull request merged**
