### PR TITLE
Fixes issue #1870

### PR DESCRIPTION
**Pull request by rresol**
Added documentation for console_printer in print_actions()

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
Also, we do not use past tense in the shortlog (title of the commit)

**Comment by Adrianzatreanu** [comment]
We also use an optional body in which we explain WHY we did that change and why it was needed.
And end the commit message with a ``Fixes <issue_url>``

**Comment by Adrianzatreanu** [comment]
newlines between header, body & fixes;

**Comment by Adrianzatreanu** [comment]
No, this is not how you do it. I explicitely asked you to use ``git commit --amend`` . You simply created a new commit instead of editing the last one. And you also included a merge commit in your PR. You will need to do a rebase to fix this, please read a git tutorial or something, i suggest try.github.io or http://coala.readthedocs.org/en/latest/Users/Tutorials/Git_Help.html , or google git rebasing;

**Comment by rresol** [comment]
I will look into it.

**Comment by AbdealiJK** [comment]
Can you use `ConsoleInteraction` instead of `output` ?
Also, you need a rebase.

**Comment by rresol** [comment]
okay! I will do that.

**Comment by AbdealiJK** [comment]
ready  03fb044

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
