### PR TITLE
.gitignore : update to reflect coala-bears repo

### PR DESCRIPTION
**Pull request by Adrianzatreanu**
Fixes:
Removed : coala.1, org.coala_analyzer.v1.service
as they were redundant
Modified coala.egg_info to be, more generally, *.egg-info.

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
Referencing https://github.com/coala-analyzer/coala-bears/issues/65

**Comment by tushar-rishav** [comment]
@Adrianzatreanu Almost done. Just need to amend the commit and add issue url after `Fixes`. Why not make that change and send a PR again? :D

**Comment by Adrianzatreanu** [comment]
Hopefully this is better :)

**Comment by Makman2** [comment]
The commit message needs slight changes :)
We don't put a space between the tag and the colon, and we usually write the first letter after the colon uppercase :)
--> `.gitignore: Update to reflect coala-bears repo`
But in this case I don't know if the message is quite appropriate, the idea behind the referenced issue was to copy the .gitignore more or less from coala to coala-bears, not vice-versa :D
At least the `Fixes: xxxx` is wrong^^

**Comment by Makman2** [comment]
unack  e2fcaee

**Comment by AbdealiJK** [comment]
What is happening here ? This PR should be for `coala-bears` not `coala`
The man page and service files get generated in this repo and so those lines in the gitignore are needed !

**Comment by AbdealiJK** [comment]
It seems you closed https://github.com/coala-analyzer/coala-bears/pull/87 and opened a new one in the wrong repo :D 
Issues in `coala-bears` should be solved in `coala-bears` and issues in `coala` need to be solved in `coala`

**Comment by Adrianzatreanu** [comment]
Yes, you are right, struggled a lot with those PRs to get them right in the past days that i opened them both in the same place. Its all my fault, sorry for the mess !

**Comment by AbdealiJK** [comment]
No issues :) ( I've created issues and PRs in the wrong repos by mistake too :P )

**Comment by Adrianzatreanu** [comment]
Ill make them right this time i hope :) creating this one again in a minute

**Pull request closed without merging**
