### PR TITLE
Fixes two newcomer issues

### PR DESCRIPTION
**Pull request by abhiroyg**
Please review.

### CODE REVIEW

**Comment by AbdealiJK** [comment]
@abhiroyg Hi, and welcome to coala.

We normally limit a person to solve 2 newcomer issues so that other newcomers have a change to et involved in coala too. So, can you remove one of these ?

Also, please ask to get assigned to an issue (you can comment on the issue) before solving it as it reduces double work. I've invited you to the coala org so I can assign them to you.

Take a look at newcomer guide:
 - http://coala.readthedocs.org/en/latest/Getting_Involved/Newcomers.html
And a git guide if you're new to git:
 - http://coala.readthedocs.org/en/latest/Users/Tutorials/Git_Help.html
and the commit style and code style guides:
 - http://coala.readthedocs.org/en/latest/Getting_Involved/Codestyle.html
 - http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html

**Comment by AbdealiJK** [comment]
@abhiroyg seems like you're having some trouble with git.
A reminder that these guides may be good for you:

Newcomer guide:

-    http://coala.readthedocs.org/en/latest/Getting_Involved/Newcomers.html

And a git guide if you're new to git:

-    http://coala.readthedocs.org/en/latest/Users/Tutorials/Git_Help.html

and the commit style and code style guides:
-    http://coala.readthedocs.org/en/latest/Getting_Involved/Codestyle.html
-    http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html


You can ping us at https://gitter.im/coala-analyzer/coala for help too :)

**Comment by AbdealiJK** [comment]
The last commit looks great !
The first one still needs to be changed

**Comment by AbdealiJK** [comment]
In the last commit too, you probably want to use:
`ConsoleInteraction: Remove unused arg tab_width`
as it's more descriptive

**Comment by abhiroyg** [comment]
Done! Tested using py.test in an virtual environment and ran ./coala without errors.

**Comment by AbdealiJK** [comment]
c5e2f58 and 17b63b5 are ready

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@abhiroyg this will automatically release your changes to the users as a prerelease btw :)

**Pull request merged**
