### PR TITLE
CLI: Add argument to group bears by languages

### PR DESCRIPTION
**Pull request by Uran198**

### CODE REVIEW

**Comment by Uran198** [comment]
d1547cc needs work. Low coverage.

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2086/commits/a97c2da055521b62576a57ef803cb1d14ad0728d#diff-e690c48863208d16808485e103164cd5R190

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2086/commits/279381c4e551ad4107fc24085dbbcc2e8ca24986

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@rultor stop

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2086/commits/fbe3430daa12ece17631e115e50bfa46e36f8b8c https://github.com/coala-analyzer/coala/pull/2086/commits/1307c914c371a25ef09e5aff720a08ec82bd5545

**Comment by sils1297** [comment]
coverage is full

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
