### PR TITLE
PyLintBear.py: Remove sys.version_info check

### PR DESCRIPTION
**Pull request by scriptnull**
Fixes https://github.com/coala-analyzer/coala/issues/1417

### CODE REVIEW

**Comment by sils1297** [comment]
ack 421bff31b764e4

**Comment by sils1297** [comment]
@scriptnull hey cool! You now seem to know the workflow. We'd appreciate it if you aviod solving newcomer issues when possible because they're a hell lot work to come up with :) I think you're now totally ready to get your hands dirty - as such welcome to the community - awesome to have you :)

**Comment by Makman2** [comment]
@rultor merge

**Comment by scriptnull** [comment]
@sils1297 haha sure ! Thanks. The community is awesome. People are there to help, almost all the time in coala channel, which is a great push for new comers like me. I will try to get in deep and solve something other than a newcomer issue.

**Pull request merged**
