### PR TITLE
printers: Use Printer from PyPrint

### PR DESCRIPTION
**Pull request by sils1297**

### CODE REVIEW

**Comment by sils1297** [comment]
see https://github.com/coala-analyzer/coala/issues/925

**Comment by sils1297** [comment]
Reviewers: I don't see any point in fixing the scrutinizer issue, the file will be removed later anyways and I don't see why it turns up now and not before.

**Comment by Makman2** [comment]
There's some problems in two tests, the `ConsoleInteractionTest` and the `coalaTest`.
--> https://gist.github.com/Makman2/9960f8dbb2f6ac55bf26
Occurs on three machines: Windows 10 (hardware), 2x Fedora 22 (VM and hardware)
and yes pyprint was installed via `pip install pyprint`

**Comment by Makman2** [comment]
I'll investigate this tomorrow^^

**Comment by sils1297** [comment]
On this PR? Which version of pyprint did you install?

**Comment by sils1297** [comment]
@Makman2 that happens for me on sils/printcol not on this one.

**Comment by Makman2** [comment]
ouh yeah indeed I tested on `sils/printcol`, this branch works :)

**Comment by sils1297** [comment]
@Makman2 so then this is pending review again, right? (And needs rebase sooner or later.)

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
