### PR TITLE
coafile: Add LanguageToolBear for docs

### PR DESCRIPTION
**Pull request by AbdealiJK**
Add this bear and fix issues that came up in the docs.

Fixes https://github.com/coala-analyzer/coala/issues/1697

### CODE REVIEW

**Comment by sils1297** [comment]
@Makman2 please mark PRs wip after review

**Comment by AbdealiJK** [comment]
Note that this is blocked until the coala-bears PR gets merged (We need those extra options in the bear)

**Comment by sils1297** [comment]
as decided on gitter we want lots of newcomer bugs

**Comment by sils1297** [comment]
@rultor merge

**Comment by AbdealiJK** [comment]
@rultor merge

**Pull request merged**
