### PR TITLE
requirements: Updates cpplint version

### PR DESCRIPTION
**Pull request by Redridge**
I updated the version of cpplint in requirements.txt

### CODE REVIEW

**Comment by sils1297** [comment]
@Redridge please accept the invitation to our org so we can assign you

**Comment by AbdealiJK** [comment]
unack  59a1739

**Comment by Redridge** [comment]
I think everything should be ok now. I hope

**Comment by sils1297** [comment]
@Redridge almost! The commit message needs another adaption and a rebase is in order. (It's very usual for a PR to be reviewed multiple times and also happens with mine or other peoples work so don't worry, you're doing good :))

**Comment by sils1297** [comment]
unack f09ecbf

**Comment by sils1297** [comment]
ack ac71cc6

**Comment by sils1297** [comment]
reack 2b4bb99

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
