### PR TITLE
Git_Hooks: Change 'standars` to 'standards'

### PR DESCRIPTION
**Pull request by kmo1**
Closes https://github.com/coala-analyzer/coala/issues/2473

### CODE REVIEW

**Comment by sils1297** [comment]
Hey @kmo1 thanks for your help - the docs are currently being ported to https://github.com/coala-analyzer/documentation/ by @Adrianzatreanu - I think we'll want to close this PR and maybe make a new one if it wasn't already fixed in the docs repo.

Sorry :/

@Adrianzatreanu to avoid this we should remove the documentation label from this repo and announce it on maintainers that documentation issues should be filed in your repo? Can we do the actual switch and remove the docs soon?

**Comment by Adrianzatreanu** [comment]
i moved the issues already, this is a PR

**Comment by sils1297** [comment]
that issue is a new one from hypo

**Comment by Adrianzatreanu** [comment]
oh, my bad..

**Pull request closed without merging**
