### PR TITLE
minor typo fix in installation doc

### PR DESCRIPTION
**Pull request by staranjeet**
This PR fixes a minor issue, where a link is not properly written in markdown.

### CODE REVIEW

**Comment by sils1297** [comment]
unack 2ab753f61e6f79152179d4f923070a12decd2029, needs work

**Comment by Makman2** [comment]
The link is automatically linked and it works :O

**Comment by sils1297** [comment]
@Makman2 this is only because github doesn't use the strict markdown spec

**Comment by staranjeet** [comment]
Opening a issue for missing brackets will not be fair, you can merge it like this only :)

**Comment by sils1297** [comment]
ack 3ecfcd56aeb138eb511d7b3723d73e0b2a69d4f2

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
Hey, congrats to your first contribution! As you can see it was already released as a development release at https://pypi.python.org/pypi/coala/0.4.1.dev20160203161256 .

**Comment by staranjeet** [comment]
Thanks. First contribution to coala finally in release. :). Btw, a very nice documentation for the commit message.

**Pull request merged**
