### PR TITLE
DocstyleDefinition: Use type-checks

### PR DESCRIPTION
**Pull request by vadi95**
Fixes https://github.com/coala-analyzer/coala/issues/1142

### CODE REVIEW

**Comment by sils1297** [comment]
ack 24c418e3b, though this needs a rebase onto the current master. Can you do that?

**Comment by sils1297** [comment]
reack e1a4866204c5 , cool! Congrats to your first contribution - will merge after CI passed.

**Comment by sils1297** [comment]
@vadi95 also do you know our channel https://gitter.im/coala-analyzer/coala ? If you have any questions you can drop by there.

**Comment by vadi95** [comment]
Yeah sure. Thanks! :)

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
