### PR TITLE
misc/ContextManager:Fix spelling error

### PR DESCRIPTION
**Pull request by srisankethu**
Fixes https://github.com/coala-analyzer/coala/issues/1439

### CODE REVIEW

**Comment by sils1297** [comment]
this is almost ready to merge, the commit message needs adaption (just do the `--amend`) and you will need a rebase in 10ish minutes because I'm about to merge another PR>

**Comment by srisankethu** [comment]
@sils1297 I am performing git commit --amend from the terminal(Ubuntu), how should I save my changes?

**Comment by sils1297** [comment]
@srisankethu you also need to fetch the latest commits from upstream (assuming you named our original repo that way) and then do a rebase on it with `git rebase upstream/master`, then you can publish your new commit via `git push --force`

**Comment by srisankethu** [comment]
@sils1297 Can you check my PR

**Comment by sils1297** [comment]
@srisankethu from what I can see I can for sure tell that you didn't do a rebase at all.

**Comment by sils1297** [comment]
@srisankethu you seem to have done a merge, we want you to do a rebase, please ask for help on gitter.

**Comment by srisankethu** [comment]
@sils1297 I did a git rebase master

**Comment by sils1297** [comment]
@srisankethu why don't you just join https://gitter.im/coala-analyzer/coala ? There's lots of people willing to help you more in depth and interactively.

**Pull request closed without merging**
