### PR TITLE
js.coalang: Move the file to the correct directory

### PR DESCRIPTION
**Pull request by meetmangukiya**
js.coalang is a language definition file that should be placed in
definitions folder, but it was in languages folder, hence moved to
correct path

### CODE REVIEW

**Comment by meetmangukiya** [comment]
Git is smart, it tracked that I moved the file from one directory to another directory. :raised_hands:

**Comment by sils1297** [comment]
Fixes note missing @meetmangukiya

**Comment by meetmangukiya** [comment]
Sorry :disappointed: I forgot about it :(

**Comment by meetmangukiya** [comment]
Fixes or closes :/ ?

**Comment by sils1297** [comment]
I think fixes, it's a bug

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala-analyzer.org/ - http://viperdev.io/ - http://gitmate.com/

**Comment by meetmangukiya** [comment]
Done

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2744/commits/2205c544c6be6904755b8e3e7c0c4ba6d12c175e

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
