### PR TITLE
Lint: Check for executable availability

### PR DESCRIPTION
**Pull request by sils1297**
@Makman2 awesome, it works :)

```
lasse@lssteady ~/prog/coala (git)-[master] % ./coala default -f test.js -b JSHintBear
Executing section Default...
[WARNING][14:13:08] The bear JSHintBear does not fulfill all requirements. jshint is not installed.
```

this PR still needs tests though

### CODE REVIEW

**Comment by AbdealiJK** [comment]
I believe this is because int he inheritance we use `LocalBear, Lint` - it should be `Lint, LocalBear` because python uses the left most class as higher priority.

**Comment by sils1297** [comment]
I think we shouldn't rely on the order here, should we?

**Comment by sils1297** [comment]
i.e. we can just make `Lint` a bear so the user does not have to deal with this

**Comment by AbdealiJK** [comment]
Inheritance does rely on the order ...
It's not bad coding per se

On Thu, Dec 17, 2015 at 11:59 AM, Lasse Schuirmann <notifications@github.com

**Comment by sils1297** [comment]
Not bad coding, bad usability.

**Comment by AbdealiJK** [comment]
But ... how else do you use multiple inheritance ?
If I have same function name in class `A` and class `B` - there is a well
defined priority order.

I rarely use multiple inheritance - so, let's look at the other cases
possible:

1. Lint inherits from Bear
Even if you inherit `Bear` in `Lint` - you'd still have to order your
inheritance in the final bear as `LocalBear, Lint` and not `Lint,
LocalBear` - otherwise the Bear's `run` would be the one which is used -
which raises NotImplemented. In fact this would get complicated - because
you need `LocalBear`'s `run` and `Lint`'s `check_prerequisites` -> implying
both need different orders.

2. Lint inherits from LocalBear
The other option is to inherit LocalBear into Lint - which is not right,
because it constraints it to be a LocalBear - which is not logically
correct, as Linters are not constrained so.

Am I missing some method of doing this which makes things simpler ?



On Thu, Dec 17, 2015 at 12:23 PM, Lasse Schuirmann <notifications@github.com

**Comment by sils1297** [comment]
Hm, still it's kind of weird that we want to override a method in `Lint` that is not in one of it's base classes, it's clearer if it is. We could also make `Lint` not derive from `Bear` and invoke the check in `__init__`... however we won't have a log message in that case. This feels ugly. How'd you solve this?

**Comment by AbdealiJK** [comment]
I'm not sure :( - I played around with inheriting Bear into Linter earlier - and this seemed to be the best way I could think of. (Now `check_prerequisite` introduces more complexity)

**Comment by AbdealiJK** [comment]
How about :
 - We make a function "check_shell_command" in `Utils.py` - which can also be used to check when tests need to be skipped.
 - Then, we make another class `LocalLintBear` which simply inherits `LocalBear` and `Lint` and overrides the `check_prerequisite` and gives the error code from `check_shell_command` ?
 - And also modify `Lint` to not take a `filename` specifically - but rather take any args. Which and `LocalLintBear` can get a filename, clean it and pass it to Lint as a arg. So, we'd be modularizing out the Lint part and LocalBear part.
 - Later : we can make a GlobalLintBear

**Comment by sils1297** [comment]
That sounds good, can you look at this?

**Comment by AbdealiJK** [comment]
Sure, but not until ~30th - Im travelling around until then

**Comment by sils1297** [comment]
Ok, will keep this open, maybe I'll find some time until then, maybe not.

2015-12-17 8:47 GMT+01:00 AbdealiJK <notifications@github.com>:

**Comment by abhsag24** [comment]
@AbdealiJK python3 manages inheritance in such a way, that the overwritten methods in any of the subclasses is used, regardless of its order in the `__mro__` (as long as there are no conflicts, then order is used) . so in our case since Lint inherits from Bear and overwrites the `check_prerequisites` function , the order of Lint doesn't matter as long as LocalBear itself doesn't overwrite the same function(which it doesn't), so Lint and LocalBear can have any order. 

The problem in our code is same as "The Diamond Problem", explained in 
 http://www.python-course.eu/python3_multiple_inheritance.php

**Comment by abhsag24** [comment]
time to close this now?

**Comment by sils1297** [comment]
yes @abhsag24 thanks for your help here :)

**Pull request closed without merging**
