### PR TITLE
Escape asterisk so that it is surely accepted as a glob

### PR DESCRIPTION
**Pull request by SanketDG**

### CODE REVIEW

**Comment by GitCop** [comment]
The commit message

 * Commit: 2c361ed268b9961f18ca43f1bca2d39162b1f122
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: c4e4a1c3a43c5af4dca54a27a9a8a7b8e9f2ff04
  * Commits must be in the following format: **%{scope}: %{description}**

Guidelines are available at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages

---
This message was auto-generated by https://gitcop.com

**Comment by sils1297** [comment]
Hey @SanketDG ! Did you read http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages ? I think your shortlog is too long, it definitely needs capitalization after the colon. Rather try something like `Escape glob argument` then explaining it elaboratively. Explain what you *do* not what you *fix* and keep it short and concise. I'll let the second shortlog to you ;)

Second: as github shows - this branch is out of date. You will need to rebase it onto the current master. I recommend you wait with that until we merge https://github.com/coala-analyzer/coala/pull/1194 which is in about five minutes, otherwise you'll just have to do it again.

**Comment by SanketDG** [comment]
@sils1297 Are the commit messages now okay?

> Second: as github shows - this branch is out of date. You will need to rebase it onto the current master. I recommend you wait with that until we merge #1194 which is in about five minutes, otherwise you'll just have to do it again.

I have done that.

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
