### PR TITLE
Wjcode/sphinxdocs - Convert our documentation to Sphinx

### PR DESCRIPTION
**Pull request by WJCode**
Fixes https://github.com/coala-analyzer/coala/issues/1198

### CODE REVIEW

**Comment by WJCode** [comment]
@sils1297 While running `setup.py`, there is a `UnicodeEncodeError` on my [latest build](https://readthedocs.org/projects/coaladocs/builds/3698108/) on readthedocs.org. I am not getting this error locally. I'll have to look into this some more

**Comment by WJCode** [comment]
Yes, of course :)

**Comment by sils1297** [comment]
@WJCode alright, so far looks nice, the direction is good, needs some general polishing like the pointed out things. Not sure how the commits should be structured ideally...

**Comment by WJCode** [comment]
@sils1297 I corrected the typos mentioned. I hope this looks better now

**Comment by sils1297** [comment]
ack 2e6284c cd3d6fa f5c6cef 4b138af, 27e0aed

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
