### PR TITLE
Revert "Linter: Accept list only on process..."

### PR DESCRIPTION
**Pull request by sils1297**
This reverts commit 6d96e937d3e026917a6ce2f02a8a9a06698531e4.

Apparently this seems to break things.

### CODE REVIEW

**Comment by sils1297** [comment]
CC @Redridge this is probably a hotfix

**Comment by sils1297** [comment]
also CC @Makman2

**Comment by Redridge** [comment]
ack ac2d536

**Comment by Redridge** [comment]
@rultor merge

**Comment by sils1297** [comment]
if it's not working please redo the original commit, if it is working please file an issue

**Pull request merged**
