### PR TITLE
Linters

### PR DESCRIPTION
**Pull request by AbdealiJK**
Unify all the linters !

### CODE REVIEW

**Comment by AbdealiJK** [comment]
I'd like to veto the scrutinizer issue - as the function can be inherited and the inherited function may want to use `self`

**Comment by sils1297** [comment]
@AbdealiJK you can override a static method with a nonstatic one, that's no problem

**Comment by AbdealiJK** [comment]
Oh ! alright - will change it then

**Comment by sils1297** [comment]
I pulled in the acked commits into https://github.com/coala-analyzer/coala/pull/1114 so we get an initial batch :)

**Comment by sils1297** [comment]
@AbdealiJK take a look at https://github.com/coala-analyzer/coala/pull/1116 , I did the directory restructurizing.

**Comment by sils1297** [comment]
better wait with the rebase until https://github.com/coala-analyzer/coala/pull/1120 is merged

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
