### PR TITLE
.gitignore: add docs/API/ to gitignore

### PR DESCRIPTION
**Pull request by arush0311**
Fixes https://github.com/coala-analyzer/coala/issues/1497

### CODE REVIEW

**Comment by Makman2** [comment]
You commit message needs slight polishing :)

1. Letters after `tag:` are upper case
2. You are a bit over-verbose: `.gitignore: add [...] to gitignore`

So `.gitignore: Add docs/API/` would suffice :D

**Comment by Makman2** [comment]
ack 35140d7

**Comment by AbdealiJK** [comment]
ack 35140d7

**Comment by sils1297** [comment]
moved to https://github.com/coala-analyzer/coala/pull/1615 for ease of merging. Your contribution will still be yours, don't worry ;)

**Pull request closed without merging**
