### PR TITLE
tests/bearlib: Remove double documentation

### PR DESCRIPTION
**Pull request by srisankethu**
Fixes https://github.com/coala-analyzer/coala/issues/1343

### CODE REVIEW

**Comment by sils1297** [comment]
unack  70be6c5, can be merged after commit message correction :)

**Comment by srisankethu** [comment]
@sils1297 Changed commit message

**Comment by sils1297** [comment]
@srisankethu this needs a rebase

**Comment by srisankethu** [comment]
@sils1297 I performed  git rebase upstream/master and it says current branch is already update

**Comment by sils1297** [comment]
@srisankethu you also need to do a `git fetch upstream` before so your local repo is in sync

**Comment by srisankethu** [comment]
@sils1297 Done!

**Comment by sils1297** [comment]
hm your branch isn't out of  date but you seem to have a merge commit there, as you can see 8d27bfa has two parents which makes it a merge commit :/

**Comment by srisankethu** [comment]
@sils1297 What should I do then?

**Comment by sils1297** [comment]
Please ping us on Gitter so we can help you resolve this. I have some appointment soon, maybe @Makman2, @AbdealiJK @SanketDG, @abhsag24 or @tushar-rishav can help you?

**Comment by sils1297** [comment]
as per discussion on gitter

**Comment by sils1297** [comment]
this needs work still

**Pull request closed without merging**
