### PR TITLE
coalib/tests: coala_bears_test_module ->test_bears

### PR DESCRIPTION
**Pull request by ravinimmi**
Fixes: https://github.com/coala-analyzer/coala/issues/1616

### CODE REVIEW

**Comment by sudheesh001** [comment]
unack 9362a5c

**Comment by sudheesh001** [comment]
Scrutinizer failure and we could do better in the commit message.
`coalib: Move coala_bears_test_module to test_bears`

**Comment by AbdealiJK** [comment]
"Rename" is the correct verb - "Move" means something else entirely.

Also, ignore the scrutinizer issue - @sils1297 needs to tell scrutinizer to ignore it as it's unavoidable

**Comment by ravinimmi** [comment]
@AbdealiJK Rename is exceeding 50 chars limits.

**Comment by AbdealiJK** [comment]
ack e2384af

**Comment by AbdealiJK** [comment]
Moving this to https://github.com/coala-analyzer/coala/pull/1625 to make it easier for me to merge everything. The commit will still be in your name, dont worry about that

**Pull request closed without merging**
