### PR TITLE
Bear: Change ``Simplification`` -> ``Redundancy``

### PR DESCRIPTION
**Pull request by Asnelchristian**
Fixes https://github.com/coala-analyzer/coala/issues/2416

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
commit message: ``Bear.py: Change ``Simplification``->``Redundancy``

**Comment by Adrianzatreanu** [comment]
unack 8edb751

**Comment by Adrianzatreanu** [comment]
remove the 2 spaces between the arrow

**Comment by Adrianzatreanu** [comment]
ack 11cf6d0

**Comment by Makman2** [comment]
@rultor merge

**Pull request merged**
