### PR TITLE
README: Add Gitmate Badge

### PR DESCRIPTION
**Pull request by mr-karan**
Add `gitmate` badge from [shields.io](https://img.shields.io)

### CODE REVIEW

**Comment by SanketDG** [comment]
ack f2b369a

**Comment by sils1297** [comment]
unack https://github.com/mr-karan/coala/commit/f2b369ab78836e875ac469c7e79835f85cb97016 , please don't use markdown in commit messages

**Comment by sils1297** [comment]
also can you please link the badge to gitmate.io?

**Comment by AbdealiJK** [comment]
This feels like we're cheating the system >_>
Cuz we're hardcoding it to 0

**Comment by sils1297** [comment]
https://github.com/coala-analyzer/coala/pull/1880#issuecomment-196169728 @AbdealiJK well we have an assert in the CI that'll make sure this is always the case, it's just a workaround for gitmate not having a badge right now.

**Comment by sils1297** [comment]
ack https://github.com/mr-karan/coala/commit/aa9d3782ae63ba11772cacfd8ed2a5a71f9670a4 from me, if @AbdealiJK agrees

**Comment by AbdealiJK** [comment]
ready aa9d3782ae63ba11772cacfd8ed2a5a71f9670a4

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
