### PR TITLE
misc changes

### PR DESCRIPTION
**Pull request by sils1297**

### CODE REVIEW

**Comment by Makman2** [comment]
Besides all tests run successfully on my VM (ignoring eSpeak).

**Comment by sils1297** [comment]
Why shouldn't they?

2015-03-02 16:51 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
They should and I tested them myself to be sure :D

**Comment by Makman2** [comment]
okay my formulation with "besides" was a bit irritating...

**Comment by sils1297** [comment]
fixed the comment, you can continue review

**Comment by Makman2** [comment]
ready for merge^^

**Comment by sils1297** [comment]
merging, thanks

2015-03-03 21:54 GMT+01:00 Makman2 <notifications@github.com>:

**Pull request merged**
