### PR TITLE
WIP: Logging

### PR DESCRIPTION
**Pull request by sils1297**

### CODE REVIEW

**Comment by sils1297** [comment]
@Makman2 you'll find this interesting, it works actually ;)

**Comment by Makman2** [comment]
this is damn easy :O
what about pyprint then? and does logging have color support?

**Comment by sils1297** [comment]
nope, not yet, this needs tweaking but this is something very basic and could be a first step

**Comment by sils1297** [comment]
closing in favour of https://github.com/coala-analyzer/coala/pull/2409

**Pull request closed without merging**
