### PR TITLE
docs: Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by srisankethu**
Fixes https://github.com/coala-analyzer/coala/issues/1442

### CODE REVIEW

**Comment by AbdealiJK** [comment]
unack 573259a

**Comment by sils1297** [comment]
the two commits need to be squashed, use interactive rebase and a fixup?

**Comment by srisankethu** [comment]
how to add ignore line length to http//: ? Can you give me an example?

**Comment by sils1297** [comment]
> how to add ignore line length to http//: ? Can you give me an example?

don't care about the ignores! Just remove them. No such thing is needed right now.

**Pull request closed without merging**
