### PR TITLE
Fixes #1749  , Typo error

### LINKED ISSUE #1749: A simple typo in the Install.rst file
The file `/docs/Users/Install.rst` has a typo in it.

Namely the occurence of `Max` instead of `Mac`

### PR DESCRIPTION
**Pull request by saurabhiiit**

### CODE REVIEW

**Comment by tushar-rishav** [comment]
@saurabhiiit Hey. Almost there. You just need to improve your commits. Why not read [Writing Good Commits](http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html) and then try again. :)

**Comment by saurabhiiit** [comment]
@tushar-rishav  I will surely take care of this and do better next time.

**Comment by sils1297** [comment]
@saurabhiiit you received an org invitation btw. please check your mail or github.com/coala-analyzer

**Comment by saurabhiiit** [comment]
@sils1297 Thanks.

**Comment by AbdealiJK** [comment]
@saurabhiiit please take a look at http://coala.readthedocs.org/en/latest/Getting_Involved/Newcomers.html to help you out in figuring git out a bit better.
I think you need to clean up your commits : You add something then fix a typo, then delete the thing you added first ?
Also, the title says you;re trying to fix #1749 which is already assigned to someone else. 
Please check if the issue is unassigned, else we're doing redundant work :(

**Comment by srisankethu** [comment]
@saurabhiiit Try this to update your local repo : 
1. ` git remote add <remote name> https://github.com/coala-analyzer/coala.git`
2. `git fetch <remote name>`
3. `git rebase <remote name>/master`

To change the commit message try :  `git commit --amend -m <commit message>`
Check http://coala.readthedocs.org/en/latest/Getting_Involved/Newcomers.html for clarity.

Let your commit message be something like, <where did you make a change>: <what your PR does>

**Pull request closed without merging**
