### PR TITLE
Sils/rult

### PR DESCRIPTION
**Pull request by sils1297**

### CODE REVIEW

**Comment by sils1297** [comment]
reack
1a09fe4 NpmRequirement: Add it
41eb2f7 PackageRequirement: Add multiple method
db9901f PythonRequirement: Fix docs
56417fa circle.yml: Increase timeout to 15 minutes
d461814 Linter: Invoke full executable path

**Comment by Makman2** [comment]
ack 3585ec9

**Comment by sils1297** [comment]
reack
  1 pick 43e4e23 circle.yml: Increase timeout to 15 minutes
  2 pick 1afa8f8 PythonRequirement: Fix docs
  3 pick 7822426 PackageRequirement: Add multiple method
  4 pick e34ba78 NpmRequirement: Add it

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
reack
d1206d0 NpmRequirement: Add it
3ab66cb PackageRequirement: Add multiple method
8d4120c PythonRequirement: Fix docs
bad66f5 circle.yml: Increase timeout to 15 minutes

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
reack https://github.com/coala-analyzer/coala/pull/2204/commits/9d3ead863c5f2821b4946fd1f09faf3e6bf7a4f2

**Pull request merged**
