### PR TITLE
Makman2/git-commit-bear

### PR DESCRIPTION
**Pull request by Makman2**

### CODE REVIEW

**Comment by sils1297** [comment]
@Makman2 please fix the build failures and the stuff you already found before submitting to review :)

**Comment by GitCop** [comment]
The commit message

 * Commit: 34b464f99721182adbeb40c3f9c20a85caa645fd
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 63f5849dcb08d86742c7dea5a9f2927b0288e44d
  * Commits must be in the following format: **%{scope}: %{description}**

Guidelines are available at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
The commit message

 * Commit: 34b464f99721182adbeb40c3f9c20a85caa645fd
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 63f5849dcb08d86742c7dea5a9f2927b0288e44d
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 83b4b4da2534ed157e426da8c42b51552e7521df
  * Commits must be in the following format: **%{scope}: %{description}**

Guidelines are available at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
The commit message

 * Commit: 34b464f99721182adbeb40c3f9c20a85caa645fd
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 63f5849dcb08d86742c7dea5a9f2927b0288e44d
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 83b4b4da2534ed157e426da8c42b51552e7521df
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: a101f43f8290159e3f82c4b0d3b850acc79f5ed8
  * Commits must be in the following format: **%{scope}: %{description}**

Guidelines are available at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
The commit message

 * Commit: 34b464f99721182adbeb40c3f9c20a85caa645fd
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 63f5849dcb08d86742c7dea5a9f2927b0288e44d
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 83b4b4da2534ed157e426da8c42b51552e7521df
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: a101f43f8290159e3f82c4b0d3b850acc79f5ed8
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 58be5f3f5506102c818f8000c9e244c112d59f76
  * Commits must be in the following format: **%{scope}: %{description}**

Guidelines are available at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages

---
This message was auto-generated by https://gitcop.com

**Comment by Makman2** [comment]
for myself: what needs to be done?
- Make `prepare_string_argument` in *Shell.py* os-dependent, and assume on Windows cmd
- Test that
- I think that's it, then it should work...

**Comment by GitCop** [comment]
The commit message

 * Commit: 34b464f99721182adbeb40c3f9c20a85caa645fd
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 63f5849dcb08d86742c7dea5a9f2927b0288e44d
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 83b4b4da2534ed157e426da8c42b51552e7521df
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: a101f43f8290159e3f82c4b0d3b850acc79f5ed8
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 58be5f3f5506102c818f8000c9e244c112d59f76
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 8a7df6dc69b775779bf04984c766c212060948c7
  * Commits must be in the following format: **%{scope}: %{description}**

Guidelines are available at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
The commit message

 * Commit: 34b464f99721182adbeb40c3f9c20a85caa645fd
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 63f5849dcb08d86742c7dea5a9f2927b0288e44d
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 83b4b4da2534ed157e426da8c42b51552e7521df
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: a101f43f8290159e3f82c4b0d3b850acc79f5ed8
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 58be5f3f5506102c818f8000c9e244c112d59f76
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 8a7df6dc69b775779bf04984c766c212060948c7
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 6b2a05c3c37fb3a1b15ca6f97925cdc35912c50e
  * Commits must be in the following format: **%{scope}: %{description}**

Guidelines are available at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
The commit message

 * Commit: 34b464f99721182adbeb40c3f9c20a85caa645fd
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 63f5849dcb08d86742c7dea5a9f2927b0288e44d
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 83b4b4da2534ed157e426da8c42b51552e7521df
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: a101f43f8290159e3f82c4b0d3b850acc79f5ed8
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 58be5f3f5506102c818f8000c9e244c112d59f76
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 8a7df6dc69b775779bf04984c766c212060948c7
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 6b2a05c3c37fb3a1b15ca6f97925cdc35912c50e
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 70892ae8858150c8747bf821e1d66d62f81cb6f4
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 4edf54c38cd36d5a49284ff853f897177a87a7f3
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: d8595b53f261d083b0a55f628ecbd651ba2efb38
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 360a819b6495e3ec5bafe532b29447c6bcaabf2e
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 8a9931385e73eee0f4c206342fce9d61677a30cf
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 25e82951e26c9c4d228ff1e02c975e65fc11a535
  * Commits must be in the following format: **%{scope}: %{description}**

Guidelines are available at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages

---
This message was auto-generated by https://gitcop.com

**Comment by sils1297** [comment]
@Makman2 don't forget to rebase

**Comment by GitCop** [comment]
The commit message

 * Commit: 34b464f99721182adbeb40c3f9c20a85caa645fd
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 63f5849dcb08d86742c7dea5a9f2927b0288e44d
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 83b4b4da2534ed157e426da8c42b51552e7521df
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: a101f43f8290159e3f82c4b0d3b850acc79f5ed8
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 58be5f3f5506102c818f8000c9e244c112d59f76
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 8a7df6dc69b775779bf04984c766c212060948c7
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 6b2a05c3c37fb3a1b15ca6f97925cdc35912c50e
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 70892ae8858150c8747bf821e1d66d62f81cb6f4
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 4edf54c38cd36d5a49284ff853f897177a87a7f3
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: d8595b53f261d083b0a55f628ecbd651ba2efb38
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 360a819b6495e3ec5bafe532b29447c6bcaabf2e
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 8a9931385e73eee0f4c206342fce9d61677a30cf
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 25e82951e26c9c4d228ff1e02c975e65fc11a535
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 92ee39bfb5593bfbb318fdf0dbd977bbd1eeb558
  * Commits must be in the following format: **%{scope}: %{description}**

Guidelines are available at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
The commit message

 * Commit: b77c644bea54105afe167570b4cd2e372a591e00
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 0bfed39d5575c2c0849ebd2efd840f83c1d5a98e
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: ff18ec1bd6bcf3f5f599135dcf86d8c2083ecdac
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: c044571c3974624f274b318b0377846f89d727de
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: e38dbb61a95657461f49db9d18c2e90a9e9789ab
  * Commits must be in the following format: **%{scope}: %{description}**

Guidelines are available at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
The commit message

 * Commit: 07532bed172414f6611acb77ba03be452b02429c
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 5042ffa983756db91d5009cee1687d2f31fd77f3
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: b376fde7f56c5e512f6ff0234cd2a68339ba72bc
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 544adbe7a6dd8d3a367a3809fbcc4358a192cf5b
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: a39c3c9e7518e2c24736666e937183c3f9ebd704
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: c56645fda723a73c1f4b053e5955d5340831f986
  * Commits must be in the following format: **%{scope}: %{description}**

Guidelines are available at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
The commit message

 * Commit: 07532bed172414f6611acb77ba03be452b02429c
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 5042ffa983756db91d5009cee1687d2f31fd77f3
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: b376fde7f56c5e512f6ff0234cd2a68339ba72bc
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: 544adbe7a6dd8d3a367a3809fbcc4358a192cf5b
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: a39c3c9e7518e2c24736666e937183c3f9ebd704
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: c56645fda723a73c1f4b053e5955d5340831f986
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: e7aeb78df7a424d16f080989d036732ec5507f39
  * Commits must be in the following format: **%{scope}: %{description}**

Guidelines are available at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages

---
This message was auto-generated by https://gitcop.com

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
