### PR TITLE
Wip/dreamlined sils

### PR DESCRIPTION
**Pull request by sils1297**

### CODE REVIEW

**Comment by smfn3321** [comment]
@sils1297 could you please investigate why coverage/coveralls shows a coverage decrease of 38% (that's a lot!). I cannot reproduce this as my coverage on this same branch is 99%

Tests finished: failures in 0 of 48 test modules
Name                                                                Stmts   Miss Branch BrMiss  Cover   Missing
---------------------------------------------------------------------------------------------------------------
bears/__init__                                                          0      0      0      0   100%   
bears/misc/KeywordBear                                                 20      0     14      0   100%   
bears/misc/LineLengthBear                                              14      0      4      0   100%   
bears/misc/__init__                                                     0      0      0      0   100%   
bears/spacing/SpaceConsistencyBear                                     22      0      8      0   100%   
bears/spacing/__init__                                                  0      0      0      0   100%   
bears/tests/LocalBearTestHelper                                         2      0      0      0   100%   
bears/tests/__init__                                                    0      0      0      0   100%   
coalib/__init__                                                         0      0      0      0   100%   
coalib/bearlib/__init__                                                 0      0      0      0   100%   
coalib/bearlib/abstractions/SectionCreatable                           13      0      0      0   100%   
coalib/bearlib/abstractions/__init__                                    0      0      0      0   100%   
coalib/bearlib/spacing/SpacingHelper                                   58      0     28      0   100%   
coalib/bearlib/spacing/__init__                                         0      0      0      0   100%   
coalib/bears/BEAR_KIND                                                  3      0      0      0   100%   
coalib/bears/Bear                                                      67      0     10      0   100%   
coalib/bears/GlobalBear                                                10      0      0      0   100%   
coalib/bears/LocalBear                                                 12      0      0      0   100%   
coalib/bears/__init__                                                   0      0      0      0   100%   
coalib/collecting/BearCollector                                        85      0     44      1    99%   
coalib/collecting/Collector                                            20      0      2      0   100%   
coalib/collecting/FileCollector                                       117      0     72      1    99%   
coalib/collecting/Importers                                            53      0     34      0   100%   
coalib/collecting/__init__                                              0      0      0      0   100%   
coalib/misc/ContextManagers                                            10      0      0      0   100%   
coalib/misc/Decorators                                                 28      0     14      0   100%   
coalib/misc/StringConstants                                            12      0      0      0   100%   
coalib/misc/StringConverter                                            74      0     32      0   100%   
coalib/misc/__init__                                                    0      0      0      0   100%   
coalib/misc/i18n                                                       36      0     16      3    94%   
coalib/output/ConfWriter                                               45      0     15      0   100%   
coalib/output/ConsoleInteractor                                        95      0     42      0   100%   
coalib/output/Interactor                                               51      0     16      0   100%   
coalib/output/__init__                                                  0      0      0      0   100%   
coalib/output/printers/ColorPrinter                                    15      0      2      0   100%   
coalib/output/printers/ConsolePrinter                                  16      0      2      0   100%   
coalib/output/printers/EspeakPrinter                                   14      0      0      0   100%   
coalib/output/printers/FilePrinter                                     14      0      4      0   100%   
coalib/output/printers/LOG_LEVEL                                        6      0      0      0   100%   
coalib/output/printers/LogPrinter                                      36      0     10      0   100%   
coalib/output/printers/NullPrinter                                     10      0      0      0   100%   
coalib/output/printers/Printer                                          6      0      2      0   100%   
coalib/output/printers/__init__                                         0      0      0      0   100%   
coalib/parsing/CliParser                                               46      0     20      0   100%   
coalib/parsing/ConfParser                                              68      0     22      0   100%   
coalib/parsing/DefaultArgParser                                        21      0      0      0   100%   
coalib/parsing/Glob                                                    69      0     34      1    99%   
coalib/parsing/LineParser                                              54      0     21      0   100%   
coalib/parsing/SectionParser                                            7      0      0      0   100%   
coalib/parsing/__init__                                                 0      0      0      0   100%   
coalib/processes/Barrier                                                3      0      0      0   100%   
coalib/processes/BearRunner                                           104      0     45      6    96%   
coalib/processes/CONTROL_ELEMENT                                        4      0      0      0   100%   
coalib/processes/SectionExecutor                                       84      0     34      1    99%   
coalib/processes/__init__                                               0      0      0      0   100%   
coalib/processes/communication/LogMessage                              16      0      4      0   100%   
coalib/processes/communication/__init__                                 0      0      0      0   100%   
coalib/results/Diff                                                    59      0     28      0   100%   
coalib/results/LineDiff                                                28      0     10      0   100%   
coalib/results/PatchResult                                             23      0     12      0   100%   
coalib/results/RESULT_SEVERITY                                          7      0      0      0   100%   
coalib/results/Result                                                  32      0     22      0   100%   
coalib/results/__init__                                                 0      0      0      0   100%   
coalib/results/result_actions/ApplyPatchAction                          8      0      4      0   100%   
coalib/results/result_actions/ResultAction                             17      0      6      0   100%   
coalib/results/result_actions/__init__                                  0      0      0      0   100%   
coalib/settings/DocumentationComment                                   45      0     20      0   100%   
coalib/settings/FunctionMetadata                                       62      0     39      0   100%   
coalib/settings/Section                                                97      0     38      0   100%   
coalib/settings/SectionFiller                                          30      0     20      0   100%   
coalib/settings/SectionManager                                         68      0     12      0   100%   
coalib/settings/Setting                                                35      0     12      0   100%   
coalib/settings/__init__                                                0      0      0      0   100%   
coalib/tests/processes/section_executor_test_files/GlobalTestBear       2      0      0      0   100%   
coalib/tests/processes/section_executor_test_files/LocalTestBear        3      0      0      0   100%   
---------------------------------------------------------------------------------------------------------------
TOTAL                                                                1956      0    774     13    99% 

[localghost] coala > git status
Auf Branch wip/dreamlined_sils
Ihr Branch ist auf dem selben Stand wie 'origin/wip/dreamlined_sils'.

**Comment by smfn3321** [comment]
I DID add a test with two temporary files using the same procedure as in the old BearCollectorTest.

**Comment by sils1297** [comment]
Ill investigate now. Seems if we measure coverage of the python lib itself
in the Travis environment.
Am 05.02.2015 23:52 schrieb "Fabian Neuschmidt" <notifications@github.com>:

**Comment by sils1297** [comment]
did you read my comments about the importer?

**Pull request closed without merging**
