### PR TITLE
misc/ContextManager:Fix spelling error

### LINKED ISSUE #1439: Spelling error in ContextManager
`coalib/misc/ContextManagers.py` function `prepare_file` has a spelling error - `Can creates a temporary file ... ` should be `Can create a temporary file ...`

### PR DESCRIPTION
**Pull request by srisankethu**
Fixes #1439

### CODE REVIEW

**Comment by AbdealiJK** [comment]
@srisankethu - Hi !
Thanks for contributing to coala !

Would it be possible for us to chat in realtime ?
Maybe on whatsapp or hangout ? (or what ever you like really !)

**Comment by srisankethu** [comment]
gitter would be nice! Thank you

**Comment by AbdealiJK** [comment]
@srisankethu Im merging this to coala - but could you please ping me on gitter regarding `git` ?

**Comment by AbdealiJK** [comment]
@rultor merge

**Comment by sils1297** [comment]
ack 7218037

**Comment by sils1297** [comment]
@AbdealiJK remember? GitMate doesn't pick up fork comments :/

**Comment by AbdealiJK** [comment]
@sils1297 thanks ! forgot about that

**Pull request merged**
