### PR TITLE
SourceRange.from_values: Allow end_line=None

### PR DESCRIPTION
**Pull request by sils1297**

### CODE REVIEW

**Comment by sils1297** [comment]
reack
02f2efa Collectors: Handle VersionConflicts in bears
27ce9e6 coalaTest: Add test when bear throws error

**Comment by sils1297** [comment]
reack f1eb9a3 Collectors: Handle VersionConflicts in bears
045e0a1 coalaTest: Add test when bear throws error

**Comment by AbdealiJK** [comment]
ack 1708f5572dc3306862e1cfaee668d761e351c443 for the parts changed by @sils1297

**Comment by AbdealiJK** [comment]
ack fdaf6f1baedf135f43c8cc7f1c879fe4b436f7e8

**Comment by sils1297** [comment]
@stevepeak codecov did a totally wrong comment here again (and still no status) ^ coverage is 100% from build logs

**Comment by sils1297** [comment]
@rultor merge , coverage is 100% manually confirmed from build log and codecov status still not avail.

**Comment by sils1297** [comment]
@rultor sometimes you're a bit simple minded :/ You could just take the first  word...

**Pull request merged**
