### PR TITLE
configs

### PR DESCRIPTION
**Pull request by AbdealiJK**

### CODE REVIEW

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
although I think this may well need a rebase

**Comment by AbdealiJK** [comment]
@rultor merge

**Comment by sils1297** [comment]
*drum roll*

**Comment by AbdealiJK** [comment]
wow, the docker image has made it much faster :)

**Comment by sils1297** [comment]
or maybe the fact that they cleaned up their disks ?

2015-07-24 14:01 GMT+02:00 AbdealiJK <notifications@github.com>:

**Comment by AbdealiJK** [comment]
did they ? I didnt know - that's cool too :)

**Comment by sils1297** [comment]
well, they must have after the "no space availbale" isue

**Pull request merged**
