### PR TITLE
BearRunning: Change succesfully -> successfully

### PR DESCRIPTION
**Pull request by windwaker**
Fixes https://github.com/coala-analyzer/coala/issues/2497

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
ack ce848d0

**Comment by tushar-rishav** [comment]
@rultor merge

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2517/commits/c97943166478f90fde13a8bd0cba08e0cab10268

**Comment by sils1297** [comment]
will be merged with https://github.com/coala-analyzer/coala/pull/2527 for simplicity

**Pull request closed without merging**
