### PR TITLE
ConsoleInteraction: Change "a" -> "A"

### PR DESCRIPTION
**Pull request by tveyben**
Fixes https://github.com/coala-analyzer/coala/issues/2503

### CODE REVIEW

**Comment by Asnelchristian** [comment]
this looks good :+1:

**Comment by Asnelchristian** [comment]
ack https://github.com/coala-analyzer/coala/pull/2516/commits/a85043951b6ec21d180ee7169f1c40eb5dcdad37

**Comment by Asnelchristian** [comment]
ack https://github.com/coala-analyzer/coala/pull/2516/commits/13688a05de48b52d407120d26d6e3d60bb30a261

**Comment by Adrianzatreanu** [comment]
The 2nd commit message shortlog requires some work. You could maybe add the file that the change is on, before the message? Like ``Filename: Change arguements->arguments`` (only for the first line)

**Comment by Adrianzatreanu** [comment]
unack 13688a0

**Comment by Adrianzatreanu** [comment]
to edit the last commit, just type git commit --amend, do the change, and push again :) the changes will be automatically applied to your PR

**Comment by Asnelchristian** [comment]
needs rebase :)

**Comment by sils1297** [comment]
Hi,

it looks like your PR is out of date and needs a rebase. [This page](http://coala.readthedocs.org/en/latest/Users/Tutorials/Git_Help.html) may help you to get started on this. (*Do not press the update branch button. It's evil.*)

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

Ping us on [our gitter channel](https://gitter.im/coala-analyzer/coala) if you need help!

**Comment by tushar-rishav** [comment]
ack https://github.com/coala-analyzer/coala/pull/2516/commits/8775d205d4d23338548b75b0802c213014ffab5b

**Comment by tushar-rishav** [comment]
@tveyben This PR just need a rebase and it's ready. :)
You just need to 
* Fetch from remote in master
* Rebase current branch on master
* Force push

**Comment by sils1297** [comment]
will be merged with https://github.com/coala-analyzer/coala/pull/2527 for simplicity

**Pull request closed without merging**
