### PR TITLE
Fixes typo #1342

### PR DESCRIPTION
**Pull request by abit2**
fixes typo of .coafile.

### CODE REVIEW

**Comment by sils1297** [comment]
@abit2 this commit needs a bit of work - don't worry, that's very usual for new people. Once you get accustomed to this it'll get really trivial for you.

So first off the commit message needs some work. We have guidelines at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages because that's a very common problem for new people.

You can change the commit message with git commit --amend locally. Also we want you to do a rebase onto the current master - ping us if you need help with that. This should also help you removing those merge commits, we don't want those in our history.

**Comment by sils1297** [comment]
unack 2d032a5 as per review

**Comment by sils1297** [comment]
@abit2 do you intend to continue working on this?

**Comment by sils1297** [comment]
need help? Ping us on gitter in that case.

**Comment by abit2** [comment]
@sils1297 Hey #1362 has been already merged with #1387 .
My midsems exam are going on, will resume to contribute after this week.

**Comment by sils1297** [comment]
ok this is not relevant anymore then, thanks

**Pull request closed without merging**
