### PR TITLE
ConsoleInteraction: Suggest installing bears

### PR DESCRIPTION
**Pull request by sils1297**
Fixes https://github.com/coala-analyzer/coala/issues/2205

### CODE REVIEW

**Comment by sils1297** [comment]
@scottbelden

**Comment by scottbelden** [comment]
ack https://github.com/coala-analyzer/coala/pull/2231/commits/cdbefa3f3c6c50b21dc53949b01c65fba1c94705

**Comment by scottbelden** [comment]
ack https://github.com/coala-analyzer/coala/pull/2231/commits/51fa1bd4a75b201d065f666fd15d80802f2af655

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
