### PR TITLE
Bear: Rename run_bear to run

### PR DESCRIPTION
**Pull request by Udayan12167**
All the tests have been changes to match the change and pass. And the run method is renamed to run_main.

### CODE REVIEW

**Comment by sils1297** [comment]
Hey Udayan,

thanks for submitting those patches! I'll now review them which is the usual process. coala's review process is the same as for GNOME modules.

It is important for you to know that if there are issues with your patches that does not at all mean you have done bad work. We appreciate every contribution and it's great you did this! (As you see my own pull request right now is in the third revision and I'm the one who wrote the codestyle guidelines and commit message guidelines.)

So please don't feel intimidated, it's just how things are done in order to get good code.

**Comment by sils1297** [comment]
Why there are two commits with exactly the same commit message?

**Comment by Udayan12167** [comment]
There was some problem while pushing i'll just delete the first commit and fix the spacing.

**Comment by sils1297** [comment]
Ah, you want to rebase your commits on our current master.

Please take a look at some forking related workflows here: https://help.github.com/articles/fork-a-repo/#step-3-configure-git-to-sync-your-fork-with-the-original-spoon-knife-repository

You will want to do a `git pull upstream --rebase` to rebase your commit on the current master of the coala main repository.

**Comment by sils1297** [comment]
I'd also suggest to not work on the master branch so you can keep your master branch synced with coalas master and then rebase your working branch on top of this.

You will need this git knowledge for the GSoC anyway so its good to learn it now.

**Comment by sils1297** [comment]
You also want to create two commits, one where you rename the run method to run_main or so and another where you rename run_bear to run. I'm also not sure if run_main is a good name.

I'm not sure if run_main is a good name, but I don't really have a better idea right now. If you have a better one, feel free to propose.

You might want to check out pycharm as python IDE. The community version is apache licensed so you can use it freely, it's a really really good IDE IMO that can handle the renaming for you at least partially automated.

**Comment by Udayan12167** [comment]
we can rename run to run_bear_main? Also i think i'll just refork the repository and submit another bugfix.

**Comment by Udayan12167** [comment]
Also what i dont get is creating seperate commits would be difficult as those commits i cant test properly as these are co dependant function?

**Comment by sils1297** [comment]
Commit message: the tag is meant to be useful. So better commit message would be something like:
```
Bear: Rename run() to execute()

We want run() to be implemented by bear writers so we need another name for this. ...
```

I assume you have read our commit message guidelines and misunderstood the tag thing. I've filed #308 for that.

So how about renaming run to execute in the first commit and run_bear to run in the second?

About forking: you really want to refork the repository whenever we change something on master? As I said, you'll need the git knowledge anyways so setting up the upstream once and then pulling from it should be far easier even if the initial time needed is higher.

Usually one wants small commits. That has several reasons:

 * Smaller changes are easier to review. Thus it is easier to assure that there are no bugs introduced in those commits.
 * Smaller changes are easier to revert. If someone finds a bug that did not exist some time before, git offers a tool that lets you find the commit that introduced the bug. The smaller the commits are, the more this helps in finding the bug in the commit.

**Comment by sils1297** [comment]
Note: I've just merged a few fixes into master so you need to rebase again. (Should be just one command.)

**Pull request closed without merging**
