### PR TITLE
Decouple bears from coalib.tests

### PR DESCRIPTION
**Pull request by AbdealiJK**

### CODE REVIEW

**Comment by AbdealiJK** [comment]
Scrutinizer needs to be ignored. @sils1297 I had some time - so, made this, push if possible

**Comment by sils1297** [comment]
ack
2c1130f deps: Remove Goopfile
15d813e conftest: Check if coverage is installed
452ce20 coalaCITest: Remove dependency on bears module
18a27c4 coala_bears_test_module: Add SpaceConsistency
707fbc9 coalaTest: Install test bears module and test
64bc72a TestUtilities: Add helpers to use test module
792cf98 coalib/tests: Add module coala_bears_test_module
12ed328 ConsolInteractionTest: Remove bears dependency
5be2814 DiffTest: Remove dependency on clang
1e19178 LintTest: Remove IndentBear dependency

**Comment by sils1297** [comment]
@rultor merge

**Comment by ravinimmi** [comment]
@AbdealiJK this commit is failing scrutinizer check.

**Comment by AbdealiJK** [comment]
@ravinimmi Yes, but it is an unavoidable issue so we decided to ignore that for now

**Comment by ravinimmi** [comment]
@AbdealiJK But this is causing my [PR](https://github.com/coala-analyzer/coala/pull/1627) to fail. Could you review?

**Pull request merged**
