### PR TITLE
DOC: Explain Bears and their kinds

### PR DESCRIPTION
**Pull request by souravsingh**

### CODE REVIEW

**Comment by souravsingh** [comment]
The PR is related to #1630

**Comment by Makman2** [comment]
Hi @souravsingh :)
Looks like this is your first contribution to our repository, I would suggest you reading http://coala.readthedocs.org/en/latest/Getting_Involved/README.html where we cover the basics how we handle stuff here :D
As you might have seen we have a review process where a maintainer looks at your code before it gets merged, I will do this now :)

**Comment by Makman2** [comment]
As you see we also use continuous-integration, and the tests do fail. This is because of the codestyle violations you can already see as comments in this PR. These need to get fixed too^^

**Comment by tushar-rishav** [comment]
@souravsingh Hey. You're almost there. Just need to implement a few changes before we can accept your PR. Please follow these points :

- [Commit guidelines](http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html)
- Before sending PR, just run `coala` in your local fork. `coala` will essentially fix/reveal some of the important bugs. 
Hope to see your PR again. :D

**Comment by souravsingh** [comment]
Thanks for the PR review @Makman2

**Comment by sils1297** [comment]
@Adrianzatreanu where was this resolved?

**Comment by sils1297** [comment]
ah it's a PR, @Adrianzatreanu if you close things please always give a reason

**Pull request closed without merging**
