### PR TITLE
add coalangs

### PR DESCRIPTION
**Pull request by abhsag24**

### CODE REVIEW

**Comment by fneu** [comment]
ack https://github.com/coala-analyzer/coala/pull/2510/commits/5d3466821af73c13148474480c19b595f180a1f https://github.com/coala-analyzer/coala/pull/2510/commits/9be24560c68145382c4fe1a8f7da377f8a285d9 https://github.com/coala-analyzer/coala/pull/2510/commits/0f54bb40f00812538e6a962b18ffc8c88091da3 https://github.com/coala-analyzer/coala/pull/2510/commits/76f1318409bd3b8acae10d90cc65b5c2768b7abd0c9

**Comment by fneu** [comment]
ack https://github.com/coala-analyzer/coala/pull/2510/commits/76f1318409bd3b8acae10d90cc65b5c2768b7abd

**Comment by fneu** [comment]
reack https://github.com/coala-analyzer/coala/pull/2510/commits/76f1318409bd3b8acae10d90cc65b5c2768b7abd

**Comment by fneu** [comment]
I have no idea why, but reacks works better than ack sometimes... ?

**Comment by fneu** [comment]
@rultor merge

**Comment by fneu** [comment]
@rultor merge

**Comment by abhsag24** [comment]
reack 22c0553,1bff882,461055f, a680299

**Comment by abhsag24** [comment]
reack a680299

**Comment by abhsag24** [comment]
@rultor merge

**Comment by abhsag24** [comment]
@fneu rultor listens to me! XD

**Comment by fneu** [comment]
Yes wtf. Well I guess I was too tired to assert real dominance over it.

**Pull request merged**
