### PR TITLE
Core.py: Fix typo, escaped -> escape

### PR DESCRIPTION
**Pull request by yufw**
Fix https://github.com/coala-analyzer/coala/issues/1772

### CODE REVIEW

**Comment by AbdealiJK** [comment]
@yufw Hi !

Please take a look at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html and modifyt he commit message as mentioned there.

If you need help in figuring out how to modify commit messages take a look at http://coala.readthedocs.org/en/latest/Getting_Involved/Newcomers.html and http://coala.readthedocs.org/en/latest/Users/Tutorials/Git_Help.html

**Comment by sudheesh001** [comment]
Retriggered the build because the failure seemed unrelated.

**Comment by sudheesh001** [comment]
@yufw Looks good but maybe we can do better on the commit message ? Rather than the function can you specify which file instead the change has been made and instead of `Fix typo` specify a clearer message ?

**Comment by sudheesh001** [comment]
unack b1d25f3

**Comment by sils1297** [comment]
hey, do not press the update branch button @Adrianzatreanu that should go into the newcomer tutorial as well I guess

**Comment by yufw** [comment]
Is there a way to undo it?

**Comment by sils1297** [comment]
http://coala.readthedocs.org/en/latest/Users/Tutorials/Git_Help.html#useful-git-commands gt rebase -i

**Comment by yufw** [comment]
Thanks, I have rebased my commit.

**Comment by AbdealiJK** [comment]
ack fd29de8

**Comment by AbdealiJK** [comment]
Ahh, this it not up to date yet !

So, the rebase hasn't happened

**Comment by yufw** [comment]
I just updated the branch again and rebased my commit, now it's up to date.

**Comment by AbdealiJK** [comment]
ack d545772

**Comment by AbdealiJK** [comment]
Awesome. looks great. Will merge it when the tests pass

**Comment by AbdealiJK** [comment]
@rultor merge

**Pull request merged**
