### PR TITLE
bears: Add HaskellLint bear

### PR DESCRIPTION
**Pull request by Redridge**
Fixes https://github.com/coala-analyzer/coala/issues/1565

### CODE REVIEW

**Comment by sils1297** [comment]
FWIW the problem definitely lies in the test, not in the bear as the bear works:

```
test.hs
|   1| myconcat a b = ((++) a b)
|    | [INFO] HaskellLintBear:
|    | Redundant bracket
|    | The following actions are applicable to this result:
|    |  0: Apply no further actions.
|    |  1: Open the affected file(s) in an editor.
|    |  2: Apply the patch automatically.
|    |  3: Print a diff of the patch that would be applied.
|    | Please enter the number of the action you want to execute. 3
|----|    | /home/lasse/prog/coala/test.hs
|    |++++| /home/lasse/prog/coala/test.hs
|   1|    |-myconcat a b = ((++) a b)
|    |   1|+myconcat a b = (++) a b
|    | Displayed patch successfully.
|    | The following actions are applicable to this result:
|    |  0: Apply no further actions.
|    |  1: Open the affected file(s) in an editor.
|    |  2: Apply the patch automatically.
|    |  3: Print a diff of the patch that would be applied.
|    | Please enter the number of the action you want to execute. 
```

**Comment by sils1297** [comment]
hey, this fixes your test:

```diff
diff --git a/bears/tests/haskell/HaskellLintBearTest.py b/bears/tests/haskell/HaskellLintBearTest.py
index 320a765..c9f7d9c 100644
--- a/bears/tests/haskell/HaskellLintBearTest.py
+++ b/bears/tests/haskell/HaskellLintBearTest.py
@@ -10,11 +10,11 @@ myconcat a b = ((++) a b)
 """.split("\n")
 
 HaskellLintBear1Test = verify_local_bear(HaskellLintBear,
-                                         valid_files=(good_file),
+                                         valid_files=(good_file,),
                                          invalid_files=(),
                                          tempfile_kwargs={"suffix": ".hs"})
 
 HaskellLintBear2Test = verify_local_bear(HaskellLintBear,
                                          valid_files=(),
-                                         invalid_files=(bad_file),
+                                         invalid_files=(bad_file,),
                                          tempfile_kwargs={"suffix": ".hs"})
```

**Comment by Redridge** [comment]
I didn't think the comma actually had a role if there was only one file, fixing it

**Comment by sils1297** [comment]
it has, it makes the distinction between a tuple of things and just
redundant brackets around a thing.

2016-02-19 10:49 GMT+01:00 Alexandros Dimos <notifications@github.com>:

**Comment by sils1297** [comment]
ack 36ddc557e5

**Comment by sils1297** [comment]
ack 64483bc16c21

**Comment by AbdealiJK** [comment]
unack  44f6846
ack a647e05
Rebase needed

**Comment by Redridge** [comment]
I think there is no need to build this anymore.

**Comment by sils1297** [comment]
@Redridge please move the PR to https://github.com/coala-analyzer/coala-bears , then close this

**Comment by Redridge** [comment]
Moved to https://github.com/coala-analyzer/coala-bears/pull/17

**Pull request closed without merging**
