### PR TITLE
Update Dependencies.py

### PR DESCRIPTION
**Pull request by shubhamrajput**
a generator expression shortening the code

### CODE REVIEW

**Comment by sils1297** [comment]
unack 29bb276, needs work.

**Comment by sils1297** [comment]
Also please amend your commit, we'd prefer you to not reopen a new PR for each new version. You can use `git commit --amend` for changing the message and then `git push --force` to override the existing commits. (Hint: do not use the force push on any master branch, this is intended for your own WIP branches only since it changes the git history.)

**Comment by sils1297** [comment]
@shubhamrajput do you need any help?

**Comment by shubhamrajput** [comment]
yes .. my pull request was not successful .. it shows   "This commit needs work."

**Comment by sils1297** [comment]
@shubhamrajput because I wrote the `unack` comment, that just means you have to address my comments :)

**Comment by shubhamrajput** [comment]
so what should i do now...

**Comment by sils1297** [comment]
just checkout your branch on your git repository, run `git commit --amend`, then you can change your commit message, you can push it onto this branch with `git push --force`

**Comment by sils1297** [comment]
I'm just assuming this one is superseded by https://github.com/coala-analyzer/coala/pull/1306

**Pull request closed without merging**
