### PR TITLE
README: Embed asciinema

### PR DESCRIPTION
**Pull request by SanketDG**
Fixes https://github.com/coala-analyzer/coala/issues/2052

### CODE REVIEW

**Comment by AbdealiJK** [comment]
I can;t see it in the README preview from github

**Comment by SanketDG** [comment]
Tried two things:

- Use `..raw html`
- Set `:width:`

Both didn't work.

**Comment by sickill** [comment]
The browser is showing the image in full width (because it doesn't have width specified), expanding the container. It's enough to set `width="100%"` on the `img` tag to fix this.

**Comment by sils1297** [comment]
@sickill thanks for the hint! We'll look into it.

**Comment by AbdealiJK** [comment]
Closing this and trying it out myself

**Pull request closed without merging**
