### PR TITLE
Escaping functions

### LINKED ISSUE #160: parsing: escaping/seperating functions contain duplicate code

### PR DESCRIPTION
**Pull request by Makman2**
The long awaited regex functions that automatically escape (or not escape) characters.

Fixes #160.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/coala-analyzer/coala/pull/357%23issuecomment-77102286%22%2C%20%22https%3A//github.com/coala-analyzer/coala/pull/357%23issuecomment-77102526%22%2C%20%22https%3A//github.com/coala-analyzer/coala/commit/7738a038691d814e6ccd85251c2fbcc76835db14%23commitcomment-10022785%22%2C%20%22https%3A//github.com/coala-analyzer/coala/commit/01db6ae6d107e995350c51cd3c49c39a41cb9ca4%23commitcomment-10022802%22%2C%20%22https%3A//github.com/coala-analyzer/coala/commit/01db6ae6d107e995350c51cd3c49c39a41cb9ca4%23commitcomment-10022822%22%2C%20%22https%3A//github.com/coala-analyzer/coala/commit/01db6ae6d107e995350c51cd3c49c39a41cb9ca4%23commitcomment-10022834%22%2C%20%22https%3A//github.com/coala-analyzer/coala/commit/01db6ae6d107e995350c51cd3c49c39a41cb9ca4%23commitcomment-10034759%22%2C%20%22https%3A//github.com/coala-analyzer/coala/pull/357%23issuecomment-77206703%22%2C%20%22https%3A//github.com/coala-analyzer/coala/pull/357%23issuecomment-77207041%22%2C%20%22https%3A//github.com/coala-analyzer/coala/pull/357%23issuecomment-77207326%22%2C%20%22https%3A//github.com/coala-analyzer/coala/pull/357%23issuecomment-77208504%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/coala-analyzer/coala/pull/357%23issuecomment-77102286%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22you%20sure%2C%20you%20want%20to%20submit%20that%20for%20review%3F%20You%20e.g.%20have%20two%20commits%20with%20the%20same%20message%20in%20it.%5Cr%5Cn%5Cr%5CnAlso%20as%20I%20mentioned%20on%20gitter%2C%20you%20want%20to%20add%20tests%20in%20the%20same%20commit%20where%20you%20add%20functionailty.%22%2C%20%22created_at%22%3A%20%222015-03-04T06%3A07%3A33Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5716520%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/sils1297%22%7D%7D%2C%20%7B%22body%22%3A%20%22having%20small%20and%20concise%20commits%20is%20meant%20for%20maximum%20code%20quality%2C%20not%20for%20mirroring%20how%20the%20code%20was%20created.%20%28There%20are%20other%20workflows%20that%20optimize%20for%20that.%29%20So%20you%20don%27t%20want%20to%20have%20%60fix%20this%20and%20that%60%20commits%20in%20it%20when%20you%27re%20creating%20new%20stuff.%20You%20can%20mention%20potential%20bugs%20but%20the%20best%20you%20can%20do%20to%20highlight%20them%20is%20adding%20a%20test%20for%20exactly%20the%20cases%20where%20you%20failed%20in%20the%20first%20place%20because%20that%27s%20where%20others%20may%20fail%20too%20when%20they%27re%20trying%20to%20rewrite%20something.%5Cr%5Cn%5Cr%5CnAs%20for%20me%20I%20usually%20don%27t%20want%20to%20care%20on%20what%20branch%20or%20in%20which%20order%20a%20code%20was%20developed.%20I%20usually%20want%20to%20easily%20be%20able%20to%20say%20that%20there%20are%20no%20bugs%20in%20it.%22%2C%20%22created_at%22%3A%20%222015-03-04T06%3A11%3A05Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5716520%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/sils1297%22%7D%7D%2C%20%7B%22body%22%3A%20%22Thought%20so%2C%20but%20I%20tried%20to%20hand%20it%20to%20you%20as%20finished%20%3Apackage%3A%20%5Cr%5CnAs%20you%20see%20there%20was%20quite%20much%20to%20do.%5Cr%5CnSo%20I%20would%20copy%20the%20branch%20and%20make%20a%20v2%20of%20it.%20How%20did%20you%20do%20that%20with%20your%20pull%20requests%3F%22%2C%20%22created_at%22%3A%20%222015-03-04T17%3A42%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6023916%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Makman2%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20just%20branched%20off%20a%20v2%20and%20edited%20commit%20and%20pushed%20up.%22%2C%20%22created_at%22%3A%20%222015-03-04T17%3A43%3A36Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5716520%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/sils1297%22%7D%7D%2C%20%7B%22body%22%3A%20%22hey%2C%20this%20code%20review%20tool%20even%20gives%20you%20a%20task%20list%20out%20of%20my%20comments%20%3A%29%22%2C%20%22created_at%22%3A%20%222015-03-04T17%3A44%3A58Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5716520%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/sils1297%22%7D%7D%2C%20%7B%22body%22%3A%20%22But%20it%20doesn%27t%20look%20so%20good%5E%5E%22%2C%20%22created_at%22%3A%20%222015-03-04T17%3A50%3A33Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6023916%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Makman2%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%2C%20%22Commit%2001db6ae6d107e995350c51cd3c49c39a41cb9ca4%20coalib/parsing/StringProcessing.py%2012%2047%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/coala-analyzer/coala/commit/01db6ae6d107e995350c51cd3c49c39a41cb9ca4%23commitcomment-10022802%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22It%27s%20very%20obvious%20that%20it%27s%20optional%2C%20isn%27t%20it%3F%22%2C%20%22created_at%22%3A%20%222015-03-04T06%3A02%3A20Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5716520%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/sils1297%22%7D%7D%2C%20%7B%22body%22%3A%20%22you%20don%27t%20specify%20return%20value%20by%20the%20way%20and%20thats%20most%20importtant%20here%20because%20you%20could%20do%20that%20in%20various%20ways.%22%2C%20%22created_at%22%3A%20%222015-03-04T06%3A05%3A13Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5716520%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/sils1297%22%7D%7D%2C%20%7B%22body%22%3A%20%22damn%20completely%20forgot.%20That%27s%20the%20thing%20if%20you%20don%27t%20have%20return%20types%20in%20the%20declaration...%22%2C%20%22created_at%22%3A%20%222015-03-04T17%3A39%3A26Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6023916%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Makman2%22%7D%7D%5D%2C%20%22title%22%3A%20%22File%3A%20coalib/parsing/StringProcessing.py%3AL47%20%2801db6ae%29%22%7D%2C%20%22Commit%2001db6ae6d107e995350c51cd3c49c39a41cb9ca4%20coalib/parsing/StringProcessing.py%2019%2054%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/coala-analyzer/coala/commit/01db6ae6d107e995350c51cd3c49c39a41cb9ca4%23commitcomment-10022822%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%60rxc%60%20is%20a%20bad%20name.%20In%20this%20line%20I%20know%20what%20it%20means%20but%20if%20I%27m%20scanning%20the%20function%20fastly%20to%20grasp%20its%20functionality%20or%20so%20I%20would%20need%20to%20look%20up%20the%20declaration%20to%20see%20what%20it%20means.%20IMO%20you%20could%20be%20a%20bit%20more%20verbose.%20rxc%20is%20also%20not%20a%20common%20abbreviation.%22%2C%20%22created_at%22%3A%20%222015-03-04T06%3A04%3A09Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5716520%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/sils1297%22%7D%7D%5D%2C%20%22title%22%3A%20%22File%3A%20coalib/parsing/StringProcessing.py%3AL54%20%2801db6ae%29%22%7D%2C%20%22Commit%207738a038691d814e6ccd85251c2fbcc76835db14%20coalib/parsing/StringProcessing.py%208%208%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/coala-analyzer/coala/commit/7738a038691d814e6ccd85251c2fbcc76835db14%23commitcomment-10022785%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22I%27d%20expect%20a%20newline%20after%20short%20description.%20%28Our%20documentation%20parser%20does%20expect%20that%20too%2C%20markdown%20like.%29%22%2C%20%22created_at%22%3A%20%222015-03-04T06%3A01%3A00Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5716520%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/sils1297%22%7D%7D%5D%2C%20%22title%22%3A%20%22File%3A%20coalib/parsing/StringProcessing.py%3AL8%20%287738a03%29%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-Commit 7738a038691d814e6ccd85251c2fbcc76835db14 coalib/parsing/StringProcessing.py 8 8'></a> &nbsp;<b><a href='https://github.com/coala-analyzer/coala/commit/7738a038691d814e6ccd85251c2fbcc76835db14#commitcomment-10022785'>File: coalib/parsing/StringProcessing.py:L8 (7738a03)</a></b>
- <a href='https://github.com/sils1297'></a> I'd expect a newline after short description. (Our documentation parser does expect that too, markdown like.)
- [ ] <a href='#crh-comment-Commit 01db6ae6d107e995350c51cd3c49c39a41cb9ca4 coalib/parsing/StringProcessing.py 12 47'></a> &nbsp;<b><a href='https://github.com/coala-analyzer/coala/commit/01db6ae6d107e995350c51cd3c49c39a41cb9ca4#commitcomment-10022802'>File: coalib/parsing/StringProcessing.py:L47 (01db6ae)</a></b>
- <a href='https://github.com/sils1297'></a> It's very obvious that it's optional, isn't it?
- <a href='https://github.com/sils1297'></a> you don't specify return value by the way and thats most importtant here because you could do that in various ways.
- <a href='https://github.com/Makman2'></a> damn completely forgot. That's the thing if you don't have return types in the declaration...
- [ ] <a href='#crh-comment-Commit 01db6ae6d107e995350c51cd3c49c39a41cb9ca4 coalib/parsing/StringProcessing.py 19 54'></a> &nbsp;<b><a href='https://github.com/coala-analyzer/coala/commit/01db6ae6d107e995350c51cd3c49c39a41cb9ca4#commitcomment-10022822'>File: coalib/parsing/StringProcessing.py:L54 (01db6ae)</a></b>
- <a href='https://github.com/sils1297'></a> `rxc` is a bad name. In this line I know what it means but if I'm scanning the function fastly to grasp its functionality or so I would need to look up the declaration to see what it means. IMO you could be a bit more verbose. rxc is also not a common abbreviation.
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/coala-analyzer/coala/pull/357#issuecomment-77102286'>General Comment</a></b>
- <a href='https://github.com/sils1297'></a> you sure, you want to submit that for review? You e.g. have two commits with the same message in it.
Also as I mentioned on gitter, you want to add tests in the same commit where you add functionailty.
- <a href='https://github.com/sils1297'></a> having small and concise commits is meant for maximum code quality, not for mirroring how the code was created. (There are other workflows that optimize for that.) So you don't want to have `fix this and that` commits in it when you're creating new stuff. You can mention potential bugs but the best you can do to highlight them is adding a test for exactly the cases where you failed in the first place because that's where others may fail too when they're trying to rewrite something.
As for me I usually don't want to care on what branch or in which order a code was developed. I usually want to easily be able to say that there are no bugs in it.
- <a href='https://github.com/Makman2'></a> Thought so, but I tried to hand it to you as finished :package:
As you see there was quite much to do.
So I would copy the branch and make a v2 of it. How did you do that with your pull requests?
- <a href='https://github.com/sils1297'></a> I just branched off a v2 and edited commit and pushed up.
- <a href='https://github.com/sils1297'></a> hey, this code review tool even gives you a task list out of my comments :)
- <a href='https://github.com/Makman2'></a> But it doesn't look so good^^

<a href='https://www.codereviewhub.com/coala-analyzer/coala/pull/357?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/coala-analyzer/coala/pull/357?approve=1'></a>&nbsp;<a href='https://github.com/coala-analyzer/coala/pull/357'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/coala-analyzer/coala/pull/357" target="_blank">ReviewNinja

**Comment by sils1297** [comment]
you sure, you want to submit that for review? You e.g. have two commits with the same message in it.

Also as I mentioned on gitter, you want to add tests in the same commit where you add functionailty.

**Comment by sils1297** [comment]
having small and concise commits is meant for maximum code quality, not for mirroring how the code was created. (There are other workflows that optimize for that.) So you don't want to have `fix this and that` commits in it when you're creating new stuff. You can mention potential bugs but the best you can do to highlight them is adding a test for exactly the cases where you failed in the first place because that's where others may fail too when they're trying to rewrite something.

As for me I usually don't want to care on what branch or in which order a code was developed. I usually want to easily be able to say that there are no bugs in it.

**Comment by Makman2** [comment]
Thought so, but I tried to hand it to you as finished :package: 
As you see there was quite much to do.
So I would copy the branch and make a v2 of it. How did you do that with your pull requests?

**Comment by sils1297** [comment]
I just branched off a v2 and edited commit and pushed up.

**Comment by sils1297** [comment]
hey, this code review tool even gives you a task list out of my comments :)

**Comment by Makman2** [comment]
But it doesn't look so good^^

**Comment by Makman2** [comment]
This pull request was taken over from #364.

**Comment by Makman2** [comment]
Don't delete branch until #364 is merged!

**Pull request closed without merging**
