### PR TITLE
Add a link to bears-doc in the `Sections` section.

### PR DESCRIPTION
**Pull request by wulmer**

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
so the change is cool now :D but the commit would use some improvement.

The format we use around coala is:

``File the change is on: Imperative mood with the change``

so here it would be something like:

``Tutorial: Add link to bear-docs``

**Comment by Adrianzatreanu** [comment]
to not create a new commit and edit the previous one, simply do the changes, ``git add`` the file, and then type ``git commit --amend``, and push again :) it will rewrite your last commit :)

**Comment by wulmer** [comment]
Hm... I tried exactly the same (using `git commit --amend`) before in my last PR, however that somehow broke everything..... I feel like I am learning a low new stuff about Git today ;-)

**Comment by Adrianzatreanu** [comment]
ack 9c87ab3

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Pull request merged**
