### PR TITLE
Constants.py: Remove coalib_bears_root

### PR DESCRIPTION
**Pull request by vidhan13j07**
Fixes https://github.com/coala-analyzer/coala/issues/1646

Constants.py: Remove coalib_bears_root

Fixes https://github.com/coala-analyzer/coala/issues/1646

Constants.py: Remove coalib_bears_root

Fixes https://github.com/coala-analyzer/coala/issues/1646

### CODE REVIEW

**Comment by AbdealiJK** [comment]
unack df2b58b

**Comment by AbdealiJK** [comment]
ack 16fdb2e
This is ready

**Comment by AbdealiJK** [comment]
ack 16fdb2e

**Comment by AbdealiJK** [comment]
ack 16fdb2eaeb55160eace5724f00e757d305f7b0dc

@sils1297 it seems as if gitmate stopped running

**Comment by sils1297** [comment]
ack 16fdb2e

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
