### PR TITLE
release!

### PR DESCRIPTION
**Pull request by sils1297**

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
ack d5e37a7

**Comment by Adrianzatreanu** [comment]
ack 5f993cb

**Comment by Adrianzatreanu** [comment]
ack a68a2cb

**Comment by sils1297** [comment]
reack  	@sils1297 	RELEASE_NOTES: Add missing newlines … 	
f06341e
	@sils1297 	Release 0.5.0 	
bbf60f2
	@sils1297 	VERSION: Bump up to development 	
206ba88

**Comment by sils1297** [comment]
reack f06341e bbf60f2 206ba88

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
