### PR TITLE
coalang: Add keywords and special characters

### PR DESCRIPTION
**Pull request by hypothesist**
Add keywords and special characters for C and C++
Also added two new routines in coalang LanguageDefinition
that are useful.

### CODE REVIEW

**Comment by sils1297** [comment]
unack 06908aa also please rebase while you're at it

**Comment by hypothesist** [comment]
@sils1297 yeah, I understood the gitter message ;) Amending

**Comment by sils1297** [comment]
alright can you rebase?

**Comment by sils1297** [comment]
ack 866014ad

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
