### PR TITLE
tests: Make run_tests.py work with virtualenv

### PR DESCRIPTION
**Pull request by Uran198**
Fixes https://github.com/coala-analyzer/coala/issues/1217

### CODE REVIEW

**Comment by sils1297** [comment]
Also this needs a rebase onto current master :)

**Comment by Uran198** [comment]
@sils1297 although you don't follow pep8 in your tests, I wrote it this way because of pep8 E731. Also, it's more explicit and readable in my opinion.

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
Rultor is havin' a *bad day* today...

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
