### PR TITLE
ConfWriter: Write newlines before sections

### PR DESCRIPTION
**Pull request by sils1297**
However don't repeat them if already present.

Fixes: https://github.com/coala-analyzer/coala/issues/274

### CODE REVIEW

**Comment by sils1297** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/coala-analyzer/coala/pull/362'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by sils1297** [comment]
that was an easy fix :(

**Comment by Makman2** [comment]
Doesn't work under my VM. Sections still not separated with \n and I get an exception (when using the first save command from the coala tutorial):

```
coala -S TEST.A=A TEST.B=Makefile --save

Executing section Default...
[ERROR][17:06:46] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:

Exception was:
Traceback (most recent call last):

  File "../coala/coala", line 42, in <module>
    local_bear_list=local_bears[section_name]).run()

  File "/home/mak/dev/coala/coalib/processes/SectionExecutor.py", line 78, in run
    processes, arg_dict = self._instantiate_processes(running_processes)

  File "/home/mak/dev/coala/coalib/processes/SectionExecutor.py", line 145, in _instantiate_processes
    filename_list = collect_files(path_list(self.section['files']))

  File "/home/mak/dev/coala/coalib/settings/Section.py", line 154, in __getitem__
    return self.defaults[key]

  File "/home/mak/dev/coala/coalib/settings/Section.py", line 152, in __getitem__
    raise IndexError("Required index is unavailable.")

IndexError: Required index is unavailable.
```

I installed the right version and to be sure, I invoked coala directly from the repo (on the right branch).

`cat .coafile` serves me that the [DEFAULT] section is empty:
```
[Default]
[Makefiles]
bears = LineLengthBear
files = Makefile
max_line_length = 80
[TEST]
A = A
B = Makefile
```
Added separately a [TEST] section to see if newlines are written, but seems not^^

**Comment by sils1297** [comment]
Thanks! I'll investigate that. I wonder why the test works then...

2015-03-05 17:10 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by sils1297** [comment]
thats actually a bug that got into master with the last bunch of commit
from me.

2015-03-05 17:11 GMT+01:00 Lasse Schuirmann <lasse.schuirmann@gmail.com>:

**Comment by sils1297** [comment]
That was introduced in commit b859894ddde7f10a936c0d0f3f08018147030044.

2015-03-05 19:30 GMT+01:00 Lasse Schuirmann <lasse.schuirmann@gmail.com>:

**Comment by sils1297** [comment]
I reverted that commit on master so I need to include it here again.

2015-03-05 19:32 GMT+01:00 Lasse Schuirmann <lasse.schuirmann@gmail.com>:

**Comment by sils1297** [comment]
@Makman2 please try again, this includes the fix for the empty default_coafile now

**Comment by Makman2** [comment]
The bug vanished, so the sections are properly executed and saved, but not with newlines :)

**Comment by Makman2** [comment]
So it looks again like this:
```
[Default]
[SECTION]
a = 1
b = sb
[BETA]
alpha = 0
beta = 1
```

**Comment by Makman2** [comment]
And interestingly the execution of the other non-default sections takes quite long^^

**Comment by Makman2** [comment]
Oh damn never mind, I was the whole time on master.
I blame myself :O

**Comment by Makman2** [comment]
never mind never mind, I was on this branch xD

**Comment by sils1297** [comment]
@Makman2 could you review the first two commits until then? Thats what I reverted on master.

**Comment by sils1297** [comment]
@Makman2 everything's fixed!

**Comment by Makman2** [comment]
Everything okay, but
- No \n at end of file
- Now when creating a coafile (so `.coafile` doesn't exist first) it throws me a warning that it is not used, but the sections are all properly executed.

**Comment by sils1297** [comment]
no `\n` at end of which file?

**Comment by sils1297** [comment]
> Now when creating a coafile (so .coafile doesn't exist first) it throws me a warning that it is not used, but the sections are all properly executed.

could you file a bug? this was introduced by some other commit which is already on master IIRC.

**Comment by Makman2** [comment]
Open at #367

**Comment by Makman2** [comment]
forget about \n, it is written at EOF^^

**Comment by sils1297** [comment]
merged

**Pull request closed without merging**
