### PR TITLE
abhsag/cherrypick

### PR DESCRIPTION
**Pull request by abhsag24**

### CODE REVIEW

**Comment by abhsag24** [comment]
reack c76447b, 564dca6

**Comment by sils1297** [comment]
reack https://github.com/coala-analyzer/coala/pull/2140/commits/564dca69c6f0b859e2816dfe29d5ed0d59906514

**Comment by sils1297** [comment]
@rultor merge

**Comment by abhsag24** [comment]
@rultor merge :)

**Pull request merged**
