### PR TITLE
Code Conventions

### PR DESCRIPTION
**Pull request by keerthisuresh**
LineLengthBear : Documentation Spacing
Fixes https://github.com/coala-analyzer/coala/issues/947

### CODE REVIEW

**Comment by sils1297** [comment]
Hi @keerthisuresh can you rebase it again? Are you working with several remotes? I've seen you reforking coala in the activity logs, there's an easier way: try `git remote add coala https://github.com/coala-analyzer/coala/ && git pull coala master --rebase`, that should rebase your commit onto the coala master.

Can you also do a `git commit --amend` to change the commit message? Something like `LineLengthBear: Documentation alignment`, what you have in the second line, would be good for the first line. http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages in case you want to look it up.

Let me know if you need more help, we're getting to it :) I'm sorry you have to rebase again and again, we're currently merging a lot of stuff so we're to blame for that...

**Comment by sils1297** [comment]
oh and ignore the scrutinizer failure, they suck ;) that's why we're currently writing gitmate.

**Comment by sils1297** [comment]
Ok, github shows you still need a rebase, did you do the pull? (Could you redo it?) The commit is good and I can merge it after the rebase :)

**Comment by keerthisuresh** [comment]
redid the pull and rebased it

**Comment by sils1297** [comment]
@keerthisuresh then `git push --force` it to your branch again

**Comment by keerthisuresh** [comment]
pushed

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@keerthisuresh FYI, rultor is our merge bot, he'll also automatically release the stuff as a development release on PyPI :)

**Comment by sils1297** [comment]
@keerthisuresh hey, congrats, you got your first commit merged :)

**Pull request merged**
