### PR TITLE
Change development status to beta

### PR DESCRIPTION
**Pull request by CruiseDevice**

### CODE REVIEW

**Comment by AbdealiJK** [comment]
@CruiseDevice do you need any help with this ?

**Comment by CruiseDevice** [comment]
@AbdealiJK Well, i am confused with git. last time i was not able to push the code correctly, that's because i was confused with branches. Yes i need help cause its confusing in here while push the code.

**Comment by sils1297** [comment]
@CruiseDevice can you drop by at the gitter channel? then I'll help you there.

**Comment by sils1297** [comment]
superseded by https://github.com/coala-analyzer/coala/pull/1430

**Pull request closed without merging**
