### PR TITLE
docs: Add docker container page

### PR DESCRIPTION
**Pull request by sils1297**
Closes https://github.com/coala-analyzer/docker-coala-base/issues/9

CC @stefanoco if you want I can set you as author, for that I need your `Full Name <email@addesss>`

### CODE REVIEW

**Comment by stefanoco** [comment]
@sils1297 "Stefano Costa" <stefano.costa@bluewind.it> thanks

**Comment by sils1297** [comment]
@stefanoco updated author info. Is the doc page good as it is or did I compress too much?

**Comment by stefanoco** [comment]
It's ok, perfect for me.

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2362/commits/93da64190db8a6220a42e3f0562fd1b06acab742 then

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
