### PR TITLE
tests: Shorten output

### PR DESCRIPTION
**Pull request by sils1297**
One can get verbose output through passing the -v argument. If this
doesn't meet your needs because you need the ordering between
stderr/stdout you are encouraged to execute your test manually for
debugging.

### CODE REVIEW

**Comment by sils1297** [comment]
Isn't that a nice output?
http://pastebin.com/6TgJxgT0

**Comment by smfn3321** [comment]
Slick, but is it as verbose as the current configuration if a test fails?

Also, is there a way to show line numbers for missing branches? Sometimes it's really hard to track them down especially if all statements are covered.

**Comment by sils1297** [comment]
Non-verbose output: http://pastebin.com/DG9L0Ciq
With a failure: http://pastebin.com/2syW4Dny

**Comment by sils1297** [comment]
Its as verbose as before. Only difference is that if you have something from stderr and stdout it will be seperated. E.g. the "test_non_printing (__main__.NullPrinterTestCase) ... ERROR" lines go through stderr, the test output usually goes through stdout.

**Pull request merged**
