### PR TITLE
Show relative path in results output

### PR DESCRIPTION
**Pull request by abhsag24**
related to coala-analyzer #1124

Shows relative path in the results, does not have an option(as of now) to show absolute paths.

### CODE REVIEW

**Comment by GitCop** [comment]
The commit message

 * Commit: b2d8ebd2cf9e6d7debb767b3f18c4b6da3d1b683
  * Commits must be in the following format: **%{scope}: %{description}**

Guidelines are available at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
The commit message

 * Commit: b2d8ebd2cf9e6d7debb767b3f18c4b6da3d1b683
  * Commits must be in the following format: **%{scope}: %{description}**

Guidelines are available at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
The commit message

 * Commit: b2d8ebd2cf9e6d7debb767b3f18c4b6da3d1b683
  * Commits must be in the following format: **%{scope}: %{description}**

Guidelines are available at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages

---
This message was auto-generated by https://gitcop.com

**Comment by sils1297** [comment]
@abhsag24 hey please don't press GitHub's "Update branch" button, it results in an extremely messy history and sadly you can't do anything to disable it. Instead, we'd love it if you rebase your branch onto our current master. Do you need help with that?

**Comment by abhsag24** [comment]
ok, i'll rebase the branch

**Comment by GitCop** [comment]
The commit message

 * Commit: 952fdaee13bf71a625c36dbcb9bf539eb60032dd
  * Commits must be in the following format: **%{scope}: %{description}**

Guidelines are available at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages

---
This message was auto-generated by https://gitcop.com

**Comment by sils1297** [comment]
Hey as pointed out by GitMate you have a line that's too long, can you break that? That should also fix your tests on linux. (Point of this excercise is to get all those little checks to green because if it's not green you probably have a bug in there :)).

**Comment by abhsag24** [comment]
on it :)

**Comment by GitCop** [comment]
The commit message

 * Commit: 952fdaee13bf71a625c36dbcb9bf539eb60032dd
  * Commits must be in the following format: **%{scope}: %{description}**

 * Commit: d40838527eabc3f0879e4050fd7286aebbc2d2a8
  * Commits must be in the following format: **%{scope}: %{description}**

Guidelines are available at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages

---
This message was auto-generated by https://gitcop.com

**Comment by sils1297** [comment]
@abhsag24 hey, so when you correct something we usually want you to amend the commit or use `git rebase --interactive` to squash commits. Just like with the rebase we do that so we get a clean history as we don't want to have all those `I forgot this` and `I forgot that` commits in there : ) More info about that kind of workflow is available here: http://coala.readthedocs.org/en/latest/Getting_Involved/Review/ .

Second, the commit message. It would be nice if you could add some tag (GitCop names it `%{scope}`) to give some context, if you are working in one file only the filename (without .py) usually serves a good context so when I read the commit message I immediately know what it is about.

Third, you see there's one check which is failing, right? That's appveyor which runs on windows. You can see the failure if you click on details. https://ci.appveyor.com/project/sils1297/coala/build/1.0.2506/job/eeko1opic2ysj17p#L133 - apparently `relpath` transforms the `proj/white` into `proj\white` on windows because it does some path normalization. Long story short, I'd simply replace `proj/white` in the test with something better that doesn't contain a slash, like `project_wide`.

I know we ask a lot of you but I promise if you keep onto it this will soon be trivial for you. The first time is always hard but as you learn it gets better and faster :)

**Comment by abhsag24** [comment]
1,2> I'll keep that in mind for the next commit 

3>on it :)

**Comment by sils1297** [comment]
1,2: Just try `git rebase --interactive master` that way you can squash your two commits easily :)

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
