### PR TITLE
Fixes a typo in install.rst and adds UTF-8 encoding in Constants.py

### PR DESCRIPTION
**Pull request by sudoankit**

### CODE REVIEW

**Comment by sudoankit** [comment]
Why did the appveyor build cancel?

**Comment by AbdealiJK** [comment]
Probably someone manually cancelled it as there were too many appveyors builds. Im cancelling your current build as you need a rebase.

**Comment by sudoankit** [comment]
I need a rebase? 
Please explain.

**Comment by AbdealiJK** [comment]
ack 6e60a8d 3a5eb67

**Comment by AbdealiJK** [comment]
@sudoankit Basically what has happened is that we've merged a few commits since you forked. rebasing is a process which adds those extra commits below your new commits - so that git doesnt get confused about which commits go where.
Check the newcomer guide and the git help for more info in our docs. If youre still confused after reading them, ping us on gitter

**Comment by Makman2** [comment]
Sorry @sudoankit need to unack your commits again, your commit messages need slight adjustment :)
```
install.rst : Fix typo decent -> recent

Fixed a small typo. Changed "decent" to "recent".

Fixes coala-analyzer#1767
```
`Install.rst` has its first letter uppercase. Also please don't write a space between the tag and the following colon, so --> `Install.rst: Fix typo decent -> recent` is good
Since we are on it, also use present tense please (especially you say "Fixed typo" and then "Fixes issue xxx", being consistent is good)

For the second commit the same like before applies. Also for python modules we usually don't append the `.py`, since many commits modify our python modules, and .py uses up 3-chars you often need for shortlogs (50 chars are not that much :/ )
The second commit's body contains also too long lines, maximum we allow is 73 chars, so please wrap the content :)

**Comment by Makman2** [comment]
unack 6e60a8d 3a5eb67

**Comment by Makman2** [comment]
@AbdealiJK oh 72 chars for a body? Damn I can't remember that everytime whether 73 or 72 ...

**Comment by AbdealiJK** [comment]
@Makman2 It's 73 including a newline, so I normally just say 72 (excluding the newline) ^_^

**Comment by sudoankit** [comment]
72. Wow.
Sorry, I am amending it right now.

**Comment by sudoankit** [comment]
Is it fine now?

**Comment by Makman2** [comment]
Ah no not past tense but present tense! :D
Fixed -> Fixes
Added -> Adds
etc etc :D
And `Constants.py` -> just `Constants` :+1:
Also you didn't wrap the commit body to 72chars per line :O

**Comment by sils1297** [comment]
hey people we want *IMPERATIVE PRESENT* tense! `Fixes` -> `Fix`, `Adds` -> `Add`

**Comment by sudoankit** [comment]
Okay. Sorry.
Will `Now running setup.py with python2 gives python3 requirements.` do?
I am changing the commit message, now.

**Comment by Makman2** [comment]
That line is still okay :D

**Comment by sils1297** [comment]
@Makman2 forgot labelling?

**Comment by sils1297** [comment]
ack  @sudoankit 	Install.rst: Fix typo decent -> recent … 	
6e7350a
	@sudoankit 	Constants: Add UTF-8 encoding … 	
85953c0

**Comment by sils1297** [comment]
ack 6e7350a 85953c0

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
