### PR TITLE
Newcomers.rst: moved the 'coala gitter' link in the 'Meet the community'

### PR DESCRIPTION
**Pull request by sophiavanvalkenburg**
paragraph. Fixes https://github.com/coala-analyzer/coala/issues/1780

### CODE REVIEW

**Comment by sims1253** [comment]
Hey there,
you might want to look at our commit message style guide here:
http://coala.readthedocs.io/en/latest/Getting_Involved/Writing_Good_Commits.html

Gitlab is telling you that you are missing a newline between the shortlog and body of your commit message and also that the shortlog is too long.

**Comment by sims1253** [comment]
you can now sqash your commits into one with git rebase -i master
http://coala.readthedocs.io/en/latest/Users/Tutorials/Git_Help.html#squashing-your-commits

**Comment by sophiavanvalkenburg** [comment]
for some reason the CI is timing out

**Comment by Makman2** [comment]
I restarted the build, we recently got some timeout issues, though we thought we have solved them... let's see what happens :)

**Comment by Makman2** [comment]
CircleCI is facing loading issues it seems :/

**Comment by Makman2** [comment]
ack da6caa3

**Comment by sils1297** [comment]
Hi,

it looks like your PR is out of date and needs a rebase. [This page](http://coala.readthedocs.org/en/latest/Users/Tutorials/Git_Help.html) may help you to get started on this. (*Do not press the update branch button. It's evil.*)

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

Ping us on [our gitter channel](https://gitter.im/coala-analyzer/coala) if you need help!

**Comment by Makman2** [comment]
the commit should work, marked it already as acknowledged. We merge this as soon as CI passes :)

**Comment by sils1297** [comment]
@sophiavanvalkenburg thanks for updating, restarting CI. @Makman2 I think we may need to increase the timeout even more, I guess Circle CI's connection is just bad at peaks and then it takes even longer :/

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2211/commits/b1c7f58085e1138a49a80a172c07d17195daec44

**Comment by sils1297** [comment]
ack mean s acknowledged btw, we use it so our GitMate bot picks it up. It's a way to enforce code reviews on github.

**Comment by sophiavanvalkenburg** [comment]
thanks for running the open table event! it was very helpful in getting me started learning about how to contribute to open source :)

**Comment by sils1297** [comment]
@sophiavanvalkenburg thanks for attending. Most people don't realize that their contribution is valuable and an acknowledgement to us that what we're doing is great. So don't think we're not selfish ;) I'm always enjoying introducing newcomers.

Are you around for the sprints?

**Comment by abhsag24** [comment]
@rultor merge

**Pull request merged**
