### PR TITLE
Fix typo, change its -> it is

### PR DESCRIPTION
**Pull request by yash-nisar**
Please review @sils1297

### CODE REVIEW

**Comment by mr-karan** [comment]
Hi,

it seems that your commit message doesn't contain enough information. Don't worry, most people don't know about good commit messages when they join us, including very experienced developers :)

The most important part is the first line of your commit message - maintainers will use it to read through a large number of commits and thus it's important that it's short but most importantly concise. I'd heartily recommend reading http://coala.readthedocs.io/en/latest/Getting_Involved/Writing_Good_Commits.html !

To change your message you just use git commit --amend and then git push --force the new commit to replace the old one.

Cheers!

**Comment by yash-nisar** [comment]
Thank you so much for the advice @mr-karan . I shall keep that in mind. I am unable to understand why the code is not able to pass all checks inspite of there being such minor changes.

**Comment by mr-karan** [comment]
Well the first thing you have to understand is that this change, though looks minor but is because we at coala have high standards of code-style. We cannot lower it down if you feel this minor. With that being said, I know how you feel, most beginners are like this, they get frustrated with these "minor" tasks but well, what doesn't kill you makes you strong :P

**Comment by mr-karan** [comment]
And coming to why it doesn't pass the checks, well because Gitmate which runs on coala detects the bad stuff in commit messages and won't allow the build to pass.

**Comment by sils1297** [comment]
Hey, this looks splendid already. There's two little details to correct with the commit message:

- Please remove the space before the colon
- Just remove the `Fix typo,` part

so you end up with a simple `Result: Change its -> it is`. That is a bit shorter while holding the same information.

**Comment by sils1297** [comment]
Hey, this is your first contribution, right? Congrats and welcome to the coalaians! :)

Rultor will now automatically release your changes as a prerelease so users can experience the goodness of your changes right now.

See also https://github.com/coala-analyzer/coala/wiki/coala-Steam-Offer btw.

https://github.com/coala-analyzer/coala/pull/2568/commits/3f2bf0033ea63825e783d58b5bf3c6ef65cb8593 is ready

**Comment by sils1297** [comment]
@rultor merge

**Comment by yash-nisar** [comment]
Thank you @sils1297 . I am enthusiastic to work with this organisation will try my best to contribute regularly. This community is amazing and I loved the support that I received as a newcomer. Cheers !

**Comment by mr-karan** [comment]
Congrats :+1: You can find us at https://gitter.im/coala-analyzer/coala

**Pull request merged**
