### PR TITLE
Moving towards pytest

### PR DESCRIPTION
**Pull request by AbdealiJK**

### CODE REVIEW

**Comment by sils1297** [comment]
@AbdealiJK conflicts, can you rebase?

**Comment by AbdealiJK** [comment]
Yes, one moment. i actually made one of my commits into a newcomer issue
also - need to remove that commit.

**Comment by sils1297** [comment]
reack
 	@AbdealiJK 	ConfigurationGathering: Remove mutable argument … 	
41b99b8
	@AbdealiJK 	ConfigGatheringTest: Force arg_list to be empty … 	
dc45168
	@AbdealiJK 	CI: Use pytest for testing everywhere … 	
21ed87b
	@AbdealiJK 	requirements: Create separate list for testing … 	
79ec9dd
	@AbdealiJK 	docs: Update docs about pytest for testing 	
83c4337
	@AbdealiJK 	setup.cfg: Revamp coverage and pytest settings … 	
94dc2c6
	@AbdealiJK 	CollectorsTest: Ignore __pycache__ dirs … 	
4eb70e9
	@AbdealiJK 	setup.py: Add tests_require … 	
759e971
	@AbdealiJK 	setup.py: Run pytest with `setup.py test` … 	
7b1f19f
	@AbdealiJK 	run_tests: Remove older testing framework … 	
e111219
	@AbdealiJK 	Tests: Remove sys.path manipulation for run_tests … 	0ac354b

**Comment by AbdealiJK** [comment]
ack
0ac354baf0a6567dd025f4ff9a5ecec39ffcc138 Tests: Remove sys.path manipulation for run_tests
e1112195b047a2efa88bc4340e11cd6fd50c9f24 run_tests: Remove older testing framework
7b1f19f4c58b84d975234c98d9452e925541ad1c setup.py: Run pytest with `setup.py test`
759e971bba0c6db5c0611f1e5f7e6c06ab01702b setup.py: Add tests_require
21ed87bb70d8cbfb68f0eb57368caead43be6b5c CI: Use pytest for testing everywhere
83c4337a0c7a8ff83ccef70d3913bb18cdc0685d docs: Update docs about pytest for testing
94dc2c61fdd481d030e236476d4d838182c0d964 setup.cfg: Revamp coverage and pytest settings
79ec9dd5675132e9019c3fb08f346c7aa1a40f91 requirements: Create separate list for testing
4eb70e947113f4e2d298001618d72ebfb5b8b047 CollectorsTest: Ignore __pycache__ dirs
dc45168455f9fc3bf17ddf938b5c090b9a088b54 ConfigGatheringTest: Force arg_list to be empty
41b99b81ba8f49793bbed0ef6c194cd4d7e943a2 ConfigurationGathering: Remove mutable argument

**Comment by sils1297** [comment]
ack
0ac354b Tests: Remove sys.path manipulation for run_tests
e111219 run_tests: Remove older testing framework
7b1f19f setup.py: Run pytest with setup.py test
759e971 setup.py: Add tests_require
21ed87b CI: Use pytest for testing everywhere
83c4337 docs: Update docs about pytest for testing
94dc2c6 setup.cfg: Revamp coverage and pytest settings
79ec9dd requirements: Create separate list for testing
4eb70e9 CollectorsTest: Ignore pycache dirs
dc45168 ConfigGatheringTest: Force arg_list to be empty
41b99b8 ConfigurationGathering: Remove mutable argument

I think the request gets lost if gitmate is too occupied otherwise

**Comment by AbdealiJK** [comment]
reack
92f460ec11ef200433e07c8ab071e93fd0c9ec34 Tests: Remove sys.path manipulation for run_tests
a7bca64f2ac41cb85ffdbc970ca983f8e8c8287f run_tests: Remove older testing framework
ca5570b3a8d67899295eb92a56daae13682d687e setup.py: Run pytest with `setup.py test`
2e28b49e69a1862e206b84bdbc88d06bd3adf0ee setup.py: Add tests_require
c75ee5f88fc95c3921dcdd26ce40c464658a7def CI: Use pytest for testing everywhere
9d518a3d450f18e191b3792374df0bc8f38624bb setup.cfg: Revamp coverage and pytest settings
79ec9dd5675132e9019c3fb08f346c7aa1a40f91 requirements: Create separate list for testing
4eb70e947113f4e2d298001618d72ebfb5b8b047 CollectorsTest: Ignore __pycache__ dirs
dc45168455f9fc3bf17ddf938b5c090b9a088b54 ConfigGatheringTest: Force arg_list to be empty
41b99b81ba8f49793bbed0ef6c194cd4d7e943a2 ConfigurationGathering: Remove mutable argument
c5bb607759f517964ed334eb8a120f2fca06532d docs: Update docs about pytest for testing

**Comment by sils1297** [comment]
reack
92f460e Tests: Remove sys.path manipulation for run_tests
a7bca64 run_tests: Remove older testing framework
ca5570b setup.py: Run pytest with setup.py test
2e28b49 setup.py: Add tests_require
c75ee5f CI: Use pytest for testing everywhere
9d518a3 setup.cfg: Revamp coverage and pytest settings
79ec9dd requirements: Create separate list for testing
4eb70e9 CollectorsTest: Ignore pycache dirs
dc45168 ConfigGatheringTest: Force arg_list to be empty
41b99b8 ConfigurationGathering: Remove mutable argument
c5bb607 docs: Update docs about pytest for testing

**Comment by sils1297** [comment]
reack 92f460e  a7bca64 ca5570b 2e28b49 c75ee5f  9d518a3 79ec9dd 4eb70e9 dc45168 41b99b8 c5bb607

**Comment by sils1297** [comment]
needs work, conf.py is included in coverage measurement

**Comment by AbdealiJK** [comment]
@rultor merge

**Pull request merged**
