### PR TITLE
bears: Add goreturns bear

### PR DESCRIPTION
**Pull request by sudheesh001**
Add the bears for goreturns for deeper go support
Add tests for good and bad tests for goreturns

Fixes https://github.com/coala-analyzer/coala/issues/1331

### CODE REVIEW

**Comment by AbdealiJK** [comment]
ack  2588f07

**Comment by AbdealiJK** [comment]
Appveyor fails though - could you amend and push again ?

**Comment by sils1297** [comment]
@AbdealiJK I can restart it...

**Comment by sils1297** [comment]
build restarted.

**Comment by AbdealiJK** [comment]
Moved to https://github.com/coala-analyzer/coala/pull/1507

**Pull request closed without merging**
