### PR TITLE
docs: Change regex link to python 3

### PR DESCRIPTION
**Pull request by Uran198**
Fixes https://github.com/coala-analyzer/coala/issues/1779

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
restarted the build, seems to have been a bug;

**Comment by Makman2** [comment]
@Uran198 as soon as https://github.com/coala-analyzer/coala-bears/pull/186 is merged you can rebase upon master again and circle should work again :+1:

**Comment by SanketDG** [comment]
@Uran198 A rebase and this should be good.

**Comment by sils1297** [comment]
973f93f reack

**Comment by sils1297** [comment]
reack 973f93f ?

**Comment by sils1297** [comment]
973f93f is ready

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
