### PR TITLE
__init__.py: Replace lambdas with returned string

### PR DESCRIPTION
**Pull request by mwang14**
Fixes https://github.com/coala-analyzer/coala/issues/2694

### CODE REVIEW

**Comment by sils1297** [comment]
Hey, sorry for letting you waiting so long. So there's a few little things:

- The first line of your commit message is too long, maybe remove the word "returned"? That's also why everything looks so red in the build status sections.
- Your Git author information doesn't seem to be complete. We don't care but if you want it to appear on your profile, please check it out ;)
- We need a closes instead of a fixes as we use it for bugprediction.

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

**Comment by mwang14** [comment]
Just fixed it. Thanks for letting me know :)

**Comment by Adrianzatreanu** [comment]
hey you have a gitmate error: as it points out, yuo need a newline between shortlog and commit body :)

**Comment by Adrianzatreanu** [comment]
also, it should be "closes"->"Closes"

**Comment by mwang14** [comment]
Just fixed that too, sorry!

**Comment by SanketDG** [comment]
> Just fixed that too, sorry!

@mwang14,

Sorry, it is not fixed yet. In the commit amend window, just make sure to keep one line between the first line (i.e. shortlog) and the successive lines (body) :smile:

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2728/commits/b0ef4beb960d7f74022a661d898e86f5584802e2

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
Hey, this is your first contribution, right? Congrats and welcome to the coalaians! :)

Rultor will now automatically release your changes as a prerelease so users can experience the goodness of your changes right now.

See also https://github.com/coala-analyzer/coala/wiki/coala-Steam-Offer btw.

**Comment by mwang14** [comment]
Thanks for helping me with my first commit :) you guys are awesome!

**Pull request merged**
