### PR TITLE
StringProcessingTest: Use custom assert message

### PR DESCRIPTION
**Pull request by Makman2**

### CODE REVIEW

**Comment by Makman2** [comment]
So just what it would look like:
```python
from coalib.parsing.StringProcessingTest import StringProcessingTest as SPT
def x():
    pass
print(SPT._construct_message(x, ("a", "'\"", 3,4,True,x), {"q":"w", "anumber":47}))
```
yields
```
Called x("a", "'\"", 3, 4, True, <function x at 0x0304A2B8>, anumber=47, q="w").
```

**Comment by sils1297** [comment]
@rultor merge

**Comment by Makman2** [comment]
Rebased

**Comment by Makman2** [comment]
@rultor merge

**Pull request merged**
