### PR TITLE
Sils/printcol

### PR DESCRIPTION
**Pull request by sils1297**
@Makman2 can you explain whats wrong here? Is there something wrong with the new color printer?

### CODE REVIEW

**Comment by Makman2** [comment]
I had the same error when I didn't install pyprint^^

**Comment by sils1297** [comment]
Are you saying I published the wrong version to pypi? Trying that out
tomorrow...

**Comment by Makman2** [comment]
But after I just installed via `pip install pyprint` everything worked again^^

**Comment by sils1297** [comment]
@Makman2 that happens  for me on sils/printcol not on this one.

**Comment by sils1297** [comment]
wrong PR. Related: https://github.com/coala-analyzer/coala/pull/942

**Comment by sils1297** [comment]
Rebased this PR mindlessly, will probably need some more work.

**Comment by sils1297** [comment]
@Makman2 corrected commit

**Comment by Makman2** [comment]
@rultor merge

**Comment by Makman2** [comment]
@rultor merge again

**Comment by Makman2** [comment]
@sils1297 Can you look at rultor? Dunno what's wrong :/

**Comment by sils1297** [comment]
@Makman2 looks like a rultor bug, trying again, then filing a bug if it still doesn't work.

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@rultor merge

I-want-this-MERGED!!!

**Comment by sils1297** [comment]
(deleted rultor log extracts because they make this conversation really long and they're contained in the "here" links from rultor.Needless to say that they all failed.)

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
