### PR TITLE
tests/bearlib : Removes unneeded documentation 

### PR DESCRIPTION
**Pull request by srisankethu**
@AbdealiJK Made changes from #1347 on issue #1343

### CODE REVIEW

**Comment by AbdealiJK** [comment]
@srisankethu Your patch looks good ! But, please modify your commit message also.

@sils1297 had mentioned - `So first off the commit message is not bad but it still needs some work. We have guidelines at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages because that's a very common problem for new people.`

**Comment by srisankethu** [comment]
Fixes #1343

**Comment by srisankethu** [comment]
@AbdealiJK Changed title and added short description

**Comment by sils1297** [comment]
@srisankethu hey, thanks for your contribution and welcome!

So we don't care about the title/description of the PR. We only care about:

1. What code you change.
2. THe commit message as it is a very valuable piece of documentation.

So we actually want you to change that commit, just do a `git commit --amend` and then you can improve your message. You can then push it on your branch with `git push --force`. Don't ever force push on a branch that is not solely for you (which is also why it's not recommended to send PRs from master branches.)

**Comment by srisankethu** [comment]
@ Ok that you, is my pull request accepted then? I made an earlier pull request #1379 which has passed all check except review

**Comment by sils1297** [comment]
unack 3242b04, this is not ready yet as it needs work on the commit mesage as indicated. That doesn't mean that you're doing a bad job, really. The first contribution is always hard and we do that kind of review to all of us. (@Makman2 is the worst of all reviewers - he finds something in *every* commit ;))

**Comment by srisankethu** [comment]
@sils1297 Can you suggest a commit message?Please!

**Comment by sils1297** [comment]
`tests/bearlib: Remove unneeded documentation` and then add the `Fixes` note as described in http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages ?

**Comment by sils1297** [comment]
@srisankethu hey, from the activity log I see you seem to be reforking coala i.e. you have deleted your old repository and thus my review comment which did contain suggestions. Please don't do that. There are better ways that are way easier for you. If you don't know them, approach us on gitter, we're happy to help.

**Comment by srisankethu** [comment]
@sils1297 I have changed the title and should Iwrite Fixes #1343 in the title or in the body(I have already done that)

**Comment by sils1297** [comment]
> So we don't care about the title/description of the PR. We only care about:
> 
> 1.   What code you change.
> 2.   THe commit message as it is a very valuable piece of documentation.

The PR title is irrelevant to us.

**Comment by srisankethu** [comment]
@sils1297 Made changes in #1389

**Comment by AbdealiJK** [comment]
Closing in favour of https://github.com/coala-analyzer/coala/pull/1389

**Pull request closed without merging**
