### PR TITLE
Make ResultAction settings settable from config files

### PR DESCRIPTION
**Pull request by AhmedKamal1432**
Make begin_section() save the section that we currently use proccess
it, and when user inter parmeter to a certain action, ConsoleInteractor
save it in current_section settings

see: #330

### CODE REVIEW

**Comment by sils1297** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/coala-analyzer/coala/pull/365'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by sils1297** [comment]
Before you ask: the two commands you'll need are

git reset HEAD^
git add -p

**Comment by AhmedKamal1432** [comment]
@sils1297  thanks  
"git add -p" command was very useful :smile:

**Comment by sils1297** [comment]
and please rebase onto current master, you might get conflicts since github shows this as non-mergeable. Use `git mergetool` to resolve them.

**Comment by AhmedKamal1432** [comment]
@sils1297  I added a test case to test raising `ValueError` when calling `print_result` without initializing `current_section`

**Comment by sils1297** [comment]
thats good!

**Comment by sils1297** [comment]
merged with modified commit message

**Pull request closed without merging**
