### PR TITLE
docs: Correct link in README.rst

### LINKED ISSUE #1350: README.rst: invalid rtfd urls
`Getting Involved Information` link under `Getting Involved` section of `README.rst` is pointing to invalid url. We should change the url to [http://coala.readthedocs.org/en/latest/](http://coala.readthedocs.org/en/latest/)

### PR DESCRIPTION
**Pull request by scriptnull**
Corrected the link for Getting Involved Section.

Fixes #1350

### CODE REVIEW

**Comment by tushar-rishav** [comment]
@scriptnull Please run coala to fix your commits. I am sure you would have read [Writing Good Commits](http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html)

**Comment by sils1297** [comment]
Hi, I've invited you to our team so we can assign you to bugs, it'd be sad if multiple people work on the same thing and in the end something needs to be rejected.

Feel free to join our channel at https://gitter.im/coala-analyzer/coala where we can help you figuring outt how to polish your PR :)

**Comment by sils1297** [comment]
Also, this PR needs a rebase. Ping us on gitter if you need help with that.

Btw. welcome! Don't be afraid of us, we do awful reviews but we do it to everyone even to us. ;) We appreciate your contribution!

**Comment by scriptnull** [comment]
@sils1297  @tushar-rishav Thank you I will try to do it and if I face any problems , I will contact on gitter room

**Comment by WJCode** [comment]
Hi @scriptnull could you please do a rebase and change this link to `http://coala.readthedocs.org/en/latest/Getting_Involved/README.html` as that is the Introduction page for Getting Involved.

Also two other coala.rtfd.org links on README.rst need this change. i.e in the link, simply replace the ending `/` with `.html` Could you please fix them as well?

**Comment by scriptnull** [comment]
@WJCode sure !

**Comment by scriptnull** [comment]
@tushar-rishav I have rebased and pushed my commits. i think i have made a mistake by specifying the issue number instead of the full link. It would be helpful for me , if you guys give me a pointer  to solve this. 

Please bear with me. I am new at this.  :smile:

**Comment by sils1297** [comment]
@scriptnull just do a git rebase --interactive then you can do a reword on your commit to include the full url

**Comment by Makman2** [comment]
@scriptnull and please fixup your two commits (so bunch them together keeping the first commit message), this would address the issue completely in a single commit :)

**Comment by sils1297** [comment]
unack  359fa62 11748ca, also needs a rebase

**Comment by scriptnull** [comment]
Updated it , Please review.

**Comment by Makman2** [comment]
ack 4680c14

**Comment by Makman2** [comment]
@rultor merge

**Pull request merged**
