### PR TITLE
Refactored _yield_if_right_kind into a condition

### PR DESCRIPTION
**Pull request by Uran198**
Fixes https://github.com/coala-analyzer/coala/issues/1190

### CODE REVIEW

**Comment by GitCop** [comment]
The commit message

 * Commit: 6ca85111c0f1a24627f6e7c24c84ba725a086753
  * Commits must be in the following format: **%{scope}: %{description}**

Guidelines are available at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
The commit message

 * Commit: 71e51880ac23277505dd35f4ec8249d38eb3e42f
  * Commits must be in the following format: **%{scope}: %{description}**

Guidelines are available at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages

---
This message was auto-generated by https://gitcop.com

**Comment by sils1297** [comment]
@Uran198 hi, thanks for your PR! I'll invite you to the coala org so I can assign you to that bug if you don't mind. In this case please ignore GitCop, the rules aren't very flexible...

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
(FYI rultor sometimes errors out nondeterministically, but there's no viable alternative :/)

**Comment by sils1297** [comment]
@Uran198 not your fault, I've filed https://github.com/yegor256/rultor/issues/985 if they don't fix that soon I'll do a manual merge.

**Comment by sils1297** [comment]
@rultor merge

**Comment by Uran198** [comment]
@sils1297 Ok, thank you. I've never got such a fast response :) I accepted the invitation.

**Comment by sils1297** [comment]
@Uran198 we've taken a lot of effort to make that possible, especially through the CI systems which allow me to rely on all tests passing on all OSes and stuff like that. Plus I'm really trying to be responsive because I know how bad it is to come to a project and not get a response for months - great to see that the efforts are valued! Welcome!

**Comment by sils1297** [comment]
@Uran198 I've done a manual merge now, we usually use rultor for this because it'll automatically do a development release of coala which I had to do manually now :)

**Comment by sils1297** [comment]
@Uran198 that said your commit is already in this PRs develoment release at https://pypi.python.org/pypi/coala/0.3.1.dev20160115093429

**Comment by Uran198** [comment]
@sils1297 Wow, It's cool ;) I will definitely contribute more to your project!

**Pull request merged**
