### PR TITLE
FunctionMetadata.py : if-none initialisation

### PR DESCRIPTION
**Pull request by keerthisuresh**
fixes https://github.com/coala-analyzer/coala/issues/946

### CODE REVIEW

**Comment by sils1297** [comment]
@keerthisuresh we can't merge this yet, something's wrong with our merge bot :) When everything works again, we will likely ask you to rebase it and then we can merge it. It will happen in the next days, no worries.

**Comment by keerthisuresh** [comment]
Okay , no problem !!

**Comment by Makman2** [comment]
@keerthisuresh alright, you can rebase :D our merge bot works again^^

**Comment by keerthisuresh** [comment]
rebased :)

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
