### PR TITLE
Added CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by srisankethu**
Fixes https://github.com/coala-analyzer/coala/issues/1442

### CODE REVIEW

**Comment by sils1297** [comment]
unack 8be6400, it's a good start. Such large chunks of documentation always need lots of discussion, maybe @AbdealiJK can coreview this.

**Comment by srisankethu** [comment]
Yes it's from babel

**Comment by sils1297** [comment]
please indicate it in the commit message

2016-02-14 22:27 GMT+01:00 Sri Sanketh Uppalapati <notifications@github.com>
:

**Comment by Redridge** [comment]
Seems ok to me

**Pull request closed without merging**
