### PR TITLE
Install.rst : Fix typo Max -> Mac

### PR DESCRIPTION
**Pull request by priests**
Fixes https://github.com/coala-analyzer/coala/issues/1749

### CODE REVIEW

**Comment by priests** [comment]
I hope it does the job now ?

**Comment by AbdealiJK** [comment]
ack 4d1e476

**Comment by AbdealiJK** [comment]
Needs a rebase

**Comment by AbdealiJK** [comment]
DO a rebase after https://github.com/coala-analyzer/coala/pull/1752 gets merged - else youll have to do another rebase

**Comment by priests** [comment]
Okay ! :+1:

**Comment by SanketDG** [comment]
ack 54b935f

**Comment by SanketDG** [comment]
@rultor merge

**Pull request merged**
