### PR TITLE
ConsoleInteraction: Refactor format_str

### LINKED ISSUE #1701: ConsoleInteraction: change format string to match params in print_results_formatted
`to_line` --> `end_line` and so on

difficulty/newcomer

### PR DESCRIPTION
**Pull request by analyticalmonk**
ConsoleInteraction: Refactor format_str

In ConsoleInteraction.py, changed format_str in print_results_formatted
to match params. Also made changes to ConsoleInteractionTest.py
for consistency.

Fixes #1701

### CODE REVIEW

**Comment by SanketDG** [comment]
@analyticalmonk 
Make your commit message much shorter.
Like this:
```
ConsoleInteraction: Refactor format_str
```
And probably explain what you did in the body.

Also dont forget to add `Fixes: <issue url>` so that it can be closed automatically.

Everything else looks okay.

**Comment by AbdealiJK** [comment]
ack  0246501

**Comment by sils1297** [comment]
ack 0246501

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@analyticalmonk is this your first contribution? Congrats! :) It's good to have you here and you have now mastered the needed git knowledge. I'd recommend some difficulty/low bug from coala-bears next, those are usually rather easy to write new bears, we have a tutorial in the docs how it works and it's very rewarding work because you add a whole new set of analysis routines to coala.

Your work has now been merged to master and automatically prereleased to https://pypi.python.org/pypi/coala/0.4.2.dev20160228093835 (a release just for you) so users can already enjoy it :)

**Comment by analyticalmonk** [comment]
@sils1297 Thanks! :smile: 
Good to be here. I will make another contribution soon enough.

**Pull request merged**
