### PR TITLE
setup: Add build docs command

### PR DESCRIPTION
**Pull request by Redridge**
Fixes https://github.com/coala-analyzer/coala/issues/1493

### CODE REVIEW

**Comment by sils1297** [comment]
ack 57a44cd1e4

**Comment by sils1297** [comment]
I have cancelled your builds because queues are quite full. I'll be merging https://github.com/coala-analyzer/coala/pull/1483 and when that is done I'd like you to rebase this so we can merge it.

**Comment by Redridge** [comment]
sure thing

**Comment by sils1297** [comment]
this is included in https://github.com/coala-analyzer/coala/pull/1487 now

**Pull request closed without merging**
