### PR TITLE
Cleaned coalib/tests/bearlib/__init__.py

### PR DESCRIPTION
**Pull request by srisankethu**

### CODE REVIEW

**Comment by sils1297** [comment]
Hey, why do you remove our documentation? Was there an issue for that? :/

**Comment by AbdealiJK** [comment]
@sils1297 this documentation is not correct. Its just copied from another place into the tests folder by mistake ...
And yes, i made an issue - https://github.com/coala-analyzer/coala/issues/1343

**Comment by sils1297** [comment]
Ah thanks, then the issue reference is missing.

**Comment by sils1297** [comment]
@srisankethu welcome! If you want a more personal assistance consider joining our channel at https://gitter.im/coala-analyzer/coala .

I have invited you to our organization - it would be cool if you accept that so we can assign you to this bug.

**Comment by sils1297** [comment]
@srisankethu so this commit needs a bit of work - don't worry, that's very usual for new people. Once you get accustomed to this it'll get really trivial for you.

So first off the commit message is not bad but it still needs some work. We have guidelines at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages because that's a very common problem for new people.

You can change the commit message with `git commit --amend` locally. Also we want you to do a rebase onto the current master - ping us if you need help with that.

**Comment by srisankethu** [comment]
@sils1297 I'm Kinda new to OpenSoftware can please tell me how to remove this line from website

**Comment by AbdealiJK** [comment]
@srisankethu you need to use `git commit --amend`

Just make the changed you want to make and do the `git add` to let git know you modified some files. Then do a `git commit --amend` to modify your last commit

More details can be found here : https://www.atlassian.com/git/tutorials/rewriting-history/git-commit--amend

**Comment by srisankethu** [comment]
@AbdealiJK Made changes in #1379

**Comment by AbdealiJK** [comment]
Closed in favour of https://github.com/coala-analyzer/coala/pull/1379

**Pull request closed without merging**
