### PR TITLE
ConsoleInteraction.py: Rename param in docstring

### PR DESCRIPTION
**Pull request by Asnelchristian**
Change the docstring to use :param settings_names_dict.

Closes https://github.com/coala-analyzer/coala/issues/2667

### CODE REVIEW

**Comment by Asnelchristian** [comment]
this it just a cherry-pick of https://github.com/coala-analyzer/coala/pull/2669 commit :)

**Comment by Asnelchristian** [comment]
ack https://github.com/coala-analyzer/coala/pull/2671/commits/f4ee1508fe010eb7a4dbb46f10d8d186cd16ec49

**Comment by Makman2** [comment]
unack f4ee150

**Comment by Asnelchristian** [comment]
@rultor merge

**Comment by Makman2** [comment]
documentation is not correctly aligned any more, either make it tabular again, or I recommend making another commit before this one using this layout:
```
:param x:
    X
:param y:
    Y
```
and then applying the param-changing commit (using this style too)

**Comment by Makman2** [comment]
@rultor stop

**Comment by Asnelchristian** [comment]
oops sorry for that, i didn't check

**Comment by Asnelchristian** [comment]
so @netman92 ^

**Comment by Asnelchristian** [comment]
i am modifying it any way

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2671/commits/47263d7f4c14f3c7f74c040008546fba5261f0c2 needs a rebase though!

**Comment by sils1297** [comment]
@netman92 can you do the rebase quick and ping us?

**Comment by netman92** [comment]
@sils1297 I think someone cherry-picked this.

**Comment by sils1297** [comment]
can't find it and ithub doesn't show conflicts

**Comment by sils1297** [comment]
oh this is the cherry pick! @Asnelchristian can you rebase and merge please?

**Comment by Asnelchristian** [comment]
reack https://github.com/coala-analyzer/coala/pull/2671/commits/fa545d0f2466b6fc29e7e13282cae92475c08a77

**Comment by Asnelchristian** [comment]
@rultor merge

**Pull request merged**
