### PR TITLE
Cleanup StringProcessingTest

### LINKED ISSUE #593: StringProcessing is huge!
StringProcessingTest has over a thousand lines of code. This is bad.

So maybe we can split out some things in some base class so we have only test strings in a file and test methods in another and the glue in a third one? Or maybe we can split the functionality too?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/18149777-stringprocessing-is-huge?utm_campaign=plugin&utm_content=tracker%2F2228228&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F2228228&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Makman2**
I think this would fix #593.

### CODE REVIEW

**Comment by sils1297** [comment]
@Makman2 0please look at scrutinizer: https://scrutinizer-ci.com/g/coala-analyzer/coala/inspections/5f2a06e7-53b9-4e53-b417-9826ef4841bc/issues/files/coalib/tests/parsing/StringProcessingTest.py?status=new&orderField=path&order=asc

**Comment by sils1297** [comment]
needs rebase

**Comment by sils1297** [comment]
hey, you remove 100 lines in these commits - thats good work!

**Comment by Makman2** [comment]
And I dont understand scrutinizer, where is an illegal space before my parameter??

**Comment by sils1297** [comment]
Its before the colon in the lambda expression.
Am 31.05.2015 17:52 schrieb "Makman2" <notifications@github.com>:

**Comment by Makman2** [comment]
Renamed in the new assertion functions `preprocess` into `postprocess`.
Ready for review again^^

**Comment by Makman2** [comment]
Corrected:
- Squash new global auto-trim-pattern with commit where it's first used (move-out of `search_for`)
- Rename lambda param in assertion functions to a non-builtin

**Comment by Makman2** [comment]
Put in each commit a note on test base shadow-execution.

**Comment by Udayan12167** [comment]
There are similar problems in every commit as i have mentioned in https://github.com/coala-analyzer/coala/commit/ebe97fa4f14e5004b25a2da6dfa3bea0389567a8. I dont know if that is intended code style?

**Pull request merged**
