### PR TITLE
Fix grammatic mistake

### PR DESCRIPTION
**Pull request by lonewolf07**
Fix grammatic mistake

### CODE REVIEW

**Comment by Makman2** [comment]
Could you fixup both commits? You can do that by doing `git rebase -i HEAD~2` (`HEAD~2` means the last two commits, that's how much your PR consists of). This pops up your text editor and a rebase script is displayed. You should change it like this:
```
reword AAAAAAA ...
fixup BBBBBBB ...

# Some comments of git ...
```
Important are `reword` and `fixup`. `fixup` puts all changes into the previous commit in the line above. `reword` is for changing the commit message. Your second commit message is good, I would suggest though that you add the file ending for `Linter_Bears` (the .rst) too, since normally we use extension-less tags when we mean python files or it's something very obvious.

So this would be a perfect message (at least for me :D):
```
Linter_Bears.rst: Fix grammatic mistake

Fixes https://github.com/coala-analyzer/coala/issues/1562
```

I hope this was not too complicated, if you have questions ask us at gitter :) :+1:

**Comment by sudheesh001** [comment]
unack 241e191
unack 17028f3

**Comment by sudheesh001** [comment]
@lonewolf07 This looks great but for this to pass you'd have to squash the commits you've made and rebase with the updates from master.

Here's how you can squash commits: https://asciinema.org/a/11269

**Comment by AbdealiJK** [comment]
unack 241e191
unack 17028f3

**Comment by sils1297** [comment]
unack 241e191 17028f3

**Comment by sils1297** [comment]
need help?

**Pull request closed without merging**
