### PR TITLE
tests: Move make_temp() to ContextManagers

### PR DESCRIPTION
**Pull request by WJCode**
Related to https://github.com/coala-analyzer/coala/issues/1159

### CODE REVIEW

**Comment by sils1297** [comment]
Hey, you'll need to rebase this. Also I think our CI will automatically complain in a few minutes because you didn't write a test for the function - I think I mentioned that earlier that we want a test for this function because you moved it into the production code area?

**Comment by WJCode** [comment]
@sils1297 Got it. I'll rebase this.
Yes, you mentioned that. I'm sorry I forgot. I will try to do this now

**Comment by sils1297** [comment]
Sure no problem :) We're here to learn

2016-01-15 10:51 GMT+01:00 WJCode <notifications@github.com>:

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
