### PR TITLE
gitignore: Add venv

### LINKED ISSUE #1761: Inclusion of venv in .gitignore
Most of us work on `virtualenv` in Python but `.gitignore` has no `venv/` listed. Is there any particular reason for it ? 

I know `venv` name is not compulsory to use but since Node, Bower etc have their packages listed under a fixed directory name so just a suggestion, if making `venv` a standard name for virtual environments in our project makes it easier for other people as well we can maybe add it to .gitignore.

### PR DESCRIPTION
**Pull request by laxmena**
vnev added to gitignore.

Fixes #1761

### CODE REVIEW

**Comment by sils1297** [comment]
#1764 is a merged PR and can't be fixed right? Also don't you mean venv?

**Comment by AbdealiJK** [comment]
Can you squash all of these and do a good rebase ?
Some good docs to check out are:

coala.readthedocs.org/en/latest/Getting_Involved/Newcomers.html
and
coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html

or talk to us on gitter.

**Comment by sils1297** [comment]
Hey, do you need help @laxmena ?

**Comment by Adrianzatreanu** [comment]
long lack of response, closing this.

**Pull request closed without merging**
