### PR TITLE
ConsoleInteraction: Improve coverage

### PR DESCRIPTION
**Pull request by Asnelchristian**

### CODE REVIEW

**Comment by Asnelchristian** [comment]
reack https://github.com/coala-analyzer/coala/pull/2507/commits/9f9c227aa6db6e0ec3f064f833e822d824790bb2

**Comment by Asnelchristian** [comment]
@sils1297 i guess is alright if i merge as you said in https://github.com/coala-analyzer/coala/pull/2469 :)

**Comment by Asnelchristian** [comment]
@rultor merge

**Comment by sils1297** [comment]
yes :+1:

**Pull request merged**
