### PR TITLE
Escaping helper functions v2

### PR DESCRIPTION
**Pull request by Makman2**
Takes over from #357.
Completely renewed all commits. Each function now comes with its complete test set and functionality.

### CODE REVIEW

**Comment by sils1297** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/coala-analyzer/coala/pull/364'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by Makman2** [comment]
No module `six` as standard in our distribution?

**Comment by Makman2** [comment]
PS: After review I'll rebase onto master^^

**Comment by sils1297** [comment]
why is everything failing?

**Comment by Makman2** [comment]
Because of the `six` module I used. It's for python 2/3 type compatibility ( I use it to check against string)

**Comment by Makman2** [comment]
Shall I remove it and just use str?

**Comment by Makman2** [comment]
Since we use anyway python3 no use for this module, I'll remove it^^

**Comment by Makman2** [comment]
Not using `six` anymore

**Comment by sils1297** [comment]
I think you've got enough for now, especially since most comments are generally applicable to all commits.

**Comment by Makman2** [comment]
Note for myself:
When rebasing: Rename commit messages^^

**Comment by Makman2** [comment]
Rebase done

**Comment by sils1297** [comment]
maybe you want to reference the issue in commit message:
https://github.com/coala-analyzer/coala/issues/160

(Full URL please)

**Comment by Makman2** [comment]
Shall I already rebase?

**Comment by sils1297** [comment]
yes, go ahead.

2015-03-09 19:22 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
done

**Comment by sils1297** [comment]
thanks, makes review easier if the old things are done and you don't have to think about them anymore.

**Comment by Makman2** [comment]
Completely right to add tests for your edge case... The RegexObject itself behaves a bit strange when providing an empty match pattern.

**Comment by sils1297** [comment]
I'll try not to find much, it's time we get that merged. And in first sight it looked way better than before. :)

**Comment by sils1297** [comment]
ok, I'm still nitpicky but it's only simplifications until now and no major changes :(

**Comment by sils1297** [comment]
Oh I think a tiny function is missing: `unescape(string)` which removes escape characters :) (and maybe escape which adds them where needed but I don't see any usecase for that yet)

**Comment by Makman2** [comment]
Something went wrong, my local commit order is correct, here it's turned around...

**Comment by sils1297** [comment]
yeah, github shows it wrong sometimes, can't do anything about it :(

**Comment by Makman2** [comment]
My internet is somehow extreme slow at the moment and I have connection errors, I thinkt that's the cause.

**Comment by sils1297** [comment]
As I said, github something shows things wrong. Git doesn't.

2015-03-10 21:22 GMT+01:00 Makman2 <notifications@github.com>:

**Comment by Makman2** [comment]
Hm okay the order is correct, you're right, so you can start review^^

**Comment by sils1297** [comment]
maybe it's time for v3 now

**Comment by Makman2** [comment]
kk I'll push a new branch soon^^

**Comment by sils1297** [comment]
renewed in #385

**Pull request closed without merging**
