### PR TITLE
Use coala-bears repo

### PR DESCRIPTION
**Pull request by AbdealiJK**
This is my plan to move the repo to `coala-bears`

Currently we have https://github.com/coala-analyzer/coala-bears/tree/ajk/wip which holds the latest code.
For now, I have added it to the `requirements.txt` so that it can be tested with the repo.

Once that repo gets rultor+pypi I will use the development version mentioned there.
I will change this PR to use `>=0.1.0.dev0xxxxx` and that's it - everything *should* work

### CODE REVIEW

**Comment by AbdealiJK** [comment]
Change pyprint and coala to use `>=` in requirements.txt to fix https://circleci.com/gh/coala-analyzer/coala-bears/6

**Comment by sils1297** [comment]
needs love from @AbdealiJK

**Comment by sils1297** [comment]
this isn't ready for review yet is it?

**Comment by AbdealiJK** [comment]
Currently coala cannot find the bears because the entrypoint is not setup (blocked by https://github.com/coala-analyzer/coala-bears/pull/13)
After that a rebuild should be enough to get this to work

**Comment by AbdealiJK** [comment]
Earlier I had printer `coala -v` to check the coala version being run and had compared it with `date --utc +%Y%m%d%H%M%S` so im sure the coala being run is the latest thing just installed in circleci.
It didnt give any warning about bears not found - so, it found the bears.

**Comment by AbdealiJK** [comment]
No new change has been made to `bears` folder in the last 2 days except a change from `dummy` -> `_`.

As seen in https://github.com/coala-analyzer/coala/commits/master/bears

**Comment by Redridge** [comment]
@rultor merge

**Pull request merged**
