### PR TITLE
git_tutorial_1.rst: Fix grammatical errors

### PR DESCRIPTION
**Pull request by erilyth**
Fix Issue #1725

### CODE REVIEW

**Comment by sils1297** [comment]
hey hey now you closed all didn't you?

**Comment by sils1297** [comment]
Can you just drop by at https://gitter.im/coala-analyzer/coala or freenode #coala so we can have a chat?

**Comment by erilyth** [comment]
@sils1297 I closed this one by accident, I wanted to keep one open as you suggested.

**Comment by sils1297** [comment]
@erilyth do you know what a git rebase is?

**Comment by sils1297** [comment]
@erilyth the commit looks ok so I want to merge it but one goal of the newcomer issues is to teach you about rebase and rebase --interactive. Could you please at least look it up?

**Comment by sils1297** [comment]
ack dd8b338

**Comment by erilyth** [comment]
@sils1297 Ill take a look at 'rebase' and 'rebase --interactive'

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@erilyth rultor will automatically release your change as a prerelease so users will have it right away. The docs will of course also automatically updated. Congrats to your first contribution! We have difficulty/low issues if you want to advance in your "coala-skills" :P something like https://github.com/coala-analyzer/coala-bears/issues/118 is usually very rewarding for contributors

**Pull request merged**
