### PR TITLE
Lint.py: Fix typo in function header

### PR DESCRIPTION
**Pull request by Hydro8182**
Correcting configuation to configuration in a function header.

Fixes https://github.com/coala-analyzer/coala/issues/2477

### CODE REVIEW

**Comment by tushar-rishav** [comment]
@Hydro8182 Hey! Thanks for the contribution. IMO it'd be nice if we can make the commit short log even better with something like: 
>Fix typo in `config_file` docstring.

You might also wanna rebase and then we are ready for merge. Feel free to ask us at Gitter if help is needed. :)

**Comment by sils1297** [comment]
So in addition we don't want to have a `Fixes` but a `Closes` - that's important for our bug prediction routines. (Typos aren't bugs :))

**Comment by sils1297** [comment]
Rebase help:

[This page](http://coala.readthedocs.org/en/latest/Users/Tutorials/Git_Help.html) may help you to get started on this. (*Do not press the update branch button. It's evil.*)

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix it up for you - just tell us :).

Ping us on [our gitter channel](https://gitter.im/coala-analyzer/coala) if you need help!

**Comment by sils1297** [comment]
Hey,

there's one last thing with your commit: we usually don't want a period at the end of the phrase in the first line as it makes it longer than needed and a 50 char limit is pretty strict. So for consistency we never want it there.

**Comment by Hydro8182** [comment]
Okay, I hope i did everything correctly.

**Comment by sils1297** [comment]
Yes you did! Great :) https://github.com/coala-analyzer/coala/pull/2632/commits/e59ae8227e9f5cdd35a3eab99c4625805a90f26e is ready

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
Hey, this is your first contribution, right? Congrats and welcome to the coalaians! :)

Rultor will now automatically release your changes as a prerelease so users can experience the goodness of your changes right now.

See also https://github.com/coala-analyzer/coala/wiki/coala-Steam-Offer btw.

**Pull request merged**
