### PR TITLE
Moving bears out

### PR DESCRIPTION
**Pull request by AbdealiJK**

### CODE REVIEW

**Comment by sils1297** [comment]
tests fail

**Comment by sils1297** [comment]
still

**Comment by AbdealiJK** [comment]
@sils1297 f you notice, thats a circleci issue (again only 1 container)
Thats happened twice in a row...

**Comment by AbdealiJK** [comment]
The last commit (using collect_registered_bears_dirs() in Constants) is breaking something makine Dbus fail

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
