### PR TITLE
Makman2/pylintbear fix

### PR DESCRIPTION
**Pull request by Makman2**

### CODE REVIEW

**Comment by Makman2** [comment]
We can discuss the name `shellify_path_argument` :P

**Comment by AbdealiJK** [comment]
Hey, the whole Shell module in coalib is really not needed - there is already a shlex in python - https://docs.python.org/3.2/library/shlex.html#shlex.quote

In 3.2.5, you'd need to use `pipe.quote()`

**Comment by Makman2** [comment]
@AbdealiJK `shlex.quote` does not work
And also I don't want to check every time the python version to determine which function to use, so this would be anyway the reason to make a function that generalizes the behaviour

**Comment by AbdealiJK** [comment]
Could you elaborate on why `shlex.quote` does not work? Or in what way it
does not work ? On windows ?

**Comment by Makman2** [comment]
I just tried to use `shlex.quote(filename)` in the PyLintBear, but it failed again like before because of spaces in my working directory.
Btw this is the code from `shlex.quote()` (copied from python source)
```
def quote(s):
    """Return a shell-escaped version of the string *s*."""
    if not s:
        return "''"
    if _find_unsafe(s) is None:
        return s

    # use single quotes, and put single quotes into double quotes
    # the string $'b is then quoted as '$'"'"'b'
    return "'" + s.replace("'", "'\"'\"'") + "'"
```

**Comment by Makman2** [comment]
This extreme `"'"'"` usage looks a bit weird to me and really not Windows proof (and Windows confirmed me that)

**Comment by sils1297** [comment]
@rultor merge

**Comment by Makman2** [comment]
I rebase...

**Comment by Makman2** [comment]
reack for all

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
