### PR TITLE
make "error handling" headline consistent

### PR DESCRIPTION
**Pull request by rishabhs95**

### CODE REVIEW

**Comment by rishabhs95** [comment]
Fixes https://github.com/coala-analyzer/coala/issues/2133

**Comment by Adrianzatreanu** [comment]
Hello, the change is alright. There's one more thing you need to change: the commit message. They are very important as we keep track of changes using them. here's more info if you want to learn how to right amazing commit messages http://coala.readthedocs.io/en/latest/Getting_Involved/Writing_Good_Commits.html

**Comment by Adrianzatreanu** [comment]
in a nutshell, it should be something like: ``Install.rst: Make ``Error Handling`` headline consistent``
``Newline here``
``Fixes #2133``

**Comment by Adrianzatreanu** [comment]
to change your last commit, please use ``git commit --amend`` in the command line after making the change and using ``git add`` on the file, and then push again! :)

**Comment by Adrianzatreanu** [comment]
No need to specify full path. Instead use something like ``Install.rst: Change Error Handling head style`` or even without style if it is over the 50 chars limit?

**Comment by rishabhs95** [comment]
actually, @sils1297 told me to make the make the commit message like this so it gives a clear idea of 'where' and 'what' the edit is.

**Comment by Adrianzatreanu** [comment]
alright then, keep it like this :)

**Comment by Adrianzatreanu** [comment]
ack 1044132

**Comment by sils1297** [comment]
@rultor merge

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Pull request merged**
