### PR TITLE
Sils/backport

### PR DESCRIPTION
**Pull request by sils1297**

### CODE REVIEW

**Comment by sils1297** [comment]
The following commits are cherry picked backports:

	4a66518
	689dc15
	f863bc1

**Comment by Adrianzatreanu** [comment]
ack 18c9308

**Comment by Adrianzatreanu** [comment]
ack 689dc15

**Comment by Adrianzatreanu** [comment]
ack 4a66518

**Comment by Adrianzatreanu** [comment]
ack 18c9308

**Comment by Adrianzatreanu** [comment]
ack f863bc1

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
