### PR TITLE
lint: Add tutorial link to class docstring

### PR DESCRIPTION
**Pull request by aayn**
Tutorial link 'Linter Bears' added to the docstring of class `Lint`.

Fixes https://github.com/coala-analyzer/coala/issues/1551

### CODE REVIEW

**Comment by aayn** [comment]
Okay. Will do.

**Comment by sils1297** [comment]
unack 39148e0d71d79210b95aefd6fec6818c6347c053 , also the tag in the commit message should rather be `Lint` or something like that, not docs, since you're not changing docs but the docs of the Lint class.

**Comment by aayn** [comment]
@sils1297 How do I change the commit message of an already submitted PR? Will `git amend` work?
Also, how do I make changes while commit being the same one?

**Comment by sils1297** [comment]
git commit --amend will do the job, then git push --force it up to your
branch

2016-02-19 18:30 GMT+01:00 Aayush Naik <notifications@github.com>:

**Comment by aayn** [comment]
@sils1297 Anything else that I should add?

**Comment by aayn** [comment]
And, for the small description about the class, "Deals with creation of linting bears." good enough or should I add more?(I haven't put that in the commit yet; I will, once it is decided what I should put there)

**Comment by sils1297** [comment]
it suffices, if you feel like it feel free to elaborate a bit

**Comment by aayn** [comment]
@sils1297 All done. :)

**Comment by sudheesh001** [comment]
@aayn One last thing, maybe we could do better with the commit message
How about `lint: Add tutorial link to class docstring` 

unack 05ecf1e

**Comment by aayn** [comment]
@sudheesh001 Okay, sure thing.

**Comment by aayn** [comment]
@AbdealiJK If you've approved this, why does it still say manual review pending?

**Comment by AbdealiJK** [comment]
@aayn Im guessing you pushed again, and the new commit was not acked

**Comment by AbdealiJK** [comment]
ack  2bc8418

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
