### PR TITLE
towards pytest - continuation

### PR DESCRIPTION
**Pull request by sils1297**

### CODE REVIEW

**Comment by Makman2** [comment]
@sils1297 can't you make a skip-function for the dbus stuff? less code duplication^^

**Comment by sils1297** [comment]
@Makman2 it's not really duplication, it covers different imports everywhere, hard to put into a function.

**Comment by Makman2** [comment]
can't you just import dbus completely and see whether it fails or not? That could fit into a function^^

**Comment by sils1297** [comment]
@Makman2 then the other imports will fail and everything will error out again

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
