### PR TITLE
Processing.py: Modify Auto-apply message

### PR DESCRIPTION
**Pull request by nishant-mor**
Fixes https://github.com/coala-analyzer/coala/issues/1425

### CODE REVIEW

**Comment by sils1297** [comment]
@nishant-mor apparently a test needs to be adapted

**Comment by nishant-mor** [comment]
so after updating the test should i ammend the commit or add a new commit ?

**Comment by sils1297** [comment]
@nishant-mor amend please :)

**Comment by sils1297** [comment]
@nishant-mor just do `git rebase --interactive` ane mark your new commit as `fixup`

**Comment by nishant-mor** [comment]
before rebase all test passed but after rebase getting this error.

**Comment by sils1297** [comment]
FWIW tests seem to be about to pass https://circleci.com/gh/coala-analyzer/coala/4288

**Comment by sils1297** [comment]
unack 8b2141c, minor commit message correction and then we can merge it : )

**Comment by sils1297** [comment]
ack  1d8154b :) you're ready to go beyond newcomer issues now

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@nishant-mor see, you've got your own development release just for your commit: https://pypi.python.org/pypi/coala/0.4.1.dev20160213203449

**Pull request merged**
