### PR TITLE
LanguageDefinition: Remove 'language_family'

### PR DESCRIPTION
**Pull request by abhsag24**
Fixes https://github.com/coala-analyzer/coala/issues/1811

### CODE REVIEW

**Comment by abhsag24** [comment]
@Makman2 does this suffice? 
i guess we have to make this change soon since bears are already using this we already have  the `AnnotationBear` using this and also `VariableCasing` bear and `IndentationBear` which are in the works

**Comment by abhsag24** [comment]
@fneu review needed here too

**Comment by fneu** [comment]
@abhsag24 technically that looks fine to me, so consider this commit basically acked. Strategically I'd like to wait on input from @Makman2 since you guys were discussing this in the issue.

**Comment by fneu** [comment]
ack https://github.com/coala-analyzer/coala/pull/2208/commits/827ff4e28bff3cbf87bb46b2fa51cbf4098fadf2

**Comment by Makman2** [comment]
it results somehow in settings duplication, but from conceptual perspective this is way better imo

imo you are good to go, just rebase and lgtm :+1:

**Comment by abhsag24** [comment]
reack 2a6f429

**Comment by abhsag24** [comment]
reack a11611f

**Comment by abhsag24** [comment]
@rultor merge

**Pull request merged**
