### PR TITLE
improved documentation

### PR DESCRIPTION
**Pull request by prodicus**
Hey guys, I tried fixing some typos and improving the documentation a little bit. Let me know if it needs any change.

### CODE REVIEW

**Comment by AbdealiJK** [comment]
@prodicus Ive sent you an invitation to add you to coala-analyzer's org so that we can assign you to issues you are working on :)

**Comment by tushar-rishav** [comment]
@prodicus Looks better. Needs rebase though. :)

**Comment by SanketDG** [comment]
Running coala over your code should fix everything on the CI.

**Comment by prodicus** [comment]
@SanketDG How do I do that? @tushar-rishav I have already rebased it to a single commit if that is what you are referring. 

How is the CI failing between?

**Comment by SanketDG** [comment]
@prodicus 

Just type `coala` in your shell, and follow the instructions.

**Comment by SanketDG** [comment]
@prodicus 

You will need to rebase to the latest master:

First you will have to add a remote (conveniently named `upstream`) that points to the `upstream` master of coala:

```shell
git remote add upstream git@github.com:coala-analyzer/coala.git
```

You will need to fetch the new commits since last update

```shell
git fetch upstream
```

and then apply them on your branch

```shell
git rebase upstream/master
```

Then force push, I hope you know how to do that! :D

**Comment by prodicus** [comment]
@SanketDG Rebased it. The error for **circle-ci** now says something like 

```sh

Project wide:
|    | [NORMAL] GitCommitBear:
|    | Shortlog of HEAD commit is too long.

coala-ci returned exit code 1
```

**Comment by SanketDG** [comment]
@prodicus take a look at the first point of http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html#shortlog

**Comment by prodicus** [comment]
Will make another PR. Was having issues with this one. :dizzy_face:

**Comment by tushar-rishav** [comment]
You need not close PR to fix your stuffs. Just do `git commit --amend` and
push. :)

**Pull request closed without merging**
