### PR TITLE
Makman2/catch-permission

### PR DESCRIPTION
**Pull request by Makman2**

### CODE REVIEW

**Comment by Makman2** [comment]
@sils1297 Do you know how I shall handle pypy, seems the `PermissionException` was not set^^

**Comment by AbdealiJK** [comment]
Thats unusual. pypy uses python 3.2 ... so, it should have gone to the IOError branch .. not the PermissionError one.
Maybe `sys.version_info` has been overriden to get pypy's version and not python's version ? -- very weird though.

**Comment by Makman2** [comment]
pypy issue should be solved :)

**Comment by Makman2** [comment]
Now it should work...

**Comment by Makman2** [comment]
@rultor merge

**Comment by Makman2** [comment]
@rultor merge already...

**Pull request merged**
