### PR TITLE
Fixed issue no #1412

### PR DESCRIPTION
**Pull request by SambitAcharya**
Delete bears/java/checkstyle.jar and add *.jar to gitignore

### CODE REVIEW

**Comment by sils1297** [comment]
Hi and welcome! I've just sent you an invitation to our team so we can assign you to the bug to avoid duplicate work. Would you mind accepting that? I'll do a review shortly :)

**Comment by SambitAcharya** [comment]
@sils1297 joined the development team.

**Comment by sils1297** [comment]
@SambitAcharya cool, @Makman2 is about to do a review. I'll leave you in his capable hands :)

**Comment by Makman2** [comment]
@SambitAcharya hi, thanks for submitting a PR :)
If you want to get started with coala, you should read http://coala.readthedocs.org/en/latest/Getting_Involved/README.html. There are useful informations inside the docs how we work. Especially we have a review process, that means someone looks over your code and marks it as acknowledged or not.
I need to directly tell you that your commits do not belong to our standard, the commit messages need a bit work :/ . Here's a link on how we do that :)
http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html

Very important to mention is that we use fast-forward merges. That means we **rebase** our Pull-requests/branches to be up-to-date to master, we don't do merge commits, since they clutter commit history heavily. https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase/ contains stuff on how that works.
Because of that: Please **don't** click that `Update branch` button if that appears for you, since this does a merge commit^^

If you have any questions, be sure to drop by at our gitter channel, there are many others (beyond us maintainers) that are there to help you :)
Especially for organizational purposes gitter is a good address for asking questions, assigning issues etc. etc.

Phew I think that's all (more or less)...

**Comment by SambitAcharya** [comment]
@Makman2 Thanks for the inputs. I would go through the documentation and resubmit my PR.

**Comment by sils1297** [comment]
@Makman2 why are all the builds failing though? I see not much reason for that...

**Comment by Makman2** [comment]
Alright, so concretely on your commits:
We normally use a tag before the shortlog message, so like this:
`Core: Add new param to my_func`
So the tag `Core` addresses where something happens, while the shortlog tries to explain as detailed as possible what was changed. But we allow only 50 chars for the complete shortlog^^ Then you would try to move out details into the body of the commit.

So the second commit should be changed to something like `.gitignore: Add .jar files`
And the second commit, I don't know a tag, so I would say the shortlog can stay as it is, but the body needs a bit adjustment. We use githubs auto-close-issue functionality here, so please just do `Fixes https://github.com/hardlink/to/issue`. Like you see don't use a plain issue ID, but the complete link. GitHub has made a web-ui update so I can't distinct that any more^^

Phew that was again quite much... :D

**Comment by SambitAcharya** [comment]
@Makman2 that explanation was excellent. I will follow this format for the rest of my contributions. 

And what about the build fails. Can you guide me on that?

**Comment by Makman2** [comment]
@SambitAcharya try to fix the commits like suggested, if the builds do fail again (indeed the message is weird there) I'll take care of that^^

**Comment by sils1297** [comment]
@Makman2 the failures are related to the commits actually, AppVeyor doesn't run `setup.py` which auto-downlaods the jar he deletes in the commit and this the CheckstyleBearTest fails

**Comment by sils1297** [comment]
@SambitAcharya hey, we recommend you drop by at https://gitter.im/coala-analyzer/coala :) we're just discussing your issue

**Comment by SambitAcharya** [comment]
@Makman2 @sils1297 please review my latest PR

**Comment by sils1297** [comment]
superseded by https://github.com/coala-analyzer/coala/pull/1463 , please close old PRs if you create new ones. Though we usually recommend just force pushing on the branch, that makes things way easier for you and for us.

**Comment by SambitAcharya** [comment]
@sils1297 will take care of that from next time.

**Pull request closed without merging**
