### PR TITLE
Git_Help.rst: Section explaining commit squashing

### PR DESCRIPTION
**Pull request by saurabhiiit**
Fixes https://github.com/coala-analyzer/coala/issues/1789

### CODE REVIEW

**Comment by sils1297** [comment]
please see http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html for your commit message which is in past tense

**Comment by saurabhiiit** [comment]
@sils1297  Sorry but you misunderstood, I have noticed your comment and then I have changed my commit messages according to the present tense, Document which I wrote is in preset tense, And I have read the document , Please don't feel like I am insulting

**Comment by sils1297** [comment]
I left two comments, one about the message, one about the content.

**Comment by saurabhiiit** [comment]
@sils1297  Thanks for pointing I will change that

**Comment by saurabhiiit** [comment]
@sils1297  Please give more clue where change is required.

**Comment by sils1297** [comment]
just tell the user to rebase onto master instead of explaining the whole HEAD~... story

**Comment by saurabhiiit** [comment]
Sure !!!

**Comment by srisankethu** [comment]
@saurabhiiit I seems you misunderstood when he asked you to change your commit message.Changing commit message doesn't mean changing PR title. Try `--amend` flag to git commit to rewrite your commit message. Your PR title change earlier seems a good commit message "Git_Help.rst: Add a section explaining commit squashing".

**Comment by saurabhiiit** [comment]
@srisankethu Earlier I thought that only and I changed my commit messages both from PR and the commit message but I think their is some issue related to document

**Comment by sils1297** [comment]
otherwise good, needs a rebase while your at it

**Comment by saurabhiiit** [comment]
thanks ....... yeah sure I will do that

**Comment by srisankethu** [comment]
Seems good! GREAT :+1:

**Comment by sils1297** [comment]
code looks good but the commit message doesn't refer to the issue you're fixing but to this PR which is wrong, @saurabhiiit can you fix that?

**Comment by saurabhiiit** [comment]
Thanks ..........Yes I will do that.

**Comment by srisankethu** [comment]
@saurabhiiit Any issues ?

**Comment by saurabhiiit** [comment]
@srisankethu my commit message doesn't refer to the issue I am fixing, do you have any idea ??

**Comment by srisankethu** [comment]
@saurabhiiit Yes! Your are  referencing to this PR. Try this `git commit --amend -m "Commit message" -m "Fixes https://github.com/coala-analyzer/coala/issues/1789" ` .

**Comment by saurabhiiit** [comment]
@srisankethu  thanks !!!

**Comment by srisankethu** [comment]
@saurabhiiit No problem :+1:  Contact us if any issues at https://gitter.im/coala-analyzer/coala

**Comment by srisankethu** [comment]
Seems good! GREAT :+1:

**Comment by sils1297** [comment]
ack 3e48cf948f :)

**Comment by sils1297** [comment]
@rultor merge

**Comment by saurabhiiit** [comment]
Thanks !!!

**Comment by sils1297** [comment]
@saurabhiiit I know review can sometimes be painful but we're releasing this right ahead to our users so we gotta make sure everything is clean.

**Comment by sils1297** [comment]
@saurabhiiit thus thank you for your contribution! We value every contribution. ATM it's very stressful so sometimes we forget to say that.

**Comment by saurabhiiit** [comment]
@sils1297  This process makes me learn a lot , which is ultimately fruitful for me . :+1:

**Pull request merged**
