### PR TITLE
GemRequirement: Add it

### PR DESCRIPTION
**Pull request by Adrianzatreanu**

### CODE REVIEW

**Comment by sils1297** [comment]
ack https://github.com/coala-analyzer/coala/pull/2364/commits/b00dda26700c2aa86e64d4abb2c8eb1020970248

**Comment by arafsheikh** [comment]
Shouldn't this be called `RubyRequirement` like we already have `PythonRequirement`?

**Comment by Adrianzatreanu** [comment]
i guess the name can be debatable. we also have ``NpmRequirement``

**Comment by sils1297** [comment]
I think we should rename pythonrequirement to piprequirement

**Comment by Adrianzatreanu** [comment]
don't merge this please

**Comment by sils1297** [comment]
https://github.com/coala-analyzer/coala/pull/2364/commits/c0fe74da3cdae001bb3a4c44ce78b2659b9fd40f ack

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Pull request merged**
