### PR TITLE
added support for single marker_set in markers

### LINKED ISSUE #1141: `DocstyleDefinition`: Accept a single marker set also
Via the normal constructor or a class method.

### PR DESCRIPTION
**Pull request by vadi95**
fixes #1141

### CODE REVIEW

**Comment by sils1297** [comment]
hey, can you look at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/#how-to-write-good-commit-messages for your commit message? It especially lacks a link to the issue.

Also the tests seem to be failing, let us know if you need help.

**Comment by vadi95** [comment]
Hope this is better :). No idea why CircleCI is failing though :(

**Comment by sils1297** [comment]
@vadi95 can you squash your commits? Use `git rebase --interactive`

**Comment by sils1297** [comment]
@vadi95 please run coala over your code, it'll tell you what to do, if you fix all issues, circleci will pass

**Comment by sils1297** [comment]
unack 12c97ec 41bf596, needs work

**Comment by sils1297** [comment]
ack cd418236893 now we've got it, thanks! :)

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
rultor sometimes faces nondeterministic issues. It automtically releases the stuff btw. so you can install it right away via `pip3 install coala --pre` :)

**Pull request merged**
