### PR TITLE
Fix a typo (missing word)

### PR DESCRIPTION
**Pull request by knewter**

### CODE REVIEW

**Comment by sils1297** [comment]
Hi @knewter thanks for your interest and welcome!

Your commit seems already great, the only thing I can find at this point is that the commit message could be a bit more precise, giving some context with a tag and explaining in the shortlog (it's not exactly a typo but a grammar issue right?)

We have some documentation [here](http://coala.readthedocs.io/en/latest/Getting_Involved/Writing_Good_Commits.html#how-to-write-good-commit-messages) and I'm sure you'll easily be able to figure it out :) If you need help I'm of course here, just ask.

https://github.com/coala-analyzer/coala/pull/2434/commits/299746eb3e1730e74b581f6d9235cdbb7ee6a19b needs work

**Comment by Adrianzatreanu** [comment]
hey @knewter are you still there :) ?
if there's anything we can help you with, ping us here and we'd love to help you https://gitter.im/coala-analyzer/coala

**Comment by Makman2** [comment]
@knewter if you don't mind I would take over this PR :)

**Comment by Makman2** [comment]
https://github.com/coala-analyzer/coala/pull/2637 takes over.

**Pull request closed without merging**
