### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by alan-martinovic**
Fixes https://github.com/coala-analyzer/coala/issues/2508

### CODE REVIEW

**Comment by Asnelchristian** [comment]
you need to improve a bit on your commit short log, use this as reference 
http://coala.readthedocs.io/en/latest/Getting_Involved/Writing_Good_Commits.html

btw the commit looks good :) :+1:

**Comment by Asnelchristian** [comment]
you short log is too long

**Comment by Asnelchristian** [comment]
you can use ``ConsoleInteraction: Change ``give``->``given```` :) [just a proposition] :)

**Comment by alan-martinovic** [comment]
Seems like amending the commit broke some tests...?

**Comment by Asnelchristian** [comment]
nope it is just because you short log was too long

**Comment by Asnelchristian** [comment]
'``give`` -> ``given'

**Comment by sils1297** [comment]
https://github.com/coala-analyzer/coala/pull/2512/commits/cf41f81783d0bc1427cc9931f9e8a768478a7acd is ready

**Comment by Asnelchristian** [comment]
```` these are bactsticks

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
How is this saved reply:

--------------

Hi,

it seems that your commit message doesn't contain enough information. Don't worry, most people don't know about good commit messages when they join us, including very experienced developers :)

The most important part is the first line of your commit message - maintainers will use it to read through a large number of commits and thus it's important that it's short but most importantly concise. I'd heartily recommend reading http://coala.readthedocs.io/en/latest/Getting_Involved/Writing_Good_Commits.html !

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

Cheers!

**Pull request merged**
